### ISSUE TITLE
Add Scientific controlled vocabulary to Order and Family fields

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#1019]
Once the new combined Scientific controlled vocabulary is created (#1018), add it to the Order and Family fields.

This may affect existing records with text contents in the Order and Family fields (likely in OSU Herbarium and OIMB slides collections). That text can likely be queried against the ITIS database and the text strings replaced with the ITIS URIs.

**Comment by srabun** [comment]
Ryan is working on these right now
