### ISSUE TITLE
Add help pages for ingest (other?).

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/oregondigital#1038]

**Comment by mccallum** [comment]
Erin's Documentation:
https://docs.google.com/document/d/1EXuIDFy0b1KFPDBQATB6Q-EFzKaOmvm7uuHlIXJPIW4/edit

**Comment by mellinma** [comment]
Inline help to OD2, but add About link under the text block on the main page and also in the footer. Controlled Vocabularies and Vocabularies also.
