### ISSUE TITLE
Ark ID

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/oregondigital#1039]

**Comment by mellinma** [comment]
ARK ID's are in records, but need to be able to pull this information into the finding aids

**Comment by mellinma** [comment]
Consult with Elizabeth Nielsen:  Q: is this view work?

**Comment by mellinma** [comment]
initial idea was to put these along with local collections in ONS.  Punt to OD2.  We do need to make sure finding aids are indicated / well-represented in OD2.
