### ISSUE TITLE
Change lat/long predicates to use Basic Geo (WGS84 lat/long) Vocabulary

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#1154]
The current lat/long predicates are from the EXIF vocabulary, and I think a better fit is the Basic Geo (WGS84 lat/long) Vocabulary: https://www.w3.org/2003/01/geo/
EXIF is closely tied to pictures, and comments in that schema specify that values should be in 'degrees, minutes and seconds' which we've moved away from.  https://www.w3.org/2003/12/exif/

`http://www.w3.org/2003/01/geo/wgs84_pos#lat`
and
`http://www.w3.org/2003/01/geo/wgs84_pos#long`

This will involve changing predicates on all existing records too and reindexing them.

**Comment by vantuyls** [comment]
closed, moved to OD2 Migration Prep.
