### ISSUE TITLE
Modify Decades facet to include Award Date if no Date present

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#1169]
Currently the Decades facet processor only works with a value in the Date field. If there is no Date field value, we'd like to modify it to use Award Date.

This is for the Oregon Century Farm and Ranch applications, which have the main date in Award Date.

**Comment by jsimic** [comment]
Are there any other date types we'd like to add? Issued would be useful.

**Comment by wickr** [comment]
Yes, we could add Issued. Maybe Created too?  I wondered about Earliest Date too, or combine Earliest Date and Latest Date.

So maybe priority would be:
Date
Award Date
Issued
Created
Earliest-Latest

**Comment by wickr** [comment]
Julia said Earliest-Latest wasn't needed, so I'll go forward with this priority:

Date
Award Date
Issued
Created
