### ISSUE TITLE
Fix VRA and CCO predicates in OD

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1208]
vra_ and cco_ predicates in op_ns have not been updated in OD from vra/ and cco/, thus these are showing up in raw statements.

**Comment by jsimic** [comment]
@wickr Can this be addressed soon?

**Comment by lsat12357** [comment]
Working on locating assets that use vra_ and cco_ predicates and adding the current working version (vra/ and cco/).
So far, have identified gb-warner, gb-warner-nosatsu (later batches only),

**Comment by lsat12357** [comment]
also ellis-fuller-lawrence. These (gb-warner, nosatsu, and lawrence) are done as far as I know. Have not found usage anywhere else, so unless anything else turns up (i.e. when we do the big dump) I'm going to stop working on this.
