### ISSUE TITLE
Change predicates for Is Volume, Has Number, Contained in Journal properties

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#1241]
We're no longer using swpo predicates for OD2 and need to change to bibtex. This can be done before the migration to OD2. Full namespaces in OD2 MAP.

- [x] change swpo:isVolume to bibtex:hasVolume
- [x] change swpo:hasNumber to bibtex:hasNumber
- [x] change swpo:containedInJournal to bibtex:hasJournal
- [x] change swpo:onPages to bibtex:hasPages

**Comment by lsat12357** [comment]
looks like there's also swpo:onPages, maybe only used in middle-east-water?

**Comment by lsat12357** [comment]
daily emerald for hasVolume and hasNumber, dissociation and mss for containedInJournal

**Comment by lsat12357** [comment]
have added triples rather than swapping predicates. tentatively making the switch next week. The concern is that the Emerald media folks are still uploading with the fields using swpo.

**Comment by sseymore** [comment]
@lsat12357 metadata team just talked about this. We are OK with swapping out the preds now in OD1. @wickr and @carakey need to discuss onPages and then we can move forward.

**Comment by wickr** [comment]
We decided to go with http://purl.org/net/nknouf/ns/bibtex#hasPages  to replace onPages.

**Comment by wickr** [comment]
Change of swpo:onPages to bibtex:hasPages is complete for Middle East Waters items.

**Comment by lsat12357** [comment]
did some spot checking on scrapes (see digitalprojects/metadata/OD2_Remediation/swpo_bibtex)

**Comment by sseymore** [comment]
This looks done for UO collections.

**Comment by wickr** [comment]
I confirmed Middle East Water, Herbarium, and SCARC PDFs are fully completed.
On the UO side, some collections had the new ones but still had the old ones too, so I removed the old ones from Daily Emerald, Dissociation, and e-Asia.

I didn't find any other collections that had swpo predicates in the mappings I had access to.
If anything else comes up later it will be a quick fix.
