### ISSUE TITLE
Move Support property values to Material, remove predicate

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#1244]
Move any values in the Support property to Material.
Remove the predicate from the system (including ingest form).

**Comment by lsat12357** [comment]
There seem to be only two; one of them is in review and the other seems to be a replacement for it?
https://oregondigital.org/catalog/oregondigital:df67wq320
https://oregondigital.org/catalog/oregondigital:fx71bj562#page/1/mode/1up

**Comment by jsimic** [comment]
@lsat12357 Deleted live version, reviewed newer version, moved data from Support to Material.

**Comment by lsat12357** [comment]
for future self:
irb(main):006:0> ActiveFedora::SolrService.query("desc_metadata__support_teim:[* TO *]", :fl=>'id', :rows=>100)
=> [{"id"=>"oregondigital:fx71bj562"}]
