### ISSUE TITLE
Move Caption Title property values to Alternative Title, remove predicate 

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#1246]
Move Caption Title values to Alternative Title.
For Historic Sheet Music Collection items only.
Remove predicate from system (including ingest form).

**Comment by jsimic** [comment]
There may also be some in aa-images

**Comment by lsat12357** [comment]
I just grepped the dump I have of aa-images and did not have any hits

**Comment by lsat12357** [comment]
sheet music has been done
