### ISSUE TITLE
EDTF work on collections not harvested by MWDL

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1258]
Dates from collections not selected for inclusion in MWDL/DPLA have not been remediated to conform to the EDTF standard.

Included collections:
- [ ] Art and Architecture Images (UO)
- [x] JSMA (UO)

**Comment by jsimic** [comment]
aa-images spreadsheet for date cleanup is DigitalProjects/Metadata/OD2_Remediation/aai_dates_cleanup/aai_dates_deduped.xlsx

**Comment by jsimic** [comment]
Last two groups of corrections for aai are in DigitalProjects/Metadata/OD2_Remediation/aai_dates_cleanup/aa-images-last.xlsx

**Comment by jsimic** [comment]
@lsat12357 Additional work in scrapes from other collections (all spreadsheets in DigitalProjects/Metadata/OD2_Remediation/dateScrapes/)
- [ ] arch-entourage (arch-entourage-dates.xlsx)
- [ ] schnitzer-mofa (schnitzer-mofa.xlsx)
- [ ] corazon-de-dixie (done by hand)
- [ ] texts-data (done by hand)
- [ ] uo-president (don by hand)
- [ ] easia (No corrections)
- [ ] maic
- [ ] wwdl

**Comment by lsat12357** [comment]
did a round of cleanup using reg-exp on schnitzer-mofa. I've rescraped and put the new scrape on teams.

**Comment by lsat12357** [comment]
aa-images no longer has entries for date, earliestDate/latestDate
schnitzer-mofa has edtf valid dates in date
maic has edtf valid dates in viewDate

**Comment by jsimic** [comment]
Spot checked aai. Everything looks good.
