### ISSUE TITLE
Make Rightsholder uncontrolled

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1261]
Remediate Rightsholder URIs to strings.

**Comment by lsat12357** [comment]
It looks like there are two properties in OD1: rightsHolder and dcRightsHolder. The former uses predicate opaquenamespace.org/rights/rightsHolder although it was published in opns as ns/rightsHolder. I should be able to scrape these as long as one of the two registered predicates was used; if ns/rightsHolder was used we won't be able to find it via query.
If we know that ns/rightsHolder was used and in which collection, we can plow through the collection and scrape it that way.
The other alternative is to handle it somehow during migration.

**Comment by lsat12357** [comment]
so a quick count shows that there are 164111 assets that use dcRightsHolder and 74904 that use rightsHolder

**Comment by lsat12357** [comment]
on the UO side, whittled it down to 13803 dcRightsHolder values that use http* and are not UO Libraries Special Collections

**Comment by jsimic** [comment]
@lsat12357 I have no way of checking the legacy collections, since it was one of those "if you know it put it in" situations and inconsistently applied. My best guess is that artists-books might have used the opns pred?
