### ISSUE TITLE
Confirm Locations URIs are pulling Geonames hierarchy

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1262]
Some are pulling narrowest term only. This is a label fetching issue not URI issue

**Comment by sseymore** [comment]
I believe this work can close this ticket. Will check. https://github.com/OregonDigital/OD2/issues/1124

**Comment by wickr** [comment]
Most of this is being resolved as part of preflight cleanup and Geonames label review in OD1.
Labels will refetch in OD2.
