### ISSUE TITLE
Make Location Copy--Shelf Location uncontrolled

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1269]
Remediate Location Copy--Shelf Location URIs to strings

**Comment by lsat12357** [comment]
locationCopyShelfLocator not queryable

**Comment by lsat12357** [comment]
looks like a couple in gwilliams, mss-rb, schnitzer-nitrate, uo-president and a bunch in sheetmusic and percent-for-art

**Comment by lsat12357** [comment]
scraped mss-rb, schnitzer-nitrate, uo-president, sheetmusic, percent-for-art, did not find any uris in locationCopyShelfLocator
