### ISSUE TITLE
Make Series Name uncontrolled

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1270]
Remediate Series Name URIs to strings and deleted opaquenamespace vocab

**Comment by lsat12357** [comment]
alice-b-sheldon
chinavine
gb-warner-papers-ua022
gbwarnerpapers
joanna-russ
joel-palmer
johnyeonarchdrawings
lee-moorhouse
mss-rb
or-latino-herit
quincy-scott
