### ISSUE TITLE
Make Form of Work controlled

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1272]
Remediate Form of Work strings to URIs.

UO only work in Artist's Books collection

**Comment by sseymore** [comment]
Also Western waters

**Comment by sseymore** [comment]
See DigitalProjects/Metadata/OD2_Remediation for URIs to use.

**Comment by lsat12357** [comment]
one lone asset in building-or can be done by hand
https://oregondigital.org/catalog/oregondigital:fx71bz06b#page/1/mode/1up
one lone asset in mss-rb already contains a uri
oregondigital:fx71ch048
a number of assets in angelus also already have uris.

**Comment by lsat12357** [comment]
ran script to either convert string labels to uris using spreadsheet vals or convert string uris to rdf:
artists-books, western-waters, angelus-studio.
