### ISSUE TITLE
Review localCollectionName values export for incorrect URIs or missing data

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#1273]
An export of items with a localCollectionName was done on March 30.

- [x] UO items cleaned up
- [x] OSU items cleaned up

https://docs.google.com/spreadsheets/d/1atOeDro5kkqiYMkNHwTY8iz-4aV-oAaDPj_nYHGgrRA/edit#gid=0

Review for things like missing Institution, URIs with typos or other missing info causing a mismatch.

**Comment by jsimic** [comment]
@lsat12357 There is a spreadsheet for corrections to UO localCollectionName entries in DigitalProjects/Metadata/OD2_Remediation/localCollectionName/localCollectionName_changes.xlsx

**Comment by jsimic** [comment]
There are several other mass corrections that came out of the localCollectionName scrape. There are spreadsheets in the DigitalProjects/Metadata/OD2_Remediation/localCollectionName folder:

Institution_changes.xlsx
Missing_Identifiers.xlsx
schnitzer-nitrate_dateChanges.xlsx
Title_changes.xlsx

**Comment by lsat12357** [comment]
the additional spreadsheets have been done. Some of these seem to be items that are in review and have a duplicate that is live.
