### ISSUE TITLE
Make Designer controlled (OSU only)

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#1275]
Make the Designer field controlled like other Creator fields.

An export was done in February, with 475 values, all from the Historic and Cultural Textile and Apparel Collection.  (more likely came in with recent batch upload there).

- [x] Find or create URIs for values - Kevin
- [x] Batch load new names to ONS - Ryan
- [x] Change Designer field to be controlled - Ryan
- [x] Change text strings to URIs - round 1 - Ryan
- [x] Find or create URIs for 'round 2' values - Kevin
- [x] Change text strings to URIs - round 2 - Ryan

**Comment by luisgreg99** [comment]
Found strings in the Designer field for Historic_and_Cultural_Textile_and_Apparel_Collection seed data. I added the list of occurrences in second bullet in this ticket: [Historic_and_Cultural_Textile_and_Apparel_Collection (seed data) preflight check issues #1380
](https://github.com/OregonDigital/oregondigital/issues/1380)

**Comment by KevinJonesMeta** [comment]
URIs found or created. 216 new ONS names ready to be added in batch.

**Comment by wickr** [comment]
214 names batch loaded to ONS (1 was duplicate, 1 was header)

**Comment by wickr** [comment]
After making replacements, there are an additional 40 unique names remaining (likely from more recent batches). These are on the 'round2' sheet.

**Comment by wickr** [comment]
Work is complete. Round 2 of name mapping to URIs was completed, and a few remaining entries were modified by hand. Another export found no remaining text values.
