### ISSUE TITLE
Make Owner controlled (OSU only)

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#1276]
Make Owner a controlled field like other Creator fields

An export was done in February, with around 2000 existing values, from OSU collections.

- [x] Find or create URIs for existing values
- [X] Change Owner field to be controlled
- [x] Change URIs as text strings to be URIs (242)
- [x] Map text strings to URIs
- [x] Final cleanup

**Comment by luisgreg99** [comment]
During preflight checks for metadata refresh, I found strings in "Owner" field on these seed data collections:
- [Century_Farm_and_Ranch_applications (seed data) preflight check: invalid URIs #1370](https://github.com/OregonDigital/oregondigital/issues/1370)
- [Baseball_jpegs (seed data) preflight check issues #1371](https://github.com/OregonDigital/oregondigital/issues/1371)

**Comment by KevinJonesMeta** [comment]
Portion of new ONS URIs are in ONS review queue and portion on sheet in Google doc.

**Comment by wickr** [comment]
Text strings have all been replaced with URIs for 1113 values.

There's label issues with 21 values that need investigation, some URIs may not yet exist.

There's 94 remaining text strings, 23 of which are 'Renter'. Some of these look to be recent additions after the Owner export was initially done.

**Comment by wickr** [comment]
All known remaining cleanup work has been completed. A further check for label issues found nothing.
