### ISSUE TITLE
Replace "City of" and "Town of" geonames URIs

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1277]
A small number of geonames URIs point to the Administrative Division rather than the Populated Place URIs and pull labels with the prefixes "City of" or "Town of". Replace the ADIMs with the equivalent PPL URIs. ca. 250 entries in Location.

@lsat12357 Spreadsheet with old and new URIs is in DigitalProjects/Metadata/OD2_Remediation/CityTownOf_replacements.xlsx

**Comment by lsat12357** [comment]
this should be done.

**Comment by sseymore** [comment]
@jsimic do you want to QA this to confirm it's done?

**Comment by jsimic** [comment]
Found a single "City of" and hand corrected. Closing.
