### ISSUE TITLE
check cpds for deleted children

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/oregondigital#1278]
I just found a cpd that has a deleted child. At the moment, this means that the child is still showing up on the list in the show page, and if the user clicks on it she will get a login page.
Deleted children need to be removed from the parents before migration otherwise the parents will fail.

**Comment by lsat12357** [comment]
uo-veterans is done
mss-rb has one object with a couple of pages listed in the cpd that don't exist.
https://oregondigital.org/catalog/oregondigital:df7363445 is the child just above the missing pages.

**Comment by sseymore** [comment]
mss-rb remediation is happening now; won't migrate to OD2

**Comment by lsat12357** [comment]
this should be addressed by the preflight/remediation project.
