### ISSUE TITLE
Delete assets

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#1279]
Some assets in OD1 were migrated from CDM with missing information. These items have been re-digitized and re-uploaded. Please delete. PIDs here: https://docs.google.com/spreadsheets/d/1zGzF-PcbbQ-hKgGeLkz-Wmt2y0EvItMaS5Fpa7gXvvo/edit#gid=600114530

**Comment by lsat12357** [comment]
ok this is done
