### ISSUE TITLE
Cleanup for institutions, sets, and primary sets

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#1280]
Some items in OD1 did not have URIs for set, primary set, and/or institution, which is required information for admin set functionality in OD2. Please remediate these items: https://docs.google.com/spreadsheets/d/1zGzF-PcbbQ-hKgGeLkz-Wmt2y0EvItMaS5Fpa7gXvvo/edit#gid=4707888

**Comment by lsat12357** [comment]
It looks like these are all chinavine items?
(are there really items on this sheet that don't have set?)
for the items in the list that are children, we can't add primarySet but we can add institution.

**Comment by sseymore** [comment]
Agh, sorry -- yes, only add pset URI to cpd items. In the spreadsheet, there are other tabs for other collections, so not just all chinavine.

**Comment by lsat12357** [comment]
the joel-palmer cpds that needed fixes from the "other" tab all had children with primarySet, will remove.

**Comment by lsat12357** [comment]
have run changes on chinavine, western-waters, schnitzer-mofa, building-or, and the few odd ones on "other"

**Comment by sseymore** [comment]
done!
