### ISSUE TITLE
OD1 mongo hardening and monitoring

### ISSUE THREAD

**Issue by decimalator** [OregonDigital/oregondigital#1291]
### Descriptive summary

The OD1 issues from 12/2 were caused by the OD1 MongoDB database server lib-mongo1 rebooting and mongod not being set to start at boot time.

- [x] set mongod up to start at boot time
- [x] add monitoring for mongod so we know if it's down specifically

**Comment by raybrarian** [comment]
Added to OD2 WC8 project board for visibility.
