### ISSUE TITLE
Remove empty RDF List blank nodes from items

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#1305]
Compound objects have, on the parent item, the child pids stored in the :od_content ( predicate. Some items however have a blank node off this predicate with only a value of type of RDF List. 

```
<http://oregondigital.org/resource/oregondigital:df65w5293> <http://opaquenamespace.org/ns/contents> _:g69919205264720 .
_:g69919205264720 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#List> .
```

I think this is legacy metadata from the original compound object method. But it's essentially empty and is causing problems in the OD2 migration, so they can be removed.

Collections known to have items with these values:
- [x] Herbarium: 4617 items, 4087 affected and changed
- [x] Fairbanks: 473 items, 471 affected and changed
- [x] Gerald Williams: 2027 items, 10 affected and changed
- [x] Oregon Multicultural Archives: 3315 items, 43 affected and changed
- [x] Lincoln County Historical Society: 1393 results, 1393 affected and changed

There may be others. 
Already checked but found nothing: Braceros; Rocky Shore 93; Art, Architecture and Design; Columbia Gorge; Gifford; J.F. Ford; Middle East Water; Baseball; Extension Oral Histories; Oregon Explorer; Stream Survey; Rising Flood Waters; Siuslaw

**Comment by wickr** [comment]
First pass didn't actually delete the blank node, but I've gone back and got them too now.

Also still checking other Collections.

**Comment by luisgreg99** [comment]
Herbarium and Fairbanks are looking good for the seed data after getting a re-export today.

**Comment by wickr** [comment]
I checked all of the OSU collections that I thought were relevant (list above) and all of the items I could find have been cleaned.
