### ISSUE TITLE
OD1 raw statements remediation: Delete predicate and object(s)

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#1312]
Please delete these predicate URIs and corresponding object data:

http://www.w3.org/2000/01/rdf-schema#label
http://www.geonames.org/ontology#countryCode
http://www.geonames.org/ontology#name
http://www.w3.org/2004/02/skos/core#prefLabel

These appear in these collections:

1993 ODFW Oregon Rocky Shore Aerial Photography Survey
African Political Ephemera and Realia Project
Braceros in Oregon Photograph Collection

**Comment by sseymore** [comment]
left off here in WC10; pick up WC11

**Comment by lsat12357** [comment]
african-ephemera done

**Comment by wickr** [comment]
These predicates were cleaned up by preflight work.
https://github.com/OregonDigital/oregondigital/issues/1532
https://github.com/OregonDigital/oregondigital/issues/1501
