### ISSUE TITLE
Another scrape request: hasFormat

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#1313]
Please scrape this predicate and object data for the metadata team to review.

http://purl.org/dc/terms/hasFormat

Appears in these collections:

Gifford Photographic Collection
Picturing the Cayuse, Walla Walla, and Umatilla Tribes

**Comment by lsat12357** [comment]
moorhouse has 287 items with "Glass-plate negative"

**Comment by lsat12357** [comment]
for gifford,
6.5x8.5 glass negatives;
5x7 stereoscopic glass negatives;
6.5x8.5 glass positives;
8x10 copy negatives;
5x7 glass negatives;
4x6 glass negatives;
8x10 glass negatives;
11x14 glass negatives;
5x7 copy negatives;
8x10 glass positives;
11x14 copy negatives;
5x8 glass negatives;
8x10 nitrate negatives;
6x8 nitrate negatives;
5x10 nitrate copy negatives;
8x10 glass;
5x7 glass;
4.25x6.5 glass negatives;
4x5 glass negatives;
4.25x6.5 glass negative;
6.5x8.5 copy negatives;
4.25x6.5 glass positive;
5x7 glass positives;
4.25x6.5 glass negative
1x1 print on a 2x4 card
4x5 negatives;
5x7 negatives;
4x5 color transparency;
5x7 color transparency;
5.5x8.5 glass negatives;
5x7 nitrate negatives;
5x8 glass negatives; 5x7 stereoscopic glass negatives;
8x10 negatives
8x10 color transparency;
8x10 negatives;

**Comment by sseymore** [comment]
please move all data values in has format to has version. thanks.

**Comment by sseymore** [comment]
This is done for UO items. @wickr might need to check Gifford.

**Comment by wickr** [comment]
hasFormat moved in Gifford: https://github.com/OregonDigital/oregondigital/issues/1374
