### ISSUE TITLE
Control Donor field: Columbia Gorge Discovery Center Photo Archive

### ISSUE THREAD

**Issue by carakey** [OregonDigital/oregondigital#1320]
Parent issue #1271 

All records in this batch should have the same LC URI.

- [x] Clean up name values
- [x] Search for existing URIs
- [x] Batch edit: Replace Donor strings with URIs

**Comment by carakey** [comment]
8434 item records; 2 unique extant values; 1 unique replacement URI.

Existing Donor values are all either 'http://id.loc.gov/authorities/names/no2005000226' or 'http://id.loc.gov/authorities/names/no2005000226 ( http://id.loc.gov/authorities/names/no2005000226 )' 
The former is correct; unsure why it appears in the export. All values should be replaced with 'http://id.loc.gov/authorities/names/no2005000226'

Batch replace list: https://docs.google.com/spreadsheets/d/1UBPQ2osT6a6L1yzQ-gsbcJA542NjWuq3IzqtgtNBj80/edit#gid=304688384

**Comment by wickr** [comment]
Batch replace finished, there are now 8435 public items with the Donor value.

**Comment by carakey** [comment]
URIs appear and resolve, numbers are correct. QA pass.
