### ISSUE TITLE
Control Donor field: Historic and Cultural Textile and Apparel Collection

### ISSUE THREAD

**Issue by carakey** [OregonDigital/oregondigital#1321]
Parent issue #1271 

- [x] Clean up name values
- [x] Search for existing URIs
- [x] Create ONS records
- [x] Determine alternative text field and verbiage for messy data
- [x] Batch edit 1: Replace Donor strings with URIs 
- [x] Batch edit 2 (for messy data): Insert / append remediated name value in text field and remove value from Donor field

**Comment by luisgreg99** [comment]
Found strings in the Donor field for Historic_and_Cultural_Textile_and_Apparel_Collection seed data collection. I added the list of occurrences in this ticket: [Historic_and_Cultural_Textile_and_Apparel_Collection (seed data) preflight check issues #1380
](https://github.com/OregonDigital/oregondigital/issues/1380)

**Comment by carakey** [comment]
Donor strings in seed data from #1380 have been updated to URIs (18 items).

**Comment by carakey** [comment]
Batch CSV of 106 names ready to upload to ONS. Additional names were added manually to ONS in seed data remediation and while processing of a new batch of HCTAC items in September/October.

https://docs.google.com/spreadsheets/d/1UBPQ2osT6a6L1yzQ-gsbcJA542NjWuq3IzqtgtNBj80/edit?pli=1#gid=1623922999

(Arg, why doesn't GH support adding CSV files to tickets?)

**Comment by carakey** [comment]
Two batches of updates are ready. 
Batch 1 (1,199 items): Replace existing Donor value with URI(s).
Batch 2 (181 items): Add remediated text value as Provenance + remove Donor field.

**Comment by wickr** [comment]
Both batch edits 1 and 2 are complete.
