### ISSUE TITLE
Control Donor field: Middle East Water Collection

### ISSUE THREAD

**Issue by carakey** [OregonDigital/oregondigital#1322]
Parent issue #1271 

- [x] Clean up name values
- [x] Search for existing URIs
- [x] Batch edit: Replace Donor strings with URIs

**Comment by carakey** [comment]
7517 item records; 3 unique donor values; 3 replacement uris

Batch replace list: https://docs.google.com/spreadsheets/d/1UBPQ2osT6a6L1yzQ-gsbcJA542NjWuq3IzqtgtNBj80/edit#gid=1132344934

**Comment by wickr** [comment]
Batch replace completed. 7515 values showing in facet. The 2 'missing' were from deleted items.

Also updated the Collection info donor pages links to use the new Donor facet.

**Comment by carakey** [comment]
Numbers match, facets look good, URIs resolve. QA pass.
