### ISSUE TITLE
Control Donor field: Oregon Hops & Brewing Archives

### ISSUE THREAD

**Issue by carakey** [OregonDigital/oregondigital#1325]
Parent issue #1271 

- [x] Clean up name values
- [x] Search for existing URIs
- [x] Create ONS records
- [x] Batch edit: Replace Donor strings with URIs

**Comment by carakey** [comment]
Need review of ONS record: http://opaquenamespace.org/review/people/LarranceArt @wickr

**Comment by carakey** [comment]
Batch replace list: https://docs.google.com/spreadsheets/d/1UBPQ2osT6a6L1yzQ-gsbcJA542NjWuq3IzqtgtNBj80/edit#gid=877534323

**Comment by wickr** [comment]
Batch update is complete.

**Comment by carakey** [comment]
QA looks good: URIs appear and resolve, numbers are correct.
