### ISSUE TITLE
Control Donor field: Lincoln County Historical Society Archive

### ISSUE THREAD

**Issue by carakey** [OregonDigital/oregondigital#1326]
Parent issue #1271 

Items in this collection were mainly donated by community members and in most cases credited using first initial and last name. We probably don't need to add 254 such names to ONS in order to supply a Donor URI. I recommend instead we move / append the name credit onto an uncontrolled text field instead (using a remediated value in some cases). I suggest using Provenance, with verbiage such as "Provided by: Smith, J."

There are 54 items in the collection with donors that do have URIs (mostly museums), so we can batch update the Donor field for those items. Question for these items is whether to also copy the name to an alternate field as above, for consistency within the collection. 

- [x] Clean up name values
- [x] Search for existing URIs
- [x] Determine alternative text field and verbiage for messy data 
- [x] Batch edit 1: Replace Donor strings with URIs (54 items) / remove uncontrolled Donor strings (1,331 items)
- [x] Batch edit 2: Insert remediated name value in Provenance field (1,385 items)

**Comment by carakey** [comment]
1,385 item records. 

Batch 1 list: Donor replace / remove https://docs.google.com/spreadsheets/d/1UBPQ2osT6a6L1yzQ-gsbcJA542NjWuq3IzqtgtNBj80/edit?pli=1#gid=688644012

- first 54 records have new URIs
- all remaining rows should have Donor triple removed

Batch 2 list: Add Provenance: https://docs.google.com/spreadsheets/d/1UBPQ2osT6a6L1yzQ-gsbcJA542NjWuq3IzqtgtNBj80/edit?pli=1#gid=1881202669

@wickr This is ready

**Comment by wickr** [comment]
All batch edits are complete. @carakey

**Comment by carakey** [comment]
Numbers look right, URIs & facets look good for those 54 with controllable names. Strings appearing in Provenance field as expected. It looks like there are 8 items in the collection that didn't have a donor and are therefore unchanged. QA pass.
