### ISSUE TITLE
users on vpn unable to access restricted items

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/oregondigital#1341]
UO users off campus but on the vpn were unable to access restricted items, i.e. items whose read_group includes admin, archivist, University-of-Oregon roles, but not public.
vpn ip range was checked and found to be within the range defined for the uo role.

**Comment by wickr** [comment]
It appears if a guest user accessed OD first without a VPN or on-campus, a guest session was created for them, saved on the server and tied to their browser with a cookie. Then when the VPN was turned on, the guest session still had their IP set as the original off-campus one, and there was no good way to update it short of clearing cookies.
