### ISSUE TITLE
Fairbanks preflight probs

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/oregondigital#1366]
- [x] Predicate not found: http://www.loc.gov/standards/mods/modsrdf/v1/note during crosswalk
- [x] Predicate not found: http://opaquenamespace.org/ns/accessionNumber during crosswalk
- [x] Predicate not found: http://www.loc.gov/premis/rdf/v1#hasOriginalName during crosswalk

**Comment by wickr** [comment]
First 2 predicates were updated. Third one was removed, the filename values in there are meaningless now. Preflight check passed.
