### ISSUE TITLE
More scrape requests

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#1368]
Request to get scrapes of the following values to determine remediation needs. These are used in Historic Sheet Music (UO), but unsure about other collections

modsrdf:locationCopyShelfLocator
modsrdf:locationCopySublocation
dct:extent
modsrdf:physicalExtent
ons:vra_measurements

**Comment by lsat12357** [comment]
scrapes on DigitalProjects

**Comment by sseymore** [comment]
this is done.
