### ISSUE TITLE
Campus_Maps (seed data) preflight check: missing identifier and predicate not found

### ISSUE THREAD

**Issue by luisgreg99** [OregonDigital/oregondigital#1373]
seed data list: [Campus_Maps_seed_data.txt](https://github.com/OregonDigital/oregondigital/files/5066070/Campus_Maps_seed_data.txt)

- [x] missing identifier:
```
oregondigital:fx71cs234
oregondigital:df70cf85x
```

- [x] predicates not found:
```
Working on oregondigital:df719p65p...
Predicate not found: http://purl.org/dc/terms/creator during crosswalk
```

For `http://purl.org/dc/terms/creator`, should we flip to `http://purl.org/dc/elements/1.1/creator`? (this predicate maps to `:creator` property as `::RDF::Vocab::DC11.creator` in OD2).

**Comment by KevinJonesMeta** [comment]
Identifier added based on filename (fx71cs234) or title (df70cf85x).

**Comment by wickr** [comment]
For this wrong creator predicate, it actually had the wrong URI in it for the person as well. The correct Creator predicate had the correct person URI. I removed the wrong predicate from this item, so this collection should be good to go now.
