### ISSUE TITLE
uo-veterans preflight probs

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/oregondigital#1377]
Predicate not found: http://opaquenamespace.org/ns/militaryServiceLocations during crosswalk
Predicate not found: http://purl.org/dc/terms/rightHolder during crosswalk

**Comment by lsat12357** [comment]
Working on oregondigital:df70j7520...
missing required field: rights_statement

Working on oregondigital:df70j760p...
missing required field: rights_statement
Working on oregondigital:df70j7695...
missing required field: rights_statement
Working on oregondigital:df70j777v...
missing required field: rights_statement

Working on oregondigital:df70j7406...
missing required field: rights_statement

Working on oregondigital:df70j7431...
missing required field: rights_statement

Working on oregondigital:df70j7139...
missing required field: rights_statement

Working on oregondigital:df70j7317...
missing required field: rights_statement

Working on oregondigital:df70j719z...
missing required field: rights_statement

Working on oregondigital:w9505112w...
missing required field: rights_statement

**Comment by sseymore** [comment]
rights statements are remediated

**Comment by lsat12357** [comment]
fixed and passing preflight
