### ISSUE TITLE
texts-data preflight probs

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/oregondigital#1381]
Predicate not found: http://purl.org/dc/terms/creator during crosswalk
Predicate not found: http://purl.org/dc/elements/1.1/type during crosswalk
Predicate not found: http://purl.org/dc/elements/1.1/format during crosswalk
report_20200810151506.txt:missing required field: rights_statement

**Comment by sseymore** [comment]
All texts and data assets should have rights statements now.

**Comment by lsat12357** [comment]
once creator, type and format predicates were fixed, some of them had strings instead of uris:

Working on oregondigital:df661w41j...
Invalid URI Ebitz, David found in crosswalk
Invalid URI audio/mp3 found in crosswalk
Working on oregondigital:df661w75c...
Invalid URI application/zip found in crosswalk
Invalid URI text/dlm found in crosswalk
Working on oregondigital:df661w743...
Invalid URI Sports & Fitness Industry Association found in crosswalk
Invalid URI application/zip found in crosswalk
Working on oregondigital:df661w36p...
Invalid URI application/vnd.ms-excel found in crosswalk
Working on oregondigital:df661w433...
Invalid URI Pareja, Roberto found in crosswalk
Working on oregondigital:df661w344...
Invalid URI Serrano Valls, Luis found in crosswalk
Invalid URI Llorente Chala, Juan Carlos found in crosswalk
Working on oregondigital:df661w35d...
Invalid URI Committee on Science, Engineering, and Public Policy (U.S.). Committee on Ensuring the Utility and Integrity of Research Data in a Digital Age. found in crosswalk
Working on oregondigital:fx71c6319...
Working on oregondigital:df661w46x...
Invalid URI Potter, Elisabeth Walton found in crosswalk
Working on oregondigital:df661w39h...
Invalid URI Kabacoff, Robert I. found in crosswalk
Working on oregondigital:df661w387...
Invalid URI Bluewater Nonprofit Solutions found in crosswalk

**Comment by sseymore** [comment]
@lsat12357 this should be remediated. let me know if I missed anything.

**Comment by lsat12357** [comment]
passing preflight
