### ISSUE TITLE
Oregon_Multicultural_Archives_Assorted (seed data) preflight check

### ISSUE THREAD

**Issue by luisgreg99** [OregonDigital/oregondigital#1384]
seed data list [Oregon_Multicultural_Archives_Assorted_seed_data.txt](https://github.com/OregonDigital/oregondigital/files/5066092/Oregon_Multicultural_Archives_Assorted_seed_data.txt)

- [x] missing required fields:
```
# occurs only on oregondigital:fx71bh49f
missing required field: rights_statement
missing required field: resource_type

# occurs on every work in seed data list
missing required field: identifier
```

**Comment by KevinJonesMeta** [comment]
rights_statement and resource-type added to oregondigital:fx71bh49f.

identifier added to seed data list.
