### ISSUE TITLE
Oregon_State_University_Sports_Media_Guides (seed_data) preflight check

### ISSUE THREAD

**Issue by luisgreg99** [OregonDigital/oregondigital#1387]
seed data list: [Oregon_State_University_Sports_Media_Guides_seed_data.txt](https://github.com/OregonDigital/oregondigital/files/5066118/Oregon_State_University_Sports_Media_Guides_seed_data.txt)

- [x] missing required field: identifier (occurs on every work in this seed data collection)

**Comment by KevinJonesMeta** [comment]
Identifiers have been added to the seed data list.
