### ISSUE TITLE
Seed data for Sports Media Guides license blowing up

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/oregondigital#1391]
These assets use license http://creativecommons.org/licenses/by-nc-nd/4.0/ 
Seem to ingest fine, but the assets won't display, instead there is the message "Ack! Looks like Oregon Digital is temporarily broken"
Changing to https fixes this.

**Comment by wickr** [comment]
Yeah OD2 is set to use the 'https' version: https://github.com/OregonDigital/OD2/blob/master/config/authorities/licenses.yml#L39

Are there other cases where we're changing this in the migrator for CC v4 licenses?
