### ISSUE TITLE
minorities-lgbtq-barometer preflight prob

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/oregondigital#1405]
a good number of these use http://opaquenamespace.org/ns/rightsHolder (technically correct, but OD uses rights/rightsHolder or dct rightsHolder.

**Comment by wickr** [comment]
rightsHolder was updated now per #1385 so this should be resolved

**Comment by wickr** [comment]
Confirmed with a preflight report that there are no remaining issues.
