### ISSUE TITLE
new colls

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/oregondigital#1426]
NHPRC grant:
 
Name: Kurt Werth papers, 1919-1983
URI: kurt-werth-coll100
Blurb: Kurt Werth (1896-1983) was a German-born illustrator and author of American children's literature. The collection consists of original children's book illustrations and manuscripts, other artwork and manuscripts, personal papers, artifacts, personal and professional correspondence, and papers of his wife, Margaret Werth.
Will select images after I ingest
 
Name: Edwin Tunis papers, 1920s-1979
URI: edwin-tunis-ax776
Blurb: The Edwin Tunis papers include manuscripts and illustrations for children's books, as well as correspondence, articles, reviews, publicity, and personal papers.
Will select images after I ingest
 
Name: Kurt Wiese papers, circa 1911-1974
URI: kurt-wiese-ax445
Blurb: Kurt Wiese (1887-1974) was a German-born illustrator and author of American children's literature. The collection is primarily comprised of children's book production material including original drawings, sketches, proofs, manuscripts, and correspondence. Other artwork and personal papers are also included.
Will select images after I ingest
 
 
LSTA grant:
 
Name: Chester E. Corry papers, 1947-1989
URI: chester-e-corry-coll522
Blurb:
Chester E. Corry (1906-1989) was an Oregon landscape architect who worked predominantly in southern Oregon. Corry is best known for his work at Ashland’s Lithia Park. Born in Columbia, North Dakota, in 1906, Corry spent most of his childhood in Glendora, California. Corry received a professional degree in landscape architecture from Oregon Agricultural College (now Oregon State University) in 1930. During the early 1930s, Corry worked for Portland’s Lambert Gardens and the National Park Service at Mt. Lassen. This experience enabled Corry to become Ashland’s assistant park superintendent in 1937, a position he held until his retirement in 1969.
 
Corry invested his time and skill in many residential and public landscape architecture projects. Most projects were conducted in Ashland and Medford, Oregon, however several other areas, including 17 cities and counties in Oregon, five cities in California, and one city in Massachusetts, are reflected in the collection. The Chester E. Corry papers contain landscape architecture plans for public areas and residential clients, some accompanying documentation for landscape projects, clippings, correspondence, and an autobiography. A full inventory is available. https://scua.uoregon.edu/repositories/2/resources/8793
 
Will select images after I ingest
 
 
Name: Barbara Fealy Landscape Architect records, 1966-1993
URI: barbara-fealy-coll262
Blurb:
Barbara Bertha Vorse Fealy (1903-2000) was born in Salt Lake City, Utah to Albert Justin and Bettie Vorse. Albert Vorse owned one of Utah’s largest wholesale nurseries, and Barbara grew up assisting with his operation. In 1921, Fealy attended the University of Illinois to study landscape architecture. Fealy ultimately started her own firm in 1929 in Salt Lake City, Utah. In 1947, she moved her firm to Beaverton, Oregon and spent the remainder of her life in the Pacific Northwest producing landscape architectural designs for both private, residential clients and commercial projects.
 
The Barbara Fealy landscape architectural records include her firm’s architectural drawings, client files, photographs, and notes. Of note include her designs for Salishan Lodge in Gleneden Beach, Oregon for which she received an Honor Award from the American Society of Landscape Architects (ASLA) in 1988. Drawings also include designs for Timberline Lodge (Government Camp, Oregon), the Leach Botanical Garden (Portland, Oregon), and Yurigawa Park (Sapporo, Japan), among many others. A full inventory is available. https://scua.uoregon.edu/repositories/2/resources/2178
 
Will select images after I ingest
 
 
Name: Lord & Schryver landscape architectural records, 1929-1970
URI: lord-schryver-coll098
Blurb:
Elizabeth Lord (1887-1976) and Edith Schryver (1901-1984) founded the Lord & Schryver landscape architecture firm in 1929 in Salem, Oregon. Working from Lord’s family home in Salem, Oregon, the pair established themselves as the first firm of professional women landscape architects on the West Coast and designed gardens for locations throughout Oregon and Washington. Their practice primarily focused on garden design for private residences however, they also designed the grounds for Reed College (Portland, Oregon) and the College of Puget Sound (now University of Puget Sound, Tacoma, Washington), several parks and schools in Salem, Oregon, two churches, and a variety of city- and state-owned public buildings.
 
The Lord & Schryver landscape architectural records contain landscaping plans and drawings, correspondence, office files, subject files, photographs, brief biographical sketches, and notes relating to Lord’s and Schryver’s work as landscape architects. Additionally, the collection includes Edith Schryver’s teaching files from Oregon State College (now Oregon State University), as well as radio scripts for Lord’s and Schryver’s “Home Garden Hour” which detail a day in the life of a landscape architect. A full inventory is available. https://scua.uoregon.edu/repositories/2/resources/2021
 
Will select images after I ingest

**Comment by lsat12357** [comment]
cols are created, not reviewed.

**Comment by sseymore** [comment]
Images for landing pages:

lord-schryver-coll098:
Coll098_b000_f048_002a: https://oregondigital.org/reviewer/oregondigital:sf268644d
Coll098_b003_f001_020a: https://oregondigital.org/reviewer/oregondigital:sf268685n
Coll098_b003_f001_015a: https://oregondigital.org/reviewer/oregondigital:sf268655x

barbara-fealy-coll262:
Coll262_b000_f067_016: https://oregondigital.org/reviewer/oregondigital:2f75r8145 
Coll262_b000_f067_018: https://oregondigital.org/reviewer/oregondigital:2f75r8366
Coll262_b000_f084_005: https://oregondigital.org/reviewer/oregondigital:2f75r8081

chester-e-corry-coll522:
Coll522_b013_f000_002: https://oregondigital.org/reviewer/oregondigital:qb98mg462
Coll522_b014_f000_004: https://oregondigital.org/reviewer/oregondigital:qb98mg53g
Coll522_b017_f000_001: https://oregondigital.org/reviewer/oregondigital:qb98mg62f

**Comment by sseymore** [comment]
Images for landing pages:

**I will add links once ingested**

kurt-wiese-ax445:
AX445_b006_f001_001a
AX445_b001_f008_004a
AX445_b020_f010_004
AX445_b021_f006_002a

edwin-tunis-ax776:
AX776_b010_f007_008a
AX776_b010_f013_013a
AX776_b010_f007_009a
AX776_b010_f010_001a

kurt-werth-coll100:
Coll100_b005_f003_016
Coll100_b005_f003_013
Coll100_b008_f004_006a
Coll100_b001_f045_019
Coll100_b011_f002_005a

**Comment by lsat12357** [comment]
lord-schryver, b fealy, chester reviewed and set pages completed 8-20.

**Comment by sseymore** [comment]
@lsat12357 A request for after the WC/sprint that can be done in September. One of these collections titles changed. Can you update the collection landing page title and the set URI label for barbara-fealy-coll262?

Change from "Barbara Fealy Landscape Architect records, 1966-1993" to "Barbara Fealy landscape architectural records, 1966-1993"

**Comment by lsat12357** [comment]
name changed

**Comment by sseymore** [comment]
@lsat12357 the curator realized they have to credit the funding organization in the collection landing pages. Can you add this following blurb to these collections:

https://oregondigital.org/sets/edwin-tunis-ax776
https://oregondigital.org/sets/kurt-werth-coll100
https://oregondigital.org/sets/kurt-wiese-ax445

Funding for publishing this digital collection was provided through a grant awarded by the National Historical Publications and Records Commission (NHPRC), a division of the National Archives and Records Administration (NARA).
