### ISSUE TITLE
Scrape request for artists-books

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#1438]
We would like to look at the data in MODS note in this collection so see about remediation needs, so requesting a scrape of the entire collection.

**Comment by lsat12357** [comment]
sent via email

**Comment by sseymore** [comment]
Adding this here because I missed over email
[artists-books-scrape.txt](https://github.com/OregonDigital/oregondigital/files/8027850/artists-books-scrape.txt)

**Comment by jsimic** [comment]
@sseymore There seems to be a mismatch between field contents and field name. I believe replacesUrl contains the notes data. There is some provenance information that should not be made public.
