### ISSUE TITLE
[Remediation] osu-baseball preflight check

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#1451]
collection_id: osu-baseball

### Known Issues
- [x] Invalid dates (110) - Ryan
- [x] Name strings as URIs (35) - Kevin

Many URIs are likely ready or created, just need to be matched and replaced.
Original analysis of name URIs needed: https://github.com/osulp/metadata/blob/main/oregondigital/baseball/photographers.md 

### Related Tickets
https://github.com/OregonDigital/oregondigital/issues/1371
https://github.com/osulp/metadata/issues/21

**Comment by KevinJonesMeta** [comment]
Name strings changed to URIs.
