### ISSUE TITLE
[Remediation] gbwarnerpapers preflight check

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#1452]
collection_id: gbwarnerpapers

### Known Issues
- [x] Bad dates (Sarah)
- [x] Bad preds (Linda)

**Comment by lsat12357** [comment]
I'm not sure what predicates should replace these
http://www.w3.org/2000/01/rdf-schema#comment
http://www.w3.org/2000/01/rdf-schema#label

**Comment by sseymore** [comment]
This data is in other fields. Can delete these bad statements.

**Comment by sseymore** [comment]
ready for preflight rerun

**Comment by lsat12357** [comment]
passing preflight
