### ISSUE TITLE
[Remediation] mountaingrove preflight check

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1454]
collection_id: moutaingrove

### Known Issues
- [x]  Bad predicates (Linda)

### Related Tickets

#1311

**Comment by lsat12357** [comment]
preflight clean

**Comment by jsimic** [comment]
For the ones that are doubled with Ruth and unknown, please delete the unknown entry. There are a handful that are not doubled and are only unknown.

**Comment by lsat12357** [comment]
known unknowns removed
