### ISSUE TITLE
[Remediation] western-waters preflight check

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1459]
collection_id: western-waters

### Known Issues
- [x] Missing children (Linda)
- [x] Bad predicates (Linda)
- [x] Missing fields (Linda/Julia)
- [x] Bad dates (Julia)

### Related Tickets

#1311

**Comment by jsimic** [comment]
@lsat12357 Can I get a scrape of all the metadata labels for the items with missing Identifiers? I'm going to have to try to match the data to the filenames.
[wwdl_missingIdentifiers.txt](https://github.com/OregonDigital/oregondigital/files/7705582/wwdl_missingIdentifiers.txt)

**Comment by lsat12357** [comment]
[western-waters_missing-scrape.txt](https://github.com/OregonDigital/oregondigital/files/7722838/western-waters_missing-scrape.txt)

**Comment by jsimic** [comment]
@lsat12357 Here are the Identifiers that were missin
[western-waters_missingIdentifiers.xlsx](https://github.com/OregonDigital/oregondigital/files/7810800/western-waters_missingIdentifiers.xlsx)
g

**Comment by lsat12357** [comment]
[wwdl_uris.txt](https://github.com/OregonDigital/oregondigital/files/7942702/wwdl_uris.txt)

**Comment by jsimic** [comment]
re: oregondigital:df673g75c  Not that I can see. Since it's part of a page sequence, it should be live.

Completed replacing Contributor URIs.

**Comment by lsat12357** [comment]
ok here's another destroyed item...the previous deleted item was known to be deleted by the oracle (jeremy's pid list generator)
but this one oregondigital:df673f54d was among the living when I pulled the list. Is it supposed to be deleted? (I really hope so) how are these things tracked anyway?

**Comment by jsimic** [comment]
Can you tell when it was deleted? I can see no reason for it to have been.

**Comment by lsat12357** [comment]
wow. you actually can find out, in workflowMetadata. It was deleted on 2021-12-13

**Comment by jsimic** [comment]
oregondigital:df673f54d appears to be complete and not a dupe, so should be restored to the land of the living and migrated.

**Comment by lsat12357** [comment]
fixed 2 remaining preflight errors
