### ISSUE TITLE
[Remediation] columbia-gorge preflight check

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#1463]
collection_id: columbia-gorge

### Known Issues
- [x] Invalid dates (2) - Kevin
- [x] Strings instead of URIs, photographers and locations mostly (558)
  - [x] Make spreadsheet with unique values to URIs - Kevin
  - [x] Replace string values with URIs - Ryan

I think the best approach to these strings is to do a spreadsheet of the unique values, find or make URIs, then I'll scan all columbia-gorge items and replace values that match.

**Comment by KevinJonesMeta** [comment]
Spreadsheet of values and uris has been created. I need to eliminate duplicate values.

**Comment by KevinJonesMeta** [comment]
Deduped spreadsheet finished. https://docs.google.com/spreadsheets/d/1mNPMedZY2pJJH9hrWpwPJJm45I7HozC9pZkycePyYeI/edit#gid=0

**Comment by wickr** [comment]
Replacement script using spreadsheet mapping recorded 526 changes. Will run another preflight check.

**Comment by wickr** [comment]
6 were left, they didn't match the replacements due to spacing mismatches in the labels. Since the URIs were ready I corrected them manually.
