### ISSUE TITLE
[Remediation] textile-and-apparel preflight check

### ISSUE THREAD

**Issue by carakey** [OregonDigital/oregondigital#1464]
collection_id: textile-and-apparel

### Known Issues

- [x] resource_type missing (587) - Ryan _(should all be images)_
- [x] EDTF date ranges needing `-` swapped for `/` (2398) - Ryan 
- [x] EDTF date with trailing space + swap as above (1) - Cara
- [x] Predicate not found (1) - Ryan
- [x] Invalid URI (1) - Cara

### Related Tickets

#1311, #1380, #1240

**Comment by carakey** [comment]
- @wickr 'Predicate not found' is missing an octothorpe: oregondigital:df73dx071 has `http://www.loc.gov/standards/mods/modsrdf/v1/locationCopyShelfLocator` but should have `http://www.loc.gov/standards/mods/modsrdf/v1/#locationCopyShelfLocator`

**Comment by carakey** [comment]
- oregondigital:df711j81v; Removed trailing space in Date value and swapped `-` for `/`
- oregondigital:df71vt615; Moved "Mexico or Guatemala" from Location to end of Description and added URIs for each.

**Comment by wickr** [comment]
Predicate fixed. Date ranges updated. Resource Type updated for all that needed it.
