### ISSUE TITLE
[Remediation] african-ephemera preflight check

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#1466]
collection_id: african-ephemera

### Known Issues
- [ ] Bad preds (Linda)
- [ ] Bad URIs (Sarah)

**Comment by sseymore** [comment]
Can't edit oregondigital:02870v844: You do not have sufficient access privileges to read this document, which has been marked private.

**Comment by lsat12357** [comment]
OMG
oregondigital:02870v844 has more breaking statements than good

**Comment by lsat12357** [comment]
[african-ephemera_bad_asset.txt](https://github.com/OregonDigital/oregondigital/files/7927447/african-ephemera_bad_asset.txt)

**Comment by lsat12357** [comment]
creator/contributor predicate fixes need to be checked

**Comment by sseymore** [comment]
[african-ephemera_bad_asset.txt](https://github.com/OregonDigital/oregondigital/files/8969057/african-ephemera_bad_asset.txt)
@lsat12357 I hope I got it all fixed here.

**Comment by sseymore** [comment]
@lsat12357 Fixed creator and contributor. Measurements and Language preds just need to be swapped. I think that's it. Ready for rerun. Let me know if I missed anything.

**Comment by lsat12357** [comment]
ok the bad asset is bad no longer!
but I did find a few more things to fix. Preds are easily dealt with, can you fix these uris though
oregondigital:02870v844 Invalid URI Malawi Congress Party found in crosswalk
oregondigital:9593tv123 Invalid URI Gender Equality Support Project; Pan African Civic Educators Network; Canadian International Development Agency found in crosswalk

**Comment by sseymore** [comment]
oops, sorry I missed these. done! This data is in other parts of the record so deleted.

**Comment by sseymore** [comment]
@lsat12357 done!

**Comment by lsat12357** [comment]
preflight clean
