### ISSUE TITLE
[Remediation] album-collection preflight check

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#1467]
collection_id: album-collection

### Known Issues
- [x] Bad preds (Linda)
- [x] Bad dates (Sarah)

**Comment by lsat12357** [comment]
preflight clean

**Comment by lsat12357** [comment]
Predicate fix was for creator. Can you confirm that the creator is correct? eg this one already had a photographer.
https://oregondigital.org/catalog/oregondigital:df66xd73d

**Comment by sseymore** [comment]
I can't confirm this, actually. A legacy collection. Keep both.
