### ISSUE TITLE
[Remediation] dissociation preflight check

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#1471]
collection_id: dissociation

### Known Issues
- [x] Bad dates (Sarah)
- [x] Bad preds (Linda)

**Comment by lsat12357** [comment]
this is the only statement with a bad predicate, what would you like done?
<http://oregondigital.org/resource/oregondigital:df670g65m> <http://purl.org/dc/terms/contributor> "Tucker, James I. (trans.)"

**Comment by sseymore** [comment]
You can delete. I moved data to translator.
