### ISSUE TITLE
[Remediation] frazier-boutelle preflight check

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#1474]
collection_id: frazier-boutelle

### Known Issues
- [x] Bad dates (Sarah)
- [ ] Bad preds (Linda)

**Comment by lsat12357** [comment]
I just looked at the predicates; its all earliestDate/latestDate. The sample I checked (oregondigital:fx719p06h) shows values that are different from the viewDate. How to handle? discard? assign the dates to date or replace viewDate?

**Comment by sseymore** [comment]
Can I get a scrape of the assets to confirm?

**Comment by lsat12357** [comment]
can you get by without one? there are 6

**Comment by sseymore** [comment]
oregondigital:fx719r806	Predicate not found: http://www.loc.gov/standards/vracore/vocab/idCurrentRepository -- That was an error and moved that data to local collection name. Delete pred.

The other 6 images can have earliest/latest preds deleted.

**Comment by lsat12357** [comment]
preflight clean
