### ISSUE TITLE
[Remediation] grayson-mathews preflight check

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#1475]
collection_id: grayson-mathews

### Known Issues
- [ ] Bad preds (Linda)

**Comment by lsat12357** [comment]
looks like wrong version of creator was used; however these assets appear to be using photographer? delete the bad creator statements?

**Comment by sseymore** [comment]
If they are the same value/URI as what's used for photographer, then yes, delete. If they are different, can you send me an export of what's there? thank you!

**Comment by lsat12357** [comment]
there are 53 assets
they all have photographer set to http://opaquenamespace.org/ns/creator/MathewsGraysonLayne
which has been deprecated, acc to the opaquenamespace page
the bad creator statements use http://opaquenamespace.org/ns/creator/MathewsGraysonLane

**Comment by sseymore** [comment]
Ok, can you replace with https://opaquenamespace.org/ns/creator/MathewsGraysonLane? Can delete in creator and leave in pht. Thanks!

**Comment by lsat12357** [comment]
preflight clean
