### ISSUE TITLE
[Remediation] james-cloutier preflight check

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1476]
collection_id: james-cloutier

### Known Issues
- [x] Bad Predicates (Linda)

### Related Tickets
#1311

**Comment by lsat12357** [comment]
these all have photographer https://id.loc.gov/authorities/names/n90604094 (i.e. James Cloutier)
the bad predicates are all creator; the one I looked at uses http://opaquenamespace.org/ns/creator/CloutierJames

**Comment by jsimic** [comment]
Use photographer, dump the creators

**Comment by lsat12357** [comment]
preflight clean
