### ISSUE TITLE
[Remediation] jasr preflight check

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1477]
collection_id: jasr

### Known Issues
- [x] Bad Dates (Julia)
- [x] Bad Predicates (Linda)

**Comment by lsat12357** [comment]
preflight clean

**Comment by lsat12357** [comment]
can you confirm creator predicate fix result?
for example: https://oregondigital.org/catalog/oregondigital:df665x651

**Comment by jsimic** [comment]
Confirmed.
