### ISSUE TITLE
[Remediation] john-bauguess preflight check

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1478]
collection_id: john-bauguess

### Known Issues
- [x] Bad Predicates (Linda)

### Related Tickets
#1311

**Comment by lsat12357** [comment]
the bad predicate is dc:creator, the object used is the same as what is in photographer, i.e. http://opaquenamespace.org/ns/creator/BauguessJohn

**Comment by jsimic** [comment]
Use photographer and dump the creator

**Comment by lsat12357** [comment]
preflight clean
