### ISSUE TITLE
[Remediation] mayo-methot-bogart preflight check

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1480]
collection_id: mayo-methot-bogart

### Known Issues
- [x] Bad Predicates (Linda)

### Related Tickets
#1311

**Comment by lsat12357** [comment]
there are a bunch of technical statements that should be straightforward to fix/add.
But then there's dc:creator
the majority of the bad creators use opaquenamespace.org/ns/creator/unknownphotographer
while all the assets already have photographer: opaquenamespace.org/ns/creator/unknown
however, it appears there are a handful of exceptions. attaching the report for this.

**Comment by lsat12357** [comment]
oregondigital:df66tr640
<http://oregondigital.org/resource/oregondigital:df66tr640> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr640
<http://oregondigital.org/resource/oregondigital:df66tr640> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr640
<http://oregondigital.org/resource/oregondigital:df66tr640> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr658
<http://oregondigital.org/resource/oregondigital:df66tr658> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr658
<http://oregondigital.org/resource/oregondigital:df66tr658> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr658
<http://oregondigital.org/resource/oregondigital:df66tr658> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr66j
<http://oregondigital.org/resource/oregondigital:df66tr66j> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr66j
<http://oregondigital.org/resource/oregondigital:df66tr66j> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr66j
<http://oregondigital.org/resource/oregondigital:df66tr66j> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr67t
<http://oregondigital.org/resource/oregondigital:df66tr67t> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr67t
<http://oregondigital.org/resource/oregondigital:df66tr67t> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr67t
<http://oregondigital.org/resource/oregondigital:df66tr67t> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr683
<http://oregondigital.org/resource/oregondigital:df66tr683> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr683
<http://oregondigital.org/resource/oregondigital:df66tr683> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr683
<http://oregondigital.org/resource/oregondigital:df66tr683> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr69c
<http://oregondigital.org/resource/oregondigital:df66tr69c> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr69c
<http://oregondigital.org/resource/oregondigital:df66tr69c> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr69c
<http://oregondigital.org/resource/oregondigital:df66tr69c> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr704
<http://oregondigital.org/resource/oregondigital:df66tr704> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr704
<http://oregondigital.org/resource/oregondigital:df66tr704> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr704
<http://oregondigital.org/resource/oregondigital:df66tr704> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr71d
<http://oregondigital.org/resource/oregondigital:df66tr71d> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr71d
<http://oregondigital.org/resource/oregondigital:df66tr71d> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr71d
<http://oregondigital.org/resource/oregondigital:df66tr71d> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr72p
<http://oregondigital.org/resource/oregondigital:df66tr72p> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr72p
<http://oregondigital.org/resource/oregondigital:df66tr72p> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr72p
<http://oregondigital.org/resource/oregondigital:df66tr72p> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr73z
<http://oregondigital.org/resource/oregondigital:df66tr73z> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr73z
<http://oregondigital.org/resource/oregondigital:df66tr73z> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr73z
<http://oregondigital.org/resource/oregondigital:df66tr73z> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr747
<http://oregondigital.org/resource/oregondigital:df66tr747> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr747
<http://oregondigital.org/resource/oregondigital:df66tr747> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr747
<http://oregondigital.org/resource/oregondigital:df66tr747> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr75h
<http://oregondigital.org/resource/oregondigital:df66tr75h> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr75h
<http://oregondigital.org/resource/oregondigital:df66tr75h> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr75h
<http://oregondigital.org/resource/oregondigital:df66tr75h> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr76s
<http://oregondigital.org/resource/oregondigital:df66tr76s> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/Davies> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr76s
<http://oregondigital.org/resource/oregondigital:df66tr76s> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/Davies> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr76s
<http://oregondigital.org/resource/oregondigital:df66tr76s> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/Davies> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr772
<http://oregondigital.org/resource/oregondigital:df66tr772> <http://purl.org/dc/terms/creator> <http://id.loc.gov/authorities/names/nr99038062> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr772
<http://oregondigital.org/resource/oregondigital:df66tr772> <http://purl.org/dc/terms/creator> <http://id.loc.gov/authorities/names/nr99038062> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr772
<http://oregondigital.org/resource/oregondigital:df66tr772> <http://purl.org/dc/terms/creator> <http://id.loc.gov/authorities/names/nr99038062> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr78b
<http://oregondigital.org/resource/oregondigital:df66tr78b> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr78b
<http://oregondigital.org/resource/oregondigital:df66tr78b> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr78b
<http://oregondigital.org/resource/oregondigital:df66tr78b> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr79m
<http://oregondigital.org/resource/oregondigital:df66tr79m> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr79m
<http://oregondigital.org/resource/oregondigital:df66tr79m> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr79m
<http://oregondigital.org/resource/oregondigital:df66tr79m> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr80c
<http://oregondigital.org/resource/oregondigital:df66tr80c> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr80c
<http://oregondigital.org/resource/oregondigital:df66tr80c> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr80c
<http://oregondigital.org/resource/oregondigital:df66tr80c> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr81n
<http://oregondigital.org/resource/oregondigital:df66tr81n> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr81n
<http://oregondigital.org/resource/oregondigital:df66tr81n> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr81n
<http://oregondigital.org/resource/oregondigital:df66tr81n> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr82x
<http://oregondigital.org/resource/oregondigital:df66tr82x> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr82x
<http://oregondigital.org/resource/oregondigital:df66tr82x> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr82x
<http://oregondigital.org/resource/oregondigital:df66tr82x> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr836
<http://oregondigital.org/resource/oregondigital:df66tr836> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr836
<http://oregondigital.org/resource/oregondigital:df66tr836> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown
oregondigital:df66tr836
<http://oregondigital.org/resource/oregondigital:df66tr836> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknownphotographer> .
photographer: http://opaquenamespace.org/ns/creator/unknown

**Comment by jsimic** [comment]
Where unknownphotographer and unknown are both used, use http://opaquenamespace.org/ns/creator/unknown. For the ones that are different from unknownphotographer, use the creator URIs as creators (they appear to all be the studios the photographers are associated with)

**Comment by lsat12357** [comment]
preflight clean
