### ISSUE TITLE
[Remediation] roy-c-andrews preflight check

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1481]
collection_id: roy-c-andrews

### Known Issues
- [x] Bad Predicates (Linda)

### Related Tickets
#1311

**Comment by lsat12357** [comment]
the bad predicates are all dc:creator
they seem to all be the same as what is in the photographer field, i.e. 
http://opaquenamespace.org/ns/creator/AndrewsRoyC
but there is one exception:
oregondigital:df66zj546
the bad creator is http://id.loc.gov/authorities/subjects/sh85105182

**Comment by jsimic** [comment]
Use photographer where they are the same. The bad creator for oregondigital:df66zj546 can be deleted.

**Comment by lsat12357** [comment]
preflight clean
