### ISSUE TITLE
[Remediation] rv-mills preflight check

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1482]
collection_id: rv-mills

### Known Issues
- [x] Bad Predicates (Linda)

### Related Tickets
#1311

**Comment by lsat12357** [comment]
bad predicate is dc:creator
assets already have photographer, however unlike some of the other colls that have this prob, it doesn't look like they are always the same value.

**Comment by lsat12357** [comment]
oregondigital:df66xc87j
<http://oregondigital.org/resource/oregondigital:df66xc87j> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/WhittakerWC> .
photographer: http://id.loc.gov/authorities/names/no99021042
oregondigital:df66xc96h
<http://oregondigital.org/resource/oregondigital:df66xc96h> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/SavageCharlesD> .
photographer: http://id.loc.gov/authorities/names/no99021042
oregondigital:df66xc982
<http://oregondigital.org/resource/oregondigital:df66xc982> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknown> .
photographer: http://id.loc.gov/authorities/names/no99021042
oregondigital:df66xd09c
<http://oregondigital.org/resource/oregondigital:df66xd09c> <http://purl.org/dc/terms/creator> <http://id.loc.gov/authorities/names/no2004054787> .
photographer: http://id.loc.gov/authorities/names/no99021042
oregondigital:df66xd11d
<http://oregondigital.org/resource/oregondigital:df66xd11d> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/GWC> .
photographer: http://id.loc.gov/authorities/names/no99021042
oregondigital:df66xd172
<http://oregondigital.org/resource/oregondigital:df66xd172> <http://purl.org/dc/terms/creator> <http://id.loc.gov/authorities/names/no2004054787> .
photographer: http://id.loc.gov/authorities/names/no99021042
oregondigital:df66xd19m
<http://oregondigital.org/resource/oregondigital:df66xd19m> <http://purl.org/dc/terms/creator> <http://id.loc.gov/authorities/names/no2004054787> .
photographer: http://id.loc.gov/authorities/names/no99021042
oregondigital:df66xd279
<http://oregondigital.org/resource/oregondigital:df66xd279> <http://purl.org/dc/terms/creator> <http://id.loc.gov/authorities/names/n81145817> .
photographer: http://id.loc.gov/authorities/names/no99021042
oregondigital:df66xd31w
<http://oregondigital.org/resource/oregondigital:df66xd31w> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/unknown> .
photographer: http://id.loc.gov/authorities/names/no99021042
oregondigital:df66xd34q
<http://oregondigital.org/resource/oregondigital:df66xd34q> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/WhittakerWC> .
photographer: http://id.loc.gov/authorities/names/no99021042

**Comment by jsimic** [comment]
Creators and photographers can be different in this collection. Keep both.

**Comment by lsat12357** [comment]
preflight clean
