### ISSUE TITLE
[Remediation] siuslaw preflight check

### ISSUE THREAD

**Issue by carakey** [OregonDigital/oregondigital#1484]
collection_id: siuslaw

### Known Issues
- [x] Bad dates - Cara/Ryan
- [x] Bad dates part 2 (302) - Cara/Ryan
- [x] Bad preds - Ryan
- [x] Bad URIs (289) - Cara
- [x] Missing identifiers (43) - Cara
- [x] Visibility - Ryan

**Comment by carakey** [comment]
@wickr I have replacement dates in the first tab of the [spreadsheet](https://docs.google.com/spreadsheets/d/1DI-IpjPFHqr0Z8QtWhpKCwK-TOkPTIHFHbqmCnXi8cQ/edit#gid=0) and replacement predicates in the second tab.

**Comment by wickr** [comment]
Dates and predicates are all processed. For visibility, none of the items with read_group values were set correctly to restrict to OSU only, so those are now updated.

Another preflight check run shows all good except for 302 date errors still, so I'll look into that more to see what happened.

**Comment by wickr** [comment]
The 302 remaining dates are all fixed now as well.
A subsequent preflight check confirms all issues are resolved.
