### ISSUE TITLE
[Remediation] oregon-explorer preflight checks

### ISSUE THREAD

**Issue by KevinJonesMeta** [OregonDigital/oregondigital#1486]
collection_id: oregon-explorer

### Known Issues
- ~bad compound objects - children missing (4) - Ryan~
- [x] bad uris (15) - Kevin
- [x] missing identifiers (7) - Kevin
- [x] bad dates (34) - Kevin
- ~bad predicate (http://www.iana.org/assignments/relation/previous) - Ryan~

**Comment by KevinJonesMeta** [comment]
34 dates changed. 7 dates appeared to be EDTF format so I replaced the dashes.

**Comment by wickr** [comment]
The 5 items showing cpd and predicate errors have Gerald Williams as their Primary Set, so I removed them from the oregon-explorer pids list. The cpd children are in that set too.
A final preflight check came back clean. Though I suspect there's more items that should be in the gerald-williams list, there is a ton of overlap.
