### ISSUE TITLE
[Remediation] lichens-pnw preflight check

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#1488]
collection_id: lichens-pnw

### Known Issues
- [x] Bad dates (1) - Ryan
- [x] Missing identifiers (26) - Cara  (may be batch scriptable from filename, can see if that works)

**Comment by carakey** [comment]
Identifiers added from filenames. In 4 cases, "edited" and "cropped" notations as part of filenames were omitted from identifier.

oregondigital:df71wh118
oregondigital:df71wq485
oregondigital:df71ws14r
oregondigital:df71ww74t

**Comment by wickr** [comment]
Ran another preflight check on this and it came back with 0 issues.
