### ISSUE TITLE
[Remediation] streamsurvey preflight check

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#1489]
collection_id: streamsurvey

### Known Issues
- [x] Invalid dates (29) - Cara

Original report had lots of dates flagged, latest one only shows 29 with problems.

**Comment by carakey** [comment]
Bad dates corrected - replaced circa dates with -5/+5 year range

**Comment by wickr** [comment]
Ran another preflight check just to double check and it came back with 0 issues.
