### ISSUE TITLE
[Remediation] herbarium preflight check

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#1490]
collection_id: herbarium

### Known Issues
- [x] Missing resource_type (1875) - Ryan
- [x] Invalid collectedDates (70) - Cara
Not sure what happened with these, and if it's worth trying to fix them or just drop them, or move to Description. Or something else.

### Related Tickets
https://github.com/osulp/metadata/issues/157
https://github.com/OregonDigital/oregondigital/issues/1342

**Comment by carakey** [comment]
Invalid collectedDates: I was able to correct a number of dates based on image annotations and article texts. For those that couldn't be corrected, I deleted the collectedDate and moved the month to Description. I checked the [Herbarium database](https://oregonflora.org/index.php) for items but didn't find any additional information.

**Comment by wickr** [comment]
I exported the Herbarium collection again and confirmed that all items with no Resource Type were compound parent items. I set the Resource Type to Collection to fit with the few that already had it.
