### ISSUE TITLE
[Remediation] corvallis-flood preflight check

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#1492]
collection_id: corvallis-flood

### Known Issues
- Invalid predicates (118) - Ryan
  - [x] Predicate not found: http://opaquenamespace.org/ns/accessionNumber (59)
  - [ ] Predicate not found: http://purl.org/dc/terms/references (59) 

An early report had date problems listed, but they looked like ok EDTF. A new preflight check confirmed no date issues.

**Comment by wickr** [comment]
I'm not sure what to do with the values in the `dct:references` predicate. They seem to be just numbers, I can't find any matching reference in other item metadata or on the photos themselves. The original mapping from CONTENTdm export was: `map: dct:references` so possibly it's some other map or grid/id reference. The full archival collection isn't processed so there's little info in the finding aid.

**Comment by carakey** [comment]
@wickr Having looked at just a few of them, some kind of external map/grid makes sense. Is it possible it was meant as a relation to another item - the numbers being identifiers of other photos with views of the same area? A little hard to browse for, but for instance, the photo with identifier = 10([oregondigital:2v23vt41x](https://www.oregondigital.org/catalog/oregondigital:2v23vt41x)) has dct:references = "9", and the photo with identifier = "09" ([oregondigital:2j62s4901](https://www.oregondigital.org/catalog/oregondigital:2j62s4901)) definitely has some of the same landscape. It would take more work to confirm...

**Comment by wickr** [comment]
@carakey yeah maybe though that's a bit stronger connection than I was seeing. this collection is so small I can do a CSV export real quick, but it might take some physical item review

**Comment by wickr** [comment]
<google-sheets-html-origin><style type="text/css"></style>

pid | http://purl.org/dc/terms/description | http://purl.org/dc/terms/identifier | http://purl.org/dc/terms/references
-- | -- | -- | --
oregondigital:z603qx45b | Southwest Corvallis Pump Station; 11:00 AM; Water 23' | 4 | 3
oregondigital:7h149p866 | South Corvallis-Evans; 11:00 AM; Water 23' | 25 | 8
oregondigital:t148fh16n | North Corvallis Apartments; 11:00 AM; | 27 | 17
oregondigital:qn59q3974 | North Corvallis Apartments; 11:00 AM | 25 | 5
oregondigital:pg15bd93n | Avery Park; 11:20 AM; Water 23' | 23 | 2
oregondigital:6682x399n | Avery Park: Water 23' | 3 | 2
oregondigital:2v23vt41x | East Corvallis; 11:00 AM; Water 23' | 10 | 9
oregondigital:8049g508k | Corvallis East-Housing Dev.; 12:30 PM | 59 | 20
oregondigital:c821gj795 | South Corvallis; 11:20 AM; Water 23' | 26 | 6
oregondigital:dj52w4734 | Apartments North 5th | 67 | 17
oregondigital:1n79h431q | Corvallis Shops: 12:30 PM | 63 | 14
oregondigital:p2676v57r | East Corvallis at Peoria Rd.; 10:45 AM | 17 | 9
oregondigital:0z708w40c | South Corvallis; 11:00 AM; Water 23' | 5 | 4
oregondigital:jq085k01r | East Corvallis; 11:00 AM; Water 23' | 6 | 10
oregondigital:ws859f68w | Corvallis-East; 12:30 PM | 58 | 92
oregondigital:x633f1065 | South Corvallis: 12:30 PM | 73 | 21
oregondigital:p2676v52c | North Corvallis | 66 | 14
oregondigital:2j62s4901 | East Corvallis; 11:00 AM; Water 23' | 9 | 9
oregondigital:jd472w463 | South Corvallis; 11:20 AM; Water 23' | 24 | 11
oregondigital:2f75r804x | East Corvallis; 11:00 AM; water 23' | 21 | 9
oregondigital:4b29b599p | North Corvallis: 12:30 PM | 54 | 131
oregondigital:pv63g028j | Corvallis East; 12:30 PM | 56 | 9
oregondigital:9593tv18r | Corvallis Albany-Near farm home; 11:00 AM | 21 | 131
oregondigital:3484zg926 | North Corvallis-Sewage and shops; 11:00 AM | 26 | 14
oregondigital:0p096693w | East Corvallis-Van Buren bridge; 11:00 AM | 29 | 9
oregondigital:5t34sj573 | South Corvallis; 11:00 AM; Water 23' | 2 | 1
oregondigital:kh04dp699 | South Corvallis; 11:00 AM; Water 23' | 1 | 1
oregondigital:0v8380566 | Evans and South Corvallis; 12:30 PM | 76 | 22
oregondigital:x920fw89s | Corvallis Trailer; 12:30 PM | 78 | 4
oregondigital:gx41mh887 | East Corvallis and Peoria Road; 11:00 AM; Water 23' | 20 | 9
oregondigital:3484zg93g | South Corvallis-Evans; 11:00 AM; Water 23' | 27 | 22
oregondigital:vq27zn42r | Corvallis-Albany West side; 12:30 PM | 53 | 12
oregondigital:xd07gs69t | North Corvallis-shops; 12:30 PM | 62 | 14
oregondigital:kp78gg41b | South Corvallis; 12:30 PM | 77 | 8
oregondigital:6w924b87t | Corvallis East; 12:30 PM | 60 | 10
oregondigital:gb19f586c | Corvallis-Albany-West side-Farm Home; 11:00 AM | 20 | 131
oregondigital:x920fw90j | East Corvallis-Russells-OSU fis lab; 10:45 AM | 18 | 9
oregondigital:g158bh34t | 10:45-Corvallis-Lebanon-Near Moores Irrigation | 14 | 19
oregondigital:vq27zn431 | North Corvallis shops; 11:00 AM | 23 | 14
oregondigital:6d56zw66p | North Corvallis shops; 12:30 PM | 55 | 14
oregondigital:0k225b12c | East Corvallis; 12:30 PM | 51 | 10
oregondigital:3x816m62p | East Corvallis-at Peoria Rd.-Looking Southwest; 10:45 AM | 16 | 9
oregondigital:q237hr963 | Corvallis Albany and west side near farm home | 19 | 131
oregondigital:pv63g0278 | Southwest Corvallis; 11:00 AM; Water 23' | 22 | 3
oregondigital:1g05fb620 | North Corvallis; 11:00 AM | 22 | 16
oregondigital:sj139195q | South Corvallis; 12:30 PM | 70 | 8
oregondigital:8s45q877v | New bridge Corvallis | 68 | 9
oregondigital:tm70mv223 | North Corvallis Shops Sewage Plant; 11:00 AM; Water 23' | 8 | 5
oregondigital:q524jn81q | Highway Southwest Corvallis; 12:30 PM | 72 | 3
oregondigital:sj139194f | Corvallis-East; 10:45 AM | 15 | 10
oregondigital:nv9352884 | Corvallis East-West side (McFadden) | 61 | 18
oregondigital:r494vk213 | South Corvallis; 12:30 PM | 74 | 4
oregondigital:8910jt59d | Avery Park | 71 | 2
oregondigital:m039k493x | Corvallis-East-Van Buren-Bridge; 11:00 AM | 28 | 9
oregondigital:sq87bt65j | East Corvallis; 11:00 AM; Water 23' | 7 | 93
oregondigital:bv73c041b | South Corvallis; 11:00 AM; Water 23' | 30 | 7
oregondigital:6q182k142 | East Corvallis; 11:00 AM; Water 23' | 19 | 10
oregondigital:kp78gg36g | North Corvallis Shops; 12:30 PM | 65 | 14
oregondigital:3r074t95s | Corvallis East; 12:30 PM | 57 | 9

**Comment by carakey** [comment]
Well I'm not making much sense of it based on that earlier hypothesis, and not all the reference numbers match up to identifiers present in the collection. There are also some identifiers that are repeats, in totally different parts of town, which doesn't help.

Ordering the data by reference numbers, the descriptions would indicate that photos with the same number are of similar areas. E.g. 9's and 10's all have East Corvallis in the description, 2's have Avery Park, 131's (mostly) have Farm Home. I think it does suggest some kind of external geo reference, but unless we can track that down it doesn't have any meaning.

**Comment by wickr** [comment]
Opting to drop dct:references values via the migrator crosswalk override. We'll still have them in the OD1 records and in this ticket should we ever need them again.
