### ISSUE TITLE
[Remediation] artists-books preflight check

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#1497]
collection_id: artists-books

### Known Issues
- [x] Bad dates (Sarah)
- [x] Bad URIs (Sarah)

**Comment by sseymore** [comment]
@jsimic remediating modsnote #1438

**Comment by jsimic** [comment]
@lsat12357 Remediation complete except for oregondigital:df70bq534 which is uneditable: "We're sorry, but something went wrong." Note can be moved to Description.

**Comment by lsat12357** [comment]
that was weird, the only thing wrong with oregondigital:df70bq534 was the solr doc somehow got borked. Not positive, but possibly a label was not the expected value but instead a vocab error message, i.e. "Term not in controlled vocabularies:..."

**Comment by lsat12357** [comment]
passing preflight.

**Comment by lsat12357** [comment]
sticking this here, but this is no longer preflight, strictly speaking, we had assets fail bc of worktypes. Also, some of these may not actually be artists-books terms, but they are in use on od1, so will need to be fixed sooner or later. I see the last one already has a replacement in comment above.

assets failed for  using these worktypes
Decorative arts$http://id.loc.gov/authorities/subjects/sh85036316
Miniature books$http://id.loc.gov/authorities/subjects/sh85085643
Conservatories$http://id.loc.gov/authorities/subjects/sh85031278
Nesting dolls$http://id.loc.gov/authorities/subjects/sh90002381
Landscape architectural drawing$http://id.loc.gov/authorities/subjects/sh85074394
Tunnel books$http://id.loc.gov/authorities/subjects/sh2011003981

**Comment by lsat12357** [comment]
These are in form_of_work, which does not accept loc names
 http://id.loc.gov/authorities/names/n94057046 
   df70br23m, df70bs97m, df70bq887, df70bv37k
 http://id.loc.gov/authorities/names/n2002016868
     df70bt37c, df70bw49k

**Comment by jsimic** [comment]
Corrected. http://id.loc.gov/authorities/subjects/sh85125043 and http://vocab.getty.edu/aat/300129439
