### ISSUE TITLE
[Remediation] chinavine preflight check

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#1502]
collection_id: chinavine

### Known Issues
- [x] Bad cpd (Sarah and Linda)
- [x] Bad dates (Sarah)
- [x] Bad preds (Linda)
- [x] Bad status (Sarah and Linda)
- [x] Bad URIs (Sarah and Linda)
- [x] Missing items (Sarah and Linda)

**Comment by sseymore** [comment]
Bad URIs mass replace:
Qingha, Liu > http://opaquenamespace.org/ns/creator/LiuQingha
Xiwei, Nei > http://opaquenamespace.org/ns/creator/NieXiwei
Molds > http://vocab.getty.edu/aat/300024814
Furniture > http://vocab.getty.edu/aat/300037680
Woodworking > http://vocab.getty.edu/aat/300054083
Liang Xiucai > http://opaquenamespace.org/ns/creator/LiangXiucai (needs to be reviewed)
Paper figures > http://vocab.getty.edu/aat/300068579
Woodcut > http://vocab.getty.edu/aat/300041405

**Comment by sseymore** [comment]
@lsat12357 if we can't mass replace these URIs, I can get Leslie to assist.

**Comment by lsat12357** [comment]
should this one be reviewed?
https://oregondigital.org/catalog/oregondigital:df70zg453

**Comment by lsat12357** [comment]
I can do the bad uris; am thinking about unreviewing the cpds before I run uris and predicate fixes, and then re-reviewing them

**Comment by sseymore** [comment]
bad cpds:
oregondigital:df67v030x
child: oregondigital:df67tz59h undelete? This looks like a thumbnail of a moving image file that got uploaded. Delete. Can you fix parent?

these next 3 cpds are a mystery: none of their children exist in Fedora, but they all have pids. and the parents shouldn't have been able to be created unless the children existed. If you still have the bags, perhaps we can fix.
oregondigital:df70z381p - should have 162 photos. I found metadata sheet. Will look for images to reingest.
oregondigital:df70z382z - should have 76 photos. I found metadata sheet. Will look for images to reingest.
oregondigital:df70z3837 - should have 14 photos. I found metadata sheet. Will look for images to reingest.

**Comment by sseymore** [comment]
Working on this now. I am seeing duplicate uploads, so I'm deleting those assets. Do not migrate.

**Comment by sseymore** [comment]
pids to attach to oregondigital:df70z381p [oregondigital-df70z381p.txt](https://github.com/OregonDigital/oregondigital/files/9340594/oregondigital-df70z381p.txt)

**Comment by sseymore** [comment]
pids to attach to oregondigital:df70z382z
[oregondigital-df70z382z.txt](https://github.com/OregonDigital/oregondigital/files/9352820/oregondigital-df70z382z.txt)

**Comment by sseymore** [comment]
pids to attach to oregondigital:df70z3837
[oregondigital-df70z3837.txt](https://github.com/OregonDigital/oregondigital/files/9352858/oregondigital-df70z3837.txt)

@lsat12357 This is ready for you. Let me know if I missed anything.

**Comment by lsat12357** [comment]
all known issues cleared. will rerun preflight prior to export.
