### ISSUE TITLE
[Remediation] or-latino-herit preflight check

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#1504]
collection_id: or-latino-herit

### Known Issues
- [x] Bad cpd (Sarah and Linda)
- [ ] Bad preds (Linda)
- [x] Missing required data (Sarah)

**Comment by lsat12357** [comment]
bad predicates:
  dce:type #can be deleted?
  opaquenamespace/ns/rightsHolder #can be moved to dct:rightsHolder?
  dct:coverage #can be moved to location?

**Comment by lsat12357** [comment]
preflight flagged these as children missing from this parent: oregondigital:df70j695k
Looks like they're just in a deleted state?
{"df70j443d", "df70j444p", "df70j445z", "df70j4467", "df70j447h", "df70j448s","df70j4492", "df70j450t", "df70j4513", "df70j452c", "df70j453n", "df70j454x", "df70j4556"}

**Comment by sseymore** [comment]
bad predicates:
dce:type #can be deleted? Yes, as long as DC type is there, which it's required, so assuming it is.

opaquenamespace/ns/rightsHolder #can be moved to dct:rightsHolder? Yes.

dct:coverage #can be moved to location? What assets? Assuming will need to convert string(s) to URIs, yes?

preflight flagged these as children missing from this parent: oregondigital:df70j695k
Looks like they're just in a deleted state? Yeah, I don't know why these are deleted. I don't see any special permissions documented. Undeleted.

**Comment by lsat12357** [comment]
I think this is good now (preflight won't clear the cpd error until I redo the pidlist)
