### ISSUE TITLE
[Remediation] percent-for-art preflight checks

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#1505]
collection_id: percent-for-art

### Known Issues
- [x] Bad cpd (Sarah and Linda)
- [x] Bad dates (Sarah)
- [x] Bad preds (Linda)
- [x] Missing required data (Leslie)

**Comment by lsat12357** [comment]
cpds with children flagged as missing
oregondigital:df67zm81n
  "df67xc64c", "df67xc65n"
oregondigital:df67zn425
  "df67xh158", "df67xh16j", "df67xh17t", "df67xh183", "df67xh204", "df67xh21d", "df67xh22p", "df67xh23z", "df67xh247", "df67xh25h", "df67xh26s"
oregondigital:df67zn43f
  "df67xh272", "df67xh28b", "df67xh30c", "df67xh31n", "df67xh32x"
oregondigital:df67zn450
   "df67xh379", "df67xh39v", "df67xh40m", "df67xh41w"
oregondigital:df67zp06h
  "df67xq91b"
oregondigital:df67zp69s
  "df67z237s", "df67z239b", "df67z2446", "df67z249k"
oregondigital:df67zq355
  "df67z2293"

**Comment by lsat12357** [comment]
bad predicate is a false alarm, preflight run on outdated version of crosswalk_overrides?

**Comment by sseymore** [comment]
@lsat12357 For the missing identifier fields, please put percent_m000 in that field for remediation in OD2 post-lauch.

**Comment by sseymore** [comment]
@lsat12357 corrected all the cpds above, except:

For oregondigital:df67zn425: Delete children. Convert parent to single item. (PDF already created for all children pages.) 
For oregondigital:df67zn450: same as above
oregondigital:df67zp69s: same as above

Apart from the mass-add of data for the identifier field, I think this is ready for re-run on my end. Let me know.

**Comment by lsat12357** [comment]
there are still some edtf errors, but am closing this.
