### ISSUE TITLE
[Remediation] schnitzer-mofa preflight check

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#1506]
collection_id: schnitzer-mofa

### Known Issues
- [x] Bad dates (Sarah and Linda)
- [x] Bad preds (Linda)

**Comment by sseymore** [comment]
../.. should be the correct EDTF form of date, yes? @lsat12357 can we confirm? All other dates remediated.

**Comment by lsat12357** [comment]
ugh. see https://github.com/OregonDigital/OD2/issues/2199

**Comment by lsat12357** [comment]
other than edtf issues, this is passing
