### ISSUE TITLE
[Remediation] sheetmusic preflight check

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#1507]
collection_id: sheetmusic

### Known Issues
- [x] Bad dates (Sarah)
- [x] Bad preds (Linda)

**Comment by lsat12357** [comment]
It looks like when I fix the locationCopySublocation predicate, I also need to replace the uri-object with a string? I'm assuming it's the same value throughout?
<http://oregondigital.org/resource/oregondigital:df71j0173> <http://www.loc.gov/standards/mods/modsrdf/v1.html#locationCopySublocation> <http://id.loc.gov/vocabulary/organizations/orumu> .

**Comment by sseymore** [comment]
Yeah, http://id.loc.gov/vocabulary/organizations/orumu should be replaced with the label: University of Oregon Knight Library, Music Services Section

**Comment by lsat12357** [comment]
preflight clean
