### ISSUE TITLE
[Remediation] building-or preflight check

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#1510]
collection_id: building-or

### Known Issues
- [x] Bad dates (Leslie)
- [x] Bad preds (Linda)
- [x] Bad URIs (Leslie)
- [x] Missing required data (Leslie, Sarah and Linda)

**Comment by lsat12357** [comment]
ok, here's some wacky predicates for this coll
oregondigital:df67sn00s	Predicate not found: http://opaquenamespace.org/ns/sheetmusic/largerWork during crosswalk
oregondigital:df68gn31c	Predicate not found: http://opaquenamespace.org/ns/sheetmusic/hostItem during crosswalk
oregondigital:fx71bw165	Predicate not found: http://opaquenamespace.org/ns/sheetmusic/hostItem during crosswalk
oregondigital:fx71c1849	Predicate not found: http://opaquenamespace.org/ns/sheetmusic/largerWork during crosswalk

**Comment by lsat12357** [comment]
assuming assets have dc.type, delete these? 
http://purl.org/dc/elements/1.1/type  "img"

**Comment by sseymore** [comment]
@lsat12357 For the missing identifier fields, please put pna_m000 in that field for remediation in OD2 post-lauch.

**Comment by sseymore** [comment]
assuming assets have dc.type, delete these?
http://purl.org/dc/elements/1.1/type "img"

Yes.

oregondigital:df67sn00s Predicate not found: http://opaquenamespace.org/ns/sheetmusic/largerWork during crosswalk
oregondigital:df68gn31c Predicate not found: http://opaquenamespace.org/ns/sheetmusic/hostItem during crosswalk
oregondigital:fx71bw165 Predicate not found: http://opaquenamespace.org/ns/sheetmusic/hostItem during crosswalk
oregondigital:fx71c1849 Predicate not found: http://opaquenamespace.org/ns/sheetmusic/largerWork during crosswalk

These statements can be deleted. Data is in other fields. These are preds for sheet music, so don't know how this happened.

**Comment by sseymore** [comment]
Note about remediation for missing identifier above. For missing resource_type, all are images, please add: http://purl.org/dc/dcmitype/Image.

**Comment by lsat12357** [comment]
the majority of bad predicates are for creator, dce:type, rightsHolder, stylePeriod, and workType
I printed out the raw statements, and the values currently in those fields, file is on google drive in  the uo_pkg5 folder, "building-or_bad_preds_vals.txt"
type is already slated to go away; the rest appear to be legit (there are a handful of creators that are not uris though), and don't appear to be already in the field, so if they look ok to you, I can insert them.  If you can give me uris to replace the creator strings, I can insert those too.

**Comment by sseymore** [comment]
Worktype URI replacements:

http://id.loc.gov/authorities/subjects/sh85078076 with http://vocab.getty.edu/aat/300164014
http://id.loc.gov/authorities/subjects/sh85075320 with http://vocab.getty.edu/aat/300444926
http://id.loc.gov/authorities/subjects/sh85062603 with http://vocab.getty.edu/aat/300005425
http://id.loc.gov/authorities/subjects/sh96004672 with http://vocab.getty.edu/aat/300379282
http://id.loc.gov/authorities/subjects/sh85038731 with http://vocab.getty.edu/aat/300026030

The rest I did by hand. Working on remediating your last comment above.

**Comment by sseymore** [comment]
@lsat12357 There are 119 building-or works in review on OD1. https://oregondigital.org/reviewer?f%5Bdesc_metadata__institution_label_sim%5D%5B%5D=University+of+Oregon%24http%3A%2F%2Fid.loc.gov%2Fauthorities%2Fnames%2Fn80126183&f%5Bdesc_metadata__set_label_sim%5D%5B%5D=Building+Oregon%24http%3A%2F%2Foregondigital.org%2Fresource%2Foregondigital%3Abuilding-or&per_page=100&q=&search_field=all_fields

Please delete these items. They are duplicate uploads.

**Comment by sseymore** [comment]
Ok, I think I got all of the creator strings:

Goodwin, George:
Carroll, William G.:
Sparrow, Alex:
Peters, William H.:
(Member of U.S. Army Corps of Engineers)
Johnson, Peter: 
Banister and Banister:

I am trying to create URIs in opns, but it's being SO SLOW right now. I will update this comment with the URIs when they are ready. 

Noticing a lot of bad URIs in creator, styleperiod ,and worktype. Remove /page/ from URI:

http://vocab.getty.edu/aat/...
http://vocab.getty.edu/ulan/...

**Comment by lsat12357** [comment]
these are strings in fields that require URIs
oregondigital:sf268h46t Invalid URI Rosas, Marion found in crosswalk
oregondigital:df67k516r Invalid URI kerby found in crosswalk
oregondigital:sf268h42q Invalid URI Rosas, Marion found in crosswalk
oregondigital:sf268j35h Invalid URI Clark, Liz found in crosswalk
oregondigital:sf268j91v Invalid URI Delph, Sheldon G. found in crosswalk
oregondigital:df67j917p Invalid URI Craftsman found in crosswalk
oregondigital:df67j917p Invalid URI Colonial Revival found in crosswalk

**Comment by lharka** [comment]
@lsat12357 I've fixed the above strings. 

I don't know enough to give input on the colorSpace property. Curious if @jsimic has thoughts regarding whether or not it can be deleted.

**Comment by jsimic** [comment]
@lsat12357 @lharka  Colorspace is now part of the [file characterization](https://staging.oregondigital.org/concern/parent/df70bn027/file_sets/9593tv123#content), so it can be dumped from the descriptive metadata.

**Comment by lharka** [comment]
Oh! Good to know. Thanks, Julia!

**Comment by lsat12357** [comment]
thankyou thankyou. I think this can be exported now
