### ISSUE TITLE
[Remediation] uo-athletics preflight check

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#1519]
collection_id: uo-athletics

### Known Issues
- [x] Bad dates (Sarah and Linda)
- [x] Bad preds (Linda)
- [x] Bad URIs (Leslie)

**Comment by sseymore** [comment]
Paul and Leslie are helping with remediation of dates and bad URIs.

**Comment by lharka** [comment]
bad URIs are fixed

**Comment by lsat12357** [comment]
blank uri here oregondigital:df73dk621
I fixed a date with a space, these might just need to include digits?
oregondigital:df668k59b
oregondigital:df70n338v

**Comment by lsat12357** [comment]
fixed all the rightHolder preds; schema.org/event is correct, getting flagged for lower case 'e'

**Comment by sseymore** [comment]
oregondigital:df73dk621 - I think blank got deleted with empties deletion. ready for re-run of preflight.

**Comment by lsat12357** [comment]
preflight clean
