### ISSUE TITLE
[Remediation] easia preflight check

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1523]
collection_id: easia

### Known Issues
- [x] Bad dates (Julia)
- [x] Bad predicates (Linda)
- [x] Bad URIs (Julia)
- [x] Missing (Julia)

### Related Tickets
#1274

**Comment by jsimic** [comment]
re: Bad dates, all appear to be correct save oregondigital:df72d0699, which I have changed.

**Comment by lsat12357** [comment]
ah. dates will depend on https://github.com/OregonDigital/OD2/issues/2199

**Comment by lsat12357** [comment]
clean except for edtf
