### ISSUE TITLE
[Remediation] gb-warner-nosatsu preflight check

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1524]
collection_id: gb-warner-nosatsu

### Known Issues
- [ ] Bad cpds (Linda)
- [x] Bad predicates (Linda)
- [x] Bad URIs (Julia)

### Related Tickets
#1449 , #1314 , #1311 , #1274 , #1260

**Comment by jsimic** [comment]
Couldn't find anything wrong in the form view that would account for the blank URI errors in the preflight dump. Corrected 1 incomplete URI

**Comment by lsat12357** [comment]
ugh. I forgot about the cpd mess. will try to figure out what's going on. 
oregondigital:df719w666
{"df719w36g", "df719w37r", "df719w381", "df719w42m", "df719w43w", "df719w445", "df719w45f", "df719w470", "df719w488", "df719w49j", "df719w51k","df719w52v", "df719w54d", "df719w55p", "df719w56z", "df719w58h", "df719w59s","df719w63c"}
oregondigital:df71dg934
{"df71dg54f"}

**Comment by lsat12357** [comment]
I haven't checked all of the children from oregondigital:df719w666, but it looks like they were deleted. If they should be deleted, let me know and I will remove them from the cpd, otherwise, I think the cpd will be fixed if you undelete them.

**Comment by jsimic** [comment]
I'm not finding any that are deleted. Can you give me pids?

**Comment by lsat12357** [comment]
the pids are listed above, in my comment from Apr 8

**Comment by jsimic** [comment]
@lsat12357 Done restoring and reviewing

**Comment by lsat12357** [comment]
preflight looks clean
