### ISSUE TITLE
[Remediation] joanna-russ preflight check

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1525]
collection_id: joanna-russ

### Known Issues
- [x] Bad predicates (Linda)

### Related Tickets
#1314 , #1311

**Comment by lsat12357** [comment]
oregondigital:df724h74w has author and recipient, but under bad creator it has http://id.loc.gov/authorities/names/n83126414

**Comment by jsimic** [comment]
Corrected author by hand. All other raws are good to dump

**Comment by lsat12357** [comment]
preflight clean
