### ISSUE TITLE
[Remediation] lowenstam preflight check

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1526]
collection_id: lowenstam

### Known Issues
- [x] Bad dates (Julia, Linda)

**Comment by jsimic** [comment]
@lsat12357 Here are the date corrections. The sheet has columns for both View Date and Date. I hand corrected one record that had multiple values for Date and removed it from the sheet
[lowenstam_badDates.xlsx](https://github.com/OregonDigital/oregondigital/files/7816981/lowenstam_badDates.xlsx)
.

**Comment by lsat12357** [comment]
so just to be clear, I can delete whatever is currently in viewDate and date and insert the values from the spreadsheet?

**Comment by lsat12357** [comment]
reran preflight, it is still flagging bad dates due to https://github.com/OregonDigital/OD2/issues/2199
will run preflight again once we resolve
