### ISSUE TITLE
[Remediation] maic preflight check

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1527]
collection_id: maic

### Known Issues
- [x] Bad dates (Julia)
- [x] Bad predicates (Linda)

### Related Tickets
#1274 , #878

**Comment by lsat12357** [comment]
ok to delete raw statement from oregondigital:df66pq04n and oregondigital:df66pq05x?

**Comment by jsimic** [comment]
@lsat12357 Yes, delete raws for both

**Comment by lsat12357** [comment]
preflight clean

**Comment by sseymore** [comment]
Worktype URI replacement:

http://id.loc.gov/authorities/subjects/sh93002379 replace with http://vocab.getty.edu/aat/300006998? @jsimic should confirm this one.

**Comment by jsimic** [comment]
Replacement suggested by Sarah Beth above is confirmed.

**Comment by lsat12357** [comment]
are you waiting for me to fix these? there are 5
