### ISSUE TITLE
[Remediation] marketing-photos preflight check

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1528]
collection_id: marketing-photos

### Known Issues
- [x] Bad dates (Julia, Linda)
- [x] Missing fields (Julia, Linda)
- [x] Bad predicates (Linda)

### Related Tickets
#1314 , #1311

**Comment by jsimic** [comment]
@lsat12357 Here are the corrections for the bad dates and missing fields
[marketing-photos_missing.xlsx](https://github.com/OregonDigital/oregondigital/files/7803792/marketing-photos_missing.xlsx)
[marketing-photos_badDates.xlsx](https://github.com/OregonDigital/oregondigital/files/7803793/marketing-photos_badDates.xlsx)
.

**Comment by lsat12357** [comment]
passing preflight
