### ISSUE TITLE
[Remediation] uo-stock-photos preflight check

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1530]
collection_id: uo-stock-photos

### Known Issues
- [x] Bad dates (Julia)
- [x] Bad URIs (Julia, Linda)

### Related Tickets
#1311

**Comment by jsimic** [comment]
@lsat12357 Here are the corrections for the bad URIs
[uo-stock-photos_badURIs.xlsx](https://github.com/OregonDigital/oregondigital/files/7803950/uo-stock-photos_badURIs.xlsx)

**Comment by lsat12357** [comment]
preflight is flagging schema.org/event, a false alert. otherwise clean.
