### ISSUE TITLE
manually set labels for licenses

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/oregondigital#1535]
There are some 121k assets that use license but have no labels; wickr notes that it is no longer possible to fetch labels but they can be set manually. This would be doable since there are only a handful of uris in use. This is not a migration issue, but it is a problem for current OD1 users.

Related: #1284

**Comment by wickr** [comment]
I set several of the CC license labels manually and made sure they were all indexed. A Solr search for items with a license URI but no label comes back clean.
