### ISSUE TITLE
Change Northwest Christian University collection title

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1536]
Northwest Christian University changed their name to Bushnell University. Please change the collection title, the collection landing page, and the Set and Primary Set labels to reflect this.

**Comment by jsimic** [comment]
And replace the NCU logo image on the collection landing page with the new logo.
![Bushnell-University-Logo](https://user-images.githubusercontent.com/6344086/150880857-586e69ed-2465-476d-ac4b-fa1957c334cc.png)

**Comment by lsat12357** [comment]
Landing page has a history of name changes for the school; additional text to cover latest name change?
