### ISSUE TITLE
[Remediation] osu-historical-publications preflight checks

### ISSUE THREAD

**Issue by KevinJonesMeta** [OregonDigital/oregondigital#1542]
collection_id: osu-historical-publications

### Known Issues
- [x] Bad dates
- [x] Bad uris (Kevin)
- [x] missing identifiers (Kevin)

### Related Tickets
#1311

**Comment by KevinJonesMeta** [comment]
Dates were replaced, uris added, and identifiers added.

**Comment by wickr** [comment]
Preflight check ran again, only 2 errors found:
* oregondigital:df72sf840 missing required field: identifier
* oregondigital:fx71bd32n missing required field: identifier

**Comment by wickr** [comment]
Kevin fixed, all good.
