### ISSUE TITLE
[Remediation] osu-scarc preflight checks

### ISSUE THREAD

**Issue by KevinJonesMeta** [OregonDigital/oregondigital#1544]
collection_id: osu-scarc

### Known Issues
- [x] bad dates (Kevin)
- [x] bad uris (Kevin)
- [x] missing identifiers (Kevin)

**Comment by KevinJonesMeta** [comment]
Dates and uris changed and identifiers added. I believe this can be rechecked and should pass preflight.

**Comment by wickr** [comment]
Another check found 6 left.

oregondigital:9z903g35p in date, 1970 circa is not in EDTF format
oregondigital:df70dh26b in date, 1925 circa is not in EDTF format
oregondigital:df725h211 in date, 1950 circa is not in EDTF format
oregondigital:df73dd018 in date, 1965 circa is not in EDTF format
oregondigital:f4752k51g in date, 1973 circa is not in EDTF format
oregondigital:kp78h8639 in date, 1973 circa is not in EDTF format
