### ISSUE TITLE
New collection: Ethos

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#1549]
Collection name: Ethos Magazine
Collection PID: ethos-magazine
Blurb:

Ethos is a nationally recognized, award-winning independent student publication. Its mission is to elevate the voices of marginalized people who are underrepresented in the media landscape and to write in-depth, human-focused stories about the issues affecting them. 

Ethos is part of Emerald Media Group, a non-profit organization that’s fully independent of the University of Oregon. Students maintain complete editorial control over Ethos and work tirelessly to produce the magazine. 

Slideshow images forthcoming

**Comment by sseymore** [comment]
@lsat12357 can you create the set so I can ingest a couple of PDFs to complete this collection set up? Thanks.

**Comment by lsat12357** [comment]
collection is created, not yet reviewed

**Comment by sseymore** [comment]
Thanks so much! 3 issues are ingested and can be reviewed:

https://oregondigital.org/catalog/oregondigital:fx71d771n
https://oregondigital.org/catalog/oregondigital:fx71d772x
https://oregondigital.org/catalog/oregondigital:fx71d7736

These are also the slideshow images.

**Comment by lsat12357** [comment]
had to reupload the pdf for fx71d772x. 
collection is now reviewed, landing page has been pushed.

**Comment by lsat12357** [comment]
landing page live

**Comment by sseymore** [comment]
thank you!
