### ISSUE TITLE
Ulmann licensing update

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1556]
@lsat12357 Please apply a [CC-BY-NC-SA 4.0 license](https://creativecommons.org/licenses/by-nc-sa/4.0/) to the 383 works in [Doris Ulmann photographs](https://oregondigital.org/sets/doris-ulmann) that are [In Copyright](https://oregondigital.org/sets/doris-ulmann?f%5Bdesc_metadata__rights_label_sim%5D%5B%5D=In+Copyright%24http%3A%2F%2Frightsstatements.org%2Fvocab%2FInC%2F1.0%2F).

This is a decision by David to prep the collection for adding to the JSTOR Community Collections.

**Comment by lsat12357** [comment]
this is done
