### ISSUE TITLE
remediation lee-moorhouse

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/oregondigital#1559]
collection_id:  lee-moorhouse

### Known Issues
bad predicates, see on google drive pre_flight_checks/uo_pkg6/lee-moorhouse_bad_preds_vals.txt
this is a scrape for each asset using one or more of three bad predicates
displays the statement containing the bad predicate
and the current contents of the corresponding field
I can either just remove the bad statements
or transfer the objects to the correct field

Note: this used to be for moorhouse, but I realized that it should be for lee-moorhouse.

**Comment by sseymore** [comment]
@lsat12357 All objects (alternative, subject, creator fields) can be moved to the correct predicate.
