### ISSUE TITLE
remediation uo-president

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/oregondigital#1562]
collection_id: uo-president

### Known Issues
use of backslash in identifier is causing asset to fail crosswalk in migration.
for example: HC_421\x_kUA16.bx08.2

I can try to fix by changing to a forward slash, but if the letter following the slash creates a special char (eg \t) then this is a lot harder.
there are 73 of these, so it might be possible to do a combination of automated and manual cleanup
See attached file below.

**Comment by lsat12357** [comment]
[uo-pres_fails.txt](https://github.com/OregonDigital/oregondigital/files/9236468/uo-pres_fails.txt)

**Comment by sseymore** [comment]
@lsat12357 Remediated. Let me know if I missed anything.
