### ISSUE TITLE
loc organizations in od_repository field

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/oregondigital#1569]
http://id.loc.gov/vocabulary/organizations/csf
http://id.loc.gov/vocabulary/organizations/kslawsma
http://id.loc.gov/vocabulary/organizations/maj
http://id.loc.gov/vocabulary/organizations/manp
http://id.loc.gov/vocabulary/organizations/mbhm
http://id.loc.gov/vocabulary/organizations/mdbpm
http://id.loc.gov/vocabulary/organizations/nhudo
http://id.loc.gov/vocabulary/organizations/orjm
http://id.loc.gov/vocabulary/organizations/orumu
http://id.loc.gov/vocabulary/organizations/vilxw
these can't be used on OD2

http:///id.loc.gov/vocabulary/organizations/oreuurm has already been fixed.
### Known Issues
- [ ]

**Comment by jsimic** [comment]
http://id.loc.gov/vocabulary/organizations/csf
http://id.loc.gov/authorities/names/n50059285

http://id.loc.gov/vocabulary/organizations/kslawsma
http://id.loc.gov/authorities/names/n79000993

http://id.loc.gov/vocabulary/organizations/maj
http://id.loc.gov/authorities/names/n50062105

http://id.loc.gov/vocabulary/organizations/manp
http://id.loc.gov/authorities/names/n79122151

http://id.loc.gov/vocabulary/organizations/mbhm
http://id.loc.gov/authorities/names/n88100238

http://id.loc.gov/vocabulary/organizations/mdbpm
http://id.loc.gov/authorities/names/n79086312

http://id.loc.gov/vocabulary/organizations/nhudo
http://opaquenamespace.org/ns/repository/OlanaStateHistoricSite

http://id.loc.gov/vocabulary/organizations/orjm
http://id.loc.gov/authorities/names/no2008063027

http://id.loc.gov/vocabulary/organizations/orumu
http://opaquenamespace.org/ns/repository/UniversityofOregonKnightLibraryMusicServicesSection

http://id.loc.gov/vocabulary/organizations/vilxw
http://id.loc.gov/authorities/names/n79046221

**Comment by lsat12357** [comment]
thank you! swap made
