### ISSUE TITLE
opaquenamespace rights need to be replaced

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/oregondigital#1570]
these won't work on OD2
       "http://opaquenamespace.org/ns/rights/rr-f",  311,
        "http://opaquenamespace.org/ns/rights/unknown", 19,
        "http://opaquenamespace.org/ns/rights/educational",  5
I've already started swapping some of the 'unknown' statements for http://rightsstatements.org/vocab/UND/1.0/
"Copyright Undetermined" in gb-warner-nosatsu

### Known Issues
- [ ]

**Comment by jsimic** [comment]
Rights mapping is on a tab in the [MAP](https://docs.google.com/spreadsheets/d/1ien3djlZxcctuAE99XweyuNdMiN5YsrKoYBJcK3DjLQ/edit#gid=1130314680)

**Comment by lsat12357** [comment]
righto, forgot to check the map.
hm, I thought I'd started adding reviewed_ssim  to my solr queries... but I don't see the unknown or the educational rights in the sidebar. Fixing the rr-f though, they seem to be all uo.
