### ISSUE TITLE
[Remediation] percent-for-art

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/oregondigital#1576]
collection_id: percent-for-art
2 wonky uris turned up during ingest, both in this asset: oregondigital:df67xm01j under lcsubject
http://opaquenamespace.org/ns/subject/appliquétechnique
http://opaquenamespace.org/ns/subject/appliquévisualworks
these were not created on opaquenamespace, the first one appears to have a getty equivalent, not sure about the second.

### Known Issues
- [ ]

**Comment by jsimic** [comment]
@lsat12357 Looks like both are mistakes due to automation and have AAT entires
appliquetechnique is http://vocab.getty.edu/aat/300053646
appliquevisualworks is http://vocab.getty.edu/aat/300264062

**Comment by lsat12357** [comment]
brilliant! yes, forgot the obligatory this-was-my-fault at the top

**Comment by jsimic** [comment]
How is this your fault? I'm pretty sure the mistake was ours.

**Comment by lsat12357** [comment]
ok, how about we split it

**Comment by jsimic** [comment]
Agreed!
