### ISSUE TITLE
[Remediation] [schnitzer-mofa] 

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/oregondigital#1578]
collection_id: schnitzer-mofa
### Known Issues
- [ ] a large quantity of assets have no institution; since they also have no primary set, this prevents the admin_set lookup from completing. I can do the insertion if it's simple

**Comment by jsimic** [comment]
@lsat12357  All assets should all be UO: http://id.loc.gov/authorities/names/n80126183

**Comment by lsat12357** [comment]
danke
