### ISSUE TITLE
Check on quality of pyramidal tiffs generated from 16-bit tiffs

### ISSUE THREAD

**Issue by jechols** [OregonDigital/oregondigital#338]
In order to make vips work with 16-bit tiffs, we have to convert from TIFF to JPG and back to TIFF.  This won't likely cause quality loss as our pyramidal TIFF is really just a JPG tile container, but we should check how things look at various zoom levels.

Here are some examples:

http://oregondigital.library.oregonstate.edu/catalog/oregondigital:79407x16z
http://oregondigital.library.oregonstate.edu/catalog/oregondigital:79407x177
http://oregondigital.library.oregonstate.edu/catalog/oregondigital:5m60qr88b

**Comment by jsimic** [comment]
Any progress on this? It will effect the art collections...

**Comment by terrellt** [comment]
@jsimic Do you have a good example full-res tiff we can test on locally?

**Comment by jsimic** [comment]
Yes. http://pages.uoregon.edu/jsimic/delivery/2007_VRC_11893.tif

**Comment by terrellt** [comment]
@jsimic Is there an item with that image that shows the artifacts?
