### ISSUE TITLE
Fix links UI

### ISSUE THREAD

**Issue by jechols** [OregonDigital/oregondigital#353]
Links are somewhat weird right now because we just sort of throw in `<a>` tags and manually separate them with a hyphen.  This results in odd link spacing and dangling hyphens for certain roles:

![archivist-links](https://cloud.githubusercontent.com/assets/2157974/2759541/0638568c-c9a3-11e3-8aa7-15045f7c0c85.png)

We should (a) make the items lists (`<li>`) since that area is just a sort of "actions" list, and (b) look into CSS for separators.  The page footer is a little weird, but it's on the right track, not having special characters in the HTML.  I think we can use `:after`, `:content`, and things like `:first-of-type` to create good separators.

I tossed together a quick example: http://jsfiddle.net/NHGxd/

**Comment by mellinma** [comment]
It's cleaned up from this original problem.
