### ISSUE TITLE
Investigate IIIF working with Hydra 

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/oregondigital#379]
http://iiif.io/

Want to use IIIF as a way to get images and metadata from hydra into external exhibits. IIIF developers are a lot of Hydra folks and may be interested in helping/extending.

**Comment by jechols** [comment]
I think this is now a non-issue, isn't it?  We pull metadata from the OD search JSON interface, and that gives us all metadata (not just metadata releated to images), relevant facets, and other useful information.

Looking at the IIIF docs, I'm not sure we'd want to implement our own IIIF API given that we already have an image server (IIP) and a search + metadata service (provided by Blacklight and/or Hydra).

**Comment by terrellt** [comment]
There's benefits to having a metadata standard for viewers (it opens up things like Mirador down the line), but we can push this ticket as far back as we like.
