### ISSUE TITLE
Allow sorting of search results and browse

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#421]
There is currently no way to sort the search results and browse results.

Some possibilities: Alpha A-Z, Alpha Z-A, Sort by Date, Recently Added (current default), Recently Updated

**Comment by kestlund** [comment]
@zhang4952 : any status update on this issue?

**Comment by terrellt** [comment]
@kestlund @wickr: Making a push on some issues in this milestone. Do we really want recently updated/added? Is it useful information?

**Comment by kestlund** [comment]
Yes, the most recently added is useful for marketing and showing things off
to users in classes, donors, etc. In the meantime, it also compensates for
the lack of a date sort for collections like ODE.

**Comment by terrellt** [comment]
Do you want most recent to mean created or updated?

**Comment by kestlund** [comment]
created.
