### ISSUE TITLE
Map OAI fields

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/oregondigital#489]

**Comment by kestlund** [comment]
Need multiple methods created. I've started mappings in the Data Dictionary:

https://docs.google.com/spreadsheets/d/1nnJz49oqstQLF2PFBn5ZvWfWdF-8PVl5TFL1EMotQrA/edit#gid=0

Can others please take a look? (esp. @jsimic @sseymore @boockm @tvc15brian @boockm @mlv611  )

@no-reply also suggest RDF/XML output for DPLA purposes.

**Comment by kestlund** [comment]
Pinging on OAI field mappings:  @jsimic @sseymore @boockm @tvc15brian @mlv611 @terrellt

**Comment by terrellt** [comment]
@kestlund I assume we're looking at the DC Elements map?

**Comment by kestlund** [comment]
DC Elements Map, DC Terms Map, DPLA map

**Comment by boockm** [comment]
@kestlund Exactly what do you need from our metadata people on this? Approval? Mapping suggestions for fields not already mapped? Alternative suggestions where applicable? @tvc15brian @Clarkeri @mlv611

**Comment by kestlund** [comment]
@boockm : just review. Is anything amiss? Just add comments to the sheet.

**Comment by mlv611** [comment]
I have been using this data dictionary to create the data dictionary for SA@OSU, and it all seems fine.

**Comment by boockm** [comment]
I agree.

**Comment by kestlund** [comment]
Now that the mapping is done, @terrellt , do we need a new issue to create the groups for mapped harvest (e.g. the multiple contributors all mapped to dc.contributor)?  Should we create a new issue for the dc vs. dcq?

**Comment by terrellt** [comment]
@kestlund Yes, a new ticket would be good. One for each dc and dcq too.
