### ISSUE TITLE
Sets list page does not respect Reviewed status

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#543]
The Sets list currently displays all Sets, whether they are Reviewed or not. This is ok for now during the transition, but later it should only show Reviewed ones.

**Comment by wickr** [comment]
This looks good. For deploy though, I wonder if some of the current sets aren't actually Reviewed and if they would then be then hidden on the Sets list. It might be good to check them before deploy, or keep the old list open and verify everything is still public.

**Comment by wickr** [comment]
Also, #432 complicates this some for any new ones.

**Comment by terrellt** [comment]
wickr: #432 complicates things because you can't see the landing pages if they're not reviewed? Wouldn't you just review them in dev?

**Comment by terrellt** [comment]
["oregondigital:uo-president", "oregondigital:texts-data", "oregondigital:electric-studio", "oregondigital:james-cloutier", "oregondigital:john-bauguess", "oregondigital:uo-veterans", "oregondigital:building-or", "oregondigital:cw-furlong", "oregondigital:nw-folklife", "oregondigital:uo-athletics", "oregondigital:moorhouse", "oregondigital:lee-drake", "oregondigital:percent-for-art", "oregondigital:ormaps", "oregondigital:artists-books", "oregondigital:roy-c-andrews", "oregondigital:dan-powell", "oregondigital:uo-stock-photos", "oregondigital:angelus-studio", "oregondigital:clarence-andrews", "oregondigital:maic", "oregondigital:western-waters", "oregondigital:tribal-legacies", "oregondigital:mss-rb", "oregondigital:walter-bowman", "oregondigital:gb-warner", "oregondigital:uo-arch-photos", "oregondigital:or-latino-herit", "oregondigital:rv-mills", "oregondigital:oimb", "oregondigital:grayson-mathews", "oregondigital:album-collection", "oregondigital:corvallis-flood", "oregondigital:osu-historical-publications", "oregondigital:osu-scarc", "oregondigital:daily-barometer", "oregondigital:general-catalogs", "oregondigital:illustrated-booklets", "oregondigital:rockyshore93", "oregondigital:oregon-state-yank", "oregondigital:orange-owl", "oregondigital:middle-east-water", "oregondigital:gifford", "oregondigital:streamsurvey", "oregondigital:oregon-multicultural-archives", "oregondigital:gwilliams"]

These are unreviewed as of right now. Should I review them?

**Comment by wickr** [comment]
@terrellt No, not that you can't see the landing pages. Just more that you can't easily review a set in the Admin UI. (If I remember correctly it does actually Review it, you just have to navigate back from the broken link).

**Comment by wickr** [comment]
@terrellt yeah I would review all of those. @kestlund if you don't want any of the UO ones to be 'live' then they could always be un-reviewed.

**Comment by terrellt** [comment]
@wickr Ah. I don't think this hurts that.

**Comment by wickr** [comment]
True, that shouldn't be a tough fix either. I'll merge this now and assuming the sets are reviewed it should be fine to deploy.
