### ISSUE TITLE
Ingest Gifford Collection

### ISSUE THREAD

**Issue by terrellt** [OregonDigital/oregondigital#551]
- [x] Make photographer a Controlled Vocabulary, based on LC Names.
- [x] Figure out what to do with \<refere\>
- [x] Figure out predicate for \<origin\> (Identifier? There's already \<identi\> though.)
- [x] Figure out what \<compou\> is (Compound? Is Scenic Oregon album prints a thing?)
- [x] Figure out \<relate\> (Odd.)
- [x] Ingest bags
- [x] Review bags.

**Comment by tvc15brian** [comment]
Is 'printouts' supposed be showing up as a Work Type? Just curious.

**Comment by jsimic** [comment]
It can be. See http://www.getty.edu/vow/AATFullDisplay?find=printouts&logic=AND&note=&english=N&prev_page=1&subjectid=300028467

**Comment by tvc15brian** [comment]
thanks @jsimic

**Comment by mlv611** [comment]
@jsimic @terrellt I think the second work type (printouts) should be removed.

**Comment by jsimic** [comment]
@mlv611 @tvc15brian : Completely up to you guys.

**Comment by tvc15brian** [comment]
@wickr @terrellt @mickeroo we're about to start a metadata cleanup process with this collection. We have about 35 items waiting for the local workType term of "Glass positives", which I added to worktype.jsonld a couple months ago. How long does it take for new Opaque Namespace Vocabulary Terms to make it into Oregon Digital?

**Comment by terrellt** [comment]
Until I run the code to re-fetch things from github. I'll start it.

**Comment by terrellt** [comment]
@tvc15brian It's in there and autocompleting now.

**Comment by tvc15brian** [comment]
Thanks! @terrellt

**Comment by wickr** [comment]
Update from SCARC meeting 6/18/15:

Before Reviewing this collection:
- [ ] Fix Photographers URIs and facets - Ryan
- [ ] Fix Local Collection Names - Ryan
- [ ] Fix wrong Regions/Locations - Erin

That will be enough to Review, and then we can continue Topic and Work Type cleanup.

**Comment by wickr** [comment]
I will likely fix the work type URIs sooner rather than later, because you can't edit an item until they are corrected (Term not in Controlled Vocabularies error).

**Comment by wickr** [comment]
WorkTypes are mostly cleaned up:

- Changed 'Glass negatives' to 'glass plate negatives' URI
- Changed 'Glass positives' to URI
- Changed 'Nitrate negatives' to 'cellulose nitrate film' URI
- Changed 'Stereoscopic negatives' to 'Stereographs' URI
- Removed 'printouts' URI

Unsure about: 
- change 'transparencies' URI to 'photographic transparencies' URI
- Still just text: 'Glass' (3x), 'Glass copy negatives' (3x), 'Copy negatives' (2x)
- I wonder if 'Glass positives' URI or an acceptable substitute is in AAT? Maybe http://www.getty.edu/vow/AATFullDisplay?find=glass+positive&logic=AND&note=&english=N&prev_page=1&subjectid=300127186
Then we could move away from the OpaqueNamespace term.

**Comment by wickr** [comment]
Photographers URIs cleanup should be finished. Any that aren't listed listed or faceting at this point I don't believe were in CONTENTdm to begin with, but let me know if I missed anything. Summary:

* Changed old http://dummynamespace.org/creator URIs to new http://opaquenamespace.org URIs for Ralph I. Gifford, Ben L. Gifford, Wanda Gifford, Cecil Ager
* Changed text strings to URIs for Ben L. Gifford, Ralph (I.) Gifford, Wanda Gifford, Nels Tinning

**Comment by wickr** [comment]
I also started on the Location cleanup, mapping text to Geonames URIs. There's 274 fields that are not URIs.

**Comment by Clarkeri** [comment]
@wickr I tried fixing some of the fields today before I left. I will finish fixing the rest on Monday.

**Comment by wickr** [comment]
@Clarkeri which fields do you mean? Location? I was going to bulk change most of those.

**Comment by Clarkeri** [comment]
@wickr I changed a few of the location fields. I'm glad you can just do a bulk change. Thanks!

**Comment by wickr** [comment]
Thanks Erin, apparently you changed almost all of them. I fixed the few remaining ones. Then I ran a script to fix older Geonames URIs that didn't have a slash, and then I ran another script to basically reindex the Geonames labels, so all of the Location/Region facets should be correct and clean.

I also fixed some of the missing images today but there's still lots more.

**Comment by wickr** [comment]
I fixed about 50 missing images, and I'm pretty sure I got them all.

I want to do some quick Subject cleanup but after that this should be good enough to Review.

**Comment by wickr** [comment]
Bulk changes for Subjects are done. There were 1500+ text strings, with lots of repeats. Most were in TGM, a handful were in LCSH/LCNAF. There's about 100 left.

**Comment by wickr** [comment]
Down to 10 unique text strings for Subject:

Extension (2x)
Face Rock
Gifford, house of (20x)
Kueny, Mary (5x)
Nygren, Gene
Poling Hall
Reiling, Norman (4x)
Runnion, Kenneth
Steiner, John
Weatherford Hall

**Comment by wickr** [comment]
Everything is reviewed and live. The remaining subject cleanup was moved to new content repo: osulp/oregondigital-content#1
