### ISSUE TITLE
Ingest Williams Collection 

### ISSUE THREAD

**Issue by mickeroo** [OregonDigital/oregondigital#554]
- [x] Figure out \<huc\> it's referenced in oe_explorer mapping as *oregon:hydrologicUnitCode* but there is no entry in opaquenamespace.jsonld
- [x] Figure out \<llid\> also referenced in oe_explorer mapping as *oregon:llid* but there is no entry in opaquenamespace.jsonld
- [x] Figure out \<identi\> contains strings like "WilliamsG: ES_salt_creek_rr"
- [x] Figure out \<relati\>  contains entries like "Columbia River album; Native Americans album"
- [x] Figure out \<find\> file names:  "2016.jp2", "2017.jp2"
- [x] Come up with a plan for compound objects
- [x] Ingest bags
- [x] Review bags.

**Comment by mickeroo** [comment]
@tvc15brian @boockm Apologies for the delay in getting back to you about this.  The problem we have is that we can't ingest the parent objects without ingesting their children first.  We don't have a working parent/child edit form yet so these complex objects have to be ingested in bulk.  To get that to work I need is the metadata and images for the child objects (4, 209, 222, and 416) shown below.  With the metadata and images I can create bags for the missing children, ingest them, and then ingest their parents. 

http://oregondigital.org/u?/gwilliams,153	(parent)
http://oregondigital.org/u?/gwilliams,4 	**(doesn't exist)**
http://oregondigital.org/u?/gwilliams,116 (exists)

http://oregondigital.org/u?/gwilliams,231	(parent)
http://oregondigital.org/u?/gwilliams,209 **(doesn't exist)**
http://oregondigital.org/u?/gwilliams,210 (exists)

http://oregondigital.org/u?/gwilliams,232	(parent)
http://oregondigital.org/u?/gwilliams,222	**(doesn't exist)**
http://oregondigital.org/u?/gwilliams,223	(exists)

http://oregondigital.org/u?/gwilliams,418	(parent)
http://oregondigital.org/u?/gwilliams,416	**(doesn't exist)**
http://oregondigital.org/u?/gwilliams,417	(exists)

**Comment by boockm** [comment]
@tvc15brian I'd suggest just deleting these and putting them on the list of items to be scanned and added to the hydra set later. What do you think?

**Comment by tvc15brian** [comment]
@boockm @mickeroo I've actually found the tif files for the first three - doing a file search for the last one.

**Comment by tvc15brian** [comment]
@mickeroo found the last one - the item number in CDM didn't jive with the actual filename. I've placed all four the missing tif files inside the gwilliams folder on lun08. As far as the metadata goes, I'll work with @Clarkeri. Are you looking to get a .csv file?

**Comment by mickeroo** [comment]
@tvc15brian ideally the metadata for those items would be in the same format as the desc.all file, then I could just run the bagging script on it.  Is that an option?  Otherwise I could take the CSV and map it to desc.all manually as CSV ingest is currently not working.

**Comment by tvc15brian** [comment]
@mickeroo Sorry this is taking a while - locked out of CONTENTdm currently.

**Comment by mickeroo** [comment]
@tvc15brian  received the metadata CSVs from @Clarkeri and have bagged and ingested the missing items (and their parent complex objects) successfully.  The collection should be ready for review now.

**Comment by boockm** [comment]
@mickeroo Appears to have been a successful ingest except for one problem: All the items with Format: application/octet-stream do not have content associated with them. Checking these items in CONTENTdm, it appears that these should all be Format:image/tiff.

**Comment by mickeroo** [comment]
@boockm the items that were showing as application/octet-stream were jp2 images.  I've fixed the references for those items and now the images appear and can be downloaded.

**Comment by boockm** [comment]
@mickeroo Thanks Mike. The collection is reviewed and ready to go live then.
