### ISSUE TITLE
Ingest UO Vets

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/oregondigital#558]

**Comment by sseymore** [comment]
Still getting raw statements for Military Service Locations in the edit view but the locations are appearing in the item view- not sure if a problem. 

One example:

http://oregondigital.library.oregonstate.edu/sets/uo-veterans/oregondigital:w9505112w

Raw statement:

<http://oregondigital.org/resource/oregondigital:w9505112w> <http://opaquenamespace.org/ns/militaryServiceLocations> "(2005-2007): Afghanistan. (2007-2010): Iraq." .

**Comment by sseymore** [comment]
Ingested 2015 items but getting raw statements Military Service Location:

<http://oregondigital.org/resource/oregondigital:df70j779d> <http://opaquenamespace.org/ns/militaryServiceLocations> "Univerisity of Notre Dame, Indiana; Chicago; Portland, Oregon; Fort Sill, Oklahoma" .

For this item: http://oregondigital.org/catalog/oregondigital:df70j779d#page/1/mode/1up

These are not appearing in the .nts, so let me know if it's a problem on my end.

**Comment by lsat12357** [comment]
try militaryServiceLocation (not plural)

**Comment by sseymore** [comment]
Ah, ok. Thanks.
