### ISSUE TITLE
Ingest Mongolian Altai Inventory Collection

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/oregondigital#562]
May be some issue with VRA Core depending on LC.

**Comment by lsat12357** [comment]
all items ingested, looks like at least these triples at bottom:
http://www.loc.gov/standards/mods/modsrdf/v1/#note
http://opaquenamespace.org/ns/objectOrientation
http://opaquenamespace.org/ns/photographOrientation
http://purl.org/ontology/holding#label

**Comment by jsimic** [comment]
@kestlund : Label does appear in the triples

**Comment by jsimic** [comment]
hasVersion (formerly Site ID) appears not to be searchable?
http://oregondigital.org/sets/maic/oregondigital:df66p1436

**Comment by jsimic** [comment]
@jechols @mccallum Esther would like the same category searches on the project website to be available on the Hydra collection homepage:

Altars - includes:
altars
circular altars
small circular altars
ovoos/oboos

Circles - includes
circles
stone circles
large circles
semi-circles
small circular altars
circular altars

Dwellings and Lines - includes
dwellings
enclosures
extended linear features
frames
serpentine features
rays

Inscriptions - includes
inscriptions

Khirigsuur - includes
boulder khirigsuur
platform khirigsuur
round khirigsuur
khirigsuur
square khirigsuur

Mounds - includes
burial mounds
collared mounds
double mounds
four-cornered mounds
key-hole mounds
mounds-unknown use
rectangular mounds
ritual mounds
berms (landscaped-site elements)
stupas

Petroglyphs - includes
petroglyphs
Uighur images

Standing Stones - includes
balbal
deer stones
false image stones
image stones, Bronze Age
massive standing stones
menhirs
Turkic image stones
false deer stones
standing stones

Tamga - includes
tamga

Turkic Memorials - includes
Turkic image stones
enclosures
false image stones

**Comment by lsat12357** [comment]
@lsato replace worktype http://vocab.getty.edu/aat/300006985 with http://opaquenamespace.org/ns/workType/Altai/standingstones

**Comment by jechols** [comment]
@jsimic, I'm not sure that can be done with OregonDigital.  It might be something we could hard-code, but it will definitely take some time, and I'm not sure when I'll have time for that.

@lsat12357 are the vocabs still in flux?  I need to know when you change that, because it'll break the MA exhibit site in a few pretty significant ways.  We have to be VERY careful of any metadata changes due to the way the exhibit site had to be rebuilt.

**Comment by lsat12357** [comment]
@jsimic @jechols term change was requested by Esther.

**Comment by lsat12357** [comment]
more changes
[Uploading MAIC_metadataChanges.xlsx…]()
