### ISSUE TITLE
Ingest Percent for Art

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/oregondigital#563]
- May run into VRA issues with LC.  
- Need to wait for Karen to add ULAN to vocabs before ingesting. (ULAN will not be available until Dec. '14, but we'll ingest as-is in preparation.)

**Comment by jsimic** [comment]
URL in description is acting as URI not string, z.B.: http://oregondigital.library.oregonstate.edu/reviewer/oregondigital:df66kt361

**Comment by lsat12357** [comment]
need to fix the ulan uris, right now they look like
http://www.getty.edu/vow/ULANFullDisplay?find=500125519&role=&nation=&prev_page=1&subjectid=500071809

**Comment by lsat12357** [comment]
fixing street address predicate, creator, rightsHolder, and changing from uris back to the original strings for two fields (hasVersion, materials). ignoring problem jsimic noticed on Jan 26 for the moment (with consent), rebagging
