### ISSUE TITLE
Ingest Picturing Cayuse... (Moorhouse-wk)

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/oregondigital#567]
Comments from last review:

- delete the tribal status for this collection
- split tci classes and terms at semicolons and map to tgm
- hasVersion - delete
- add additional set statement for http://oregondigital.org/resource/oregondigital:lee-moorhouse

**Comment by lsat12357** [comment]
lots of predicate typos to clean up: exif and modsrdf are missing #, dc alternative is cap, used opns subject as a predicate, and uses dc hasFormat (not on properties list?)
