### ISSUE TITLE
Ingest Northwest Folklife

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/oregondigital#575]
http://example.org/ns/421 http://oregondigital.org/ns/localCollectionName http://oregondigital.org/ns/localCollectionName/WebfootsandBunchgrassersFolkArtoftheOregonCountry .
http://example.org/ns/421 http://purl.org/dc/terms/title "Detail of concho, soft focus" .
http://example.org/ns/421 http://purl.org/ontology/holding#label "OFA/79_OL_A12.12" .
http://example.org/ns/421 http://purl.org/dc/terms/date "1979-05-16" .
http://example.org/ns/421 http://vocab.getty.edu/resource/aat/collectors http://id.loc.gov/authorities/names/n80102437 .
http://example.org/ns/421 http://opaquenamespace.org/ns/contributingInstitution http://dbpedia.org/resource/University_of_Oregon .
http://example.org/ns/421 http://purl.org/dc/terms/subject "Harsin, Arthur J., 1910-" .
http://example.org/ns/421 http://purl.org/dc/terms/spatial http://sws.geonames.org/5725727 .
http://example.org/ns/421 http://www.loc.gov/standards/vracore/vocab/culture http://id.loc.gov/authorities/subjects/sh85045785 .
http://example.org/ns/421 http://www.loc.gov/standards/vracore/vocab/culture http://id.loc.gov/authorities/subjects/sh85118887 .
http://example.org/ns/421 http://www.loc.gov/standards/vracore/vocab/culture http://id.loc.gov/authorities/subjects/sh85068091 .
http://example.org/ns/421 http://www.loc.gov/standards/vracore/vocab/culture http://id.loc.gov/authorities/subjects/sh85040094 .
http://example.org/ns/421 http://opaquenamespace.org/ns/ethnographic http://id.loc.gov/vocabulary/ethnographicTerms/afset011210 .
http://example.org/ns/421 http://opaquenamespace.org/ns/ethnographic "objects and products of material culture" .
http://example.org/ns/421 http://opaquenamespace.org/ns/ethnographic "body adornments and alterations" .
http://example.org/ns/421 http://opaquenamespace.org/ns/ethnographic http://id.loc.gov/vocabulary/ethnographicTerms/afset003521 .
http://example.org/ns/421 http://opaquenamespace.org/ns/ethnographic "clothing by body region" .
http://example.org/ns/421 http://opaquenamespace.org/ns/ethnographic http://id.loc.gov/vocabulary/ethnographicTerms/afset007287 .
http://example.org/ns/421 http://opaquenamespace.org/ns/ethnographic "footwear components" .
http://example.org/ns/421 http://opaquenamespace.org/ns/ethnographic http://id.loc.gov/vocabulary/ethnographicTerms/afset017404 .
http://example.org/ns/421 http://opaquenamespace.org/ns/ethnographic "general processes and techniques (physical objects)" .
http://example.org/ns/421 http://opaquenamespace.org/ns/ethnographic "production (material culture)" .
http://example.org/ns/421 http://opaquenamespace.org/ns/ethnographic "specific production techniques (material culture)" .
http://example.org/ns/421 http://opaquenamespace.org/ns/ethnographic http://id.loc.gov/vocabulary/ethnographicTerms/afset011463 .
http://example.org/ns/421 http://opaquenamespace.org/ns/ethnographic http://id.loc.gov/vocabulary/ethnographicTerms/afset016621 .
http://example.org/ns/421 http://www.w3.org/1999/02/22-rdf-syntax-ns#type "35mm color slide" .
http://example.org/ns/421 http://id.loc.gov/vocabulary/relators/rps "Randall V. Mills Archives of Northwest Folklore, University of Oregon, Eugene, Oregon" .
http://example.org/ns/421 http://purl.org/dc/terms/rights http://opaquenamespace.org/rights/educational .
http://example.org/ns/421 http://opaquenamespace.org/rights/rightsHolder "Oregon Arts Commission" .
http://example.org/ns/421 http://purl.org/dc/terms/type http://purl.org/dc/dcmitype/Image .
http://example.org/ns/421 http://purl.org/dc/terms/format http://purl.org/NET/mediatypes/image/jpeg .
http://example.org/ns/421 http://purl.org/dc/terms/identifier "OFA_79_OL_A12_12" .
http://example.org/ns/421 http://opaquenamespace.org/ns/set http://oregondigital.org/resource/oregondigital:nw-folklife .
http://example.org/ns/421 http://purl.org/dc/terms/replaces https://oregondigital.org/u?folklore,421 .

**Comment by lsat12357** [comment]
not sure how to fix these. do I need to delete and reingest? or is it a database fix?
http://oregondigital.org/bulk_task_children/371161
