### ISSUE TITLE
Ingest Oregon Latino Heritage (UO)

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/oregondigital#577]
<http://example.org/ns/1> <http://purl.org/dc/terms/title> "Evan Bosh's extended family - MaggioVanNostrand Side (mom's side)" .
<http://example.org/ns/1> <http://purl.org/dc/terms/description> "Photograph submitted as part of Julia Thornton's final project in the ANTH/J-410/510 Latino Roots class, Spring 2011." .
<http://example.org/ns/1> <http://id.loc.gov/vocabulary/relators/rps> "University of Oregon Libraries - Special Collections and University Archives" .
<http://example.org/ns/1> <http://opaquenamespace.org/ns/localCollectionName> <http://opaquenamespace.org/ns/localCollectionName/LatinoRoots> .
<http://example.org/ns/1> <http://opaquenamespace.org/ns/localCollectionID> "UA142" .
<http://example.org/ns/1> <http://opaquenamespace.org/ns/seriesName> "Bosch, Evan, testimony" .
<http://example.org/ns/1> <http://purl.org/dc/elements/1.1/identifier> "UA142_thornton_julia_20120503_018" .
<http://example.org/ns/1> <http://id.loc.gov/vocabulary/relators/dnr> <http://id.loc.gov/authorities/names/no2006061740> .
<http://example.org/ns/1> <http://purl.org/dc/terms/format> <http://purl.org/NET/mediatypes/image/jpeg> .
<http://example.org/ns/1> <http://purl.org/dc/terms/type> <http://purl.org/dc/dcmitype/Image> .
<http://example.org/ns/1> <http://purl.org/dc/terms/rights> <http://creativecommons.org/licenses/by-nc-nd/4.0/> .
<http://example.org/ns/1> <http://opaquenamespace.org/rights/rightsHolder> "University of Oregon" .
<http://example.org/ns/1> <http://opaquenamespace.org/ns/set> <http://oregondigital.org/resource/oregondigital:or-latino-herit> .
<http://example.org/ns/1> <http://opaquenamespace.org/ns/contributingInstitution> <http://dbpedia.org/resource/University_of_Oregon> .
<http://example.org/ns/1> <http://purl.org/dc/terms/replaces> <https://oregondigital.org/u?latinoherit,1> .

**Comment by sseymore** [comment]
This collection was ingested in September but now the videos are not working... help?! Is this a derivative issue because the videos were working then.

@wickr 

https://oregondigital.org/sets/or-latino-herit?f%5Bdesc_metadata__type_label_sim%5D%5B%5D=Moving+Image%24http%3A%2F%2Fpurl.org%2Fdc%2Fdcmitype%2FMovingImage

**Comment by wickr** [comment]
@sseymore ok, looking into it. Trying to regenerate derivatives now.

**Comment by sseymore** [comment]
@wickr thank you!

**Comment by wickr** [comment]
@sseymore Video derivatives are complete and working now.

**Comment by sseymore** [comment]
@wickr thanks!
