### ISSUE TITLE
Ingest Building Oregon

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/oregondigital#578]
Previous notes:

- split fields on  semicolon for new statements: alternative, CreatorDispaly, creator, workType, citation, date, temporal, stylePeriod
- Use local URI in creator.jsonld for creator need to ask Julia / Sarah to make sure they are there
- citation  (looks like final one may have trailing semicolon 
- CC rights and license should be the same URI (4.0)
- [need to ask Julia about tiffs] if so need to change format
- URI for photographers, need to ask Julia
-  strip links from the citation field that have http://boundless.uoregon.... starting with the preceding comma? (e.g. , http://boundless.uoregon.edu/u?/archpnw,7590) ;
- loads of spelling errors, so ran through a checker, please use desca.all file on Google Drive
- double-check full text
- turns out some items have UO CC-BY-SA, so need to add another condition to rights method to look for SA and use http://creativecommons.org/licenses/by-sa/4.0/ for both rights and license
- need to update Karen's foul-up on Europeana rights to http://www.europeana.eu/rights/rr-f/

**Comment by kestlund** [comment]
@jsimic , Can you please check-in with @lsat12357 on this?

@mickeroo needs for OSU mobile app.

**Comment by jsimic** [comment]
@kestlund : archpnw1: StreetAddress, creator, creatorDisplay, note, license, rightsHolder in raw statements, not in triples. Label in raw statements and in triples.

archpnw2: Creator, note in raw statements, not in triples. Label, license in raw statements and in triples. Many derivatives missing, but only ingested today.

Example: http://oregondigital.library.oregonstate.edu/reviewer/oregondigital:df66qp75k

**Comment by lsat12357** [comment]
I think streetaddress (and a few others?) have been fixed since I ran archpnw1 back in November, so if I delete and reingest, that should fix the discrepancies btwn archpnw1 and archpnw2.

**Comment by sseymore** [comment]
After batch ingesting another 305 items, I'm seeing raw statements again as above:

<http://oregondigital.org/resource/oregondigital:df673902t> <http://purl.org/dc/terms/creator> <http://opaquenamespace.org/ns/creator/JTTedFrancis> .
<http://oregondigital.org/resource/oregondigital:df673902t> <http://www.loc.gov/mads/rdf/v1#streetAddress> "3110 Portland Road, Newburg, OR 97132" .
<http://oregondigital.org/resource/oregondigital:df673902t> <http://opaquenamespace.org/ns/vra/workType> <http://vocab.getty.edu/aat/300007140> .
<http://oregondigital.org/resource/oregondigital:df673902t> <http://opaquenamespace.org/ns/vra/stylePeriod> <http://vocab.getty.edu/aat/300121793> .
<http://oregondigital.org/resource/oregondigital:df673902t> <http://opaquenamespace.org/ns/vra/stylePeriod> <http://vocab.getty.edu/aat/300265600> .
<http://oregondigital.org/resource/oregondigital:df673902t> <http://opaquenamespace.org/ns/rightsHolder> <http://id.loc.gov/authorities/names/no89008456> .

 Also not in the n-triples. 

for http://oregondigital.library.oregonstate.edu/ingest/oregondigital:df673902t

**Comment by jsimic** [comment]
@sseymore please add to ticket #769

**Comment by lsat12357** [comment]
regenerated nts to get geo info ~ 3/27

**Comment by lsat12357** [comment]
redoing nts bc stylePeriod should not be strings.

**Comment by lsat12357** [comment]
in the Work Type field (http://www.w3.org/1999/02/22-rdf-syntax-ns#type)
 
replace http://vocab.getty.edu/aat/300006720
 
with http://vocab.getty.edu/aat/300266108
