### ISSUE TITLE
Ingest OIMB

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/oregondigital#580]
May have some issues with dwc and scientific vocabs. We may just have to see.

**Comment by lsat12357** [comment]
found that ubio does have a web service for rdf, explained at
http://www.ubio.org/index.php?pagename=rdf
for example
http://www.ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:447505

**Comment by lsat12357** [comment]
also that itis has been published as linked data here:
https://taskman.eionet.europa.eu/projects/linkeddata/wiki/DataSets
for instance, 
http://rdfdata.eionet.europa.eu/itis/taxon/180595
can we use?

**Comment by lsat12357** [comment]
<http://example.org/ns/3> <http://purl.org/dc/terms/title> "1" .
<http://example.org/ns/3> <http://purl.org/ontology/holding#label> "1.1.1" .
<http://example.org/ns/3> <http://purl.org/dc/terms/subject> <http://opaquenamespace.org/ns/subject/Diatoms> .
<http://example.org/ns/3> <http://purl.org/dc/terms/subject> <http://opaquenamespace.org/ns/subject/ubio_9678962> .
<http://example.org/ns/3> <http://rs.tdwg.org/dwc/terms/phylum> <http://opaquenamespace.org/ns/phylum/itis_2286> .
<http://example.org/ns/3> <http://rs.tdwg.org/dwc/terms/genus> <http://opaquenamespace.org/ns/genus/itis_2624> .
<http://example.org/ns/3> <http://purl.org/dc/terms/description> "fossil point" .
<http://example.org/ns/3> <http://rs.tdwg.org/dwc/terms/identificationVerificationStatus> "Very Certain" .
<http://example.org/ns/3> <http://purl.org/dc/terms/date> "1971" .
<http://example.org/ns/3> <http://purl.org/dc/terms/type> <http://purl.org/dc/dcmitype/Image> .
<http://example.org/ns/3> <http://purl.org/dc/terms/format> <http://purl.org/NET/mediatypes/image/jpeg> .
<http://example.org/ns/3> <http://purl.org/dc/terms/rights> <http://creativecommons.org/licenses/by-nc-nd/4.0/> .
<http://example.org/ns/3> <http://opaquenamespace.org/rights/rightsHolder> "University of Oregon" .
<http://example.org/ns/3> <http://creativecommons.org/ns#license> <http://creativecommons.org/licenses/by-nc-nd/4.0/> .
<http://example.org/ns/3> <http://opaquenamespace.org/ns/set> <http://oregondigital.org/resource/oregondigital:oimb> .
<http://example.org/ns/3> <http://opaquenamespace.org/ns/contributingInstitution> <http://dbpedia.org/resource/University_of_Oregon> .
<http://example.org/ns/3> <http://purl.org/dc/terms/replaces> <http://oregondigital.org/u?/oimb,3> .

**Comment by lsat12357** [comment]
<http://example.org/ns/230> <http://purl.org/dc/terms/title> "207" .
<http://example.org/ns/230> <http://purl.org/ontology/holding#label> "1.15.1" .
<http://example.org/ns/230> <http://purl.org/dc/terms/subject> <http://opaquenamespace.org/ns/subject/itis_660055> .
<http://example.org/ns/230> <http://rs.tdwg.org/dwc/terms/phylum> <http://opaquenamespace.org/ns/phylum/itis_660055> .
<http://example.org/ns/230> <http://rs.tdwg.org/dwc/terms/genus> <http://opaquenamespace.org/ns/genus/itis_11293> .
<http://example.org/ns/230> <http://rs.tdwg.org/dwc/terms/vernacularName> <http://opaquenamespace.org/ns/commonNames/broadwingedkelporribbonkelp> .
<http://example.org/ns/230> <http://rs.tdwg.org/dwc/terms/identificationVerificationStatus> "Very Certain" .
<http://example.org/ns/230> <http://purl.org/dc/terms/date> "1975" .
<http://example.org/ns/230> <http://purl.org/dc/terms/type> <http://purl.org/dc/dcmitype/Image> .
<http://example.org/ns/230> <http://purl.org/dc/terms/format> <http://purl.org/NET/mediatypes/image/jpeg> .
<http://example.org/ns/230> <http://purl.org/dc/terms/rights> <http://creativecommons.org/licenses/by-nc-nd/4.0/> .
<http://example.org/ns/230> <http://opaquenamespace.org/rights/rightsHolder> "University of Oregon" .
<http://example.org/ns/230> <http://creativecommons.org/ns#license> <http://creativecommons.org/licenses/by-nc-nd/4.0/> .
<http://example.org/ns/230> <http://opaquenamespace.org/ns/set> <http://oregondigital.org/resource/oregondigital:oimb> .
<http://example.org/ns/230> <http://opaquenamespace.org/ns/contributingInstitution> <http://dbpedia.org/resource/University_of_Oregon> .
<http://example.org/ns/230> <http://purl.org/dc/terms/replaces> <http://oregondigital.org/u?/oimb,230> .

**Comment by lsat12357** [comment]
except I'm replacing opns rightsHolder with dc.rightsHolder

**Comment by lsat12357** [comment]
<http://example.org/ns/3> <http://purl.org/dc/terms/title> "OIMB slide 1" .
<http://example.org/ns/3> <http://purl.org/ontology/holding#label> "1.1.1" .
<http://example.org/ns/3> <http://purl.org/dc/terms/subject> <http://opaquenamespace.org/ns/subject/Diatoms> .
<http://example.org/ns/3> <http://purl.org/dc/terms/subject> <http://opaquenamespace.org/ns/subject/ubio_9678962> .
<http://example.org/ns/3> <http://rs.tdwg.org/dwc/terms/phylum> <http://opaquenamespace.org/ns/phylum/itis_2286> .
<http://example.org/ns/3> <http://rs.tdwg.org/dwc/terms/genus> <http://opaquenamespace.org/ns/genus/itis_2624> .
<http://example.org/ns/3> <http://purl.org/dc/terms/description> "fossil point" .
<http://example.org/ns/3> <http://rs.tdwg.org/dwc/terms/identificationVerificationStatus> "Very Certain" .
<http://example.org/ns/3> <http://purl.org/dc/terms/date> "1971" .
<http://example.org/ns/3> <http://purl.org/dc/terms/type> <http://purl.org/dc/dcmitype/Image> .
<http://example.org/ns/3> <http://purl.org/dc/terms/format> <http://purl.org/NET/mediatypes/image/jpeg> .
<http://example.org/ns/3> <http://purl.org/dc/terms/rights> <http://creativecommons.org/licenses/by-nc-nd/4.0/> .
<http://example.org/ns/3> <http://purl.org/dc/terms/rightsHolder> "University of Oregon" .
<http://example.org/ns/3> <http://creativecommons.org/ns#license> <http://creativecommons.org/licenses/by-nc-nd/4.0/> .
<http://example.org/ns/3> <http://opaquenamespace.org/ns/set> <http://oregondigital.org/resource/oregondigital:oimb> .
<http://example.org/ns/3> <http://opaquenamespace.org/ns/contributingInstitution> <http://dbpedia.org/resource/University_of_Oregon> .
<http://example.org/ns/3> <http://purl.org/dc/terms/replaces> <http://oregondigital.org/u?/oimb,3> .

**Comment by lsat12357** [comment]
<http://example.org/ns/233> <http://purl.org/dc/terms/title> "OIMB slide 210" .
<http://example.org/ns/233> <http://purl.org/ontology/holding#label> "1.15.4" .
<http://example.org/ns/233> <http://purl.org/dc/terms/subject> <http://opaquenamespace.org/ns/subject/itis_660055> .
<http://example.org/ns/233> <http://rs.tdwg.org/dwc/terms/phylum> <http://opaquenamespace.org/ns/phylum/itis_660055> .
<http://example.org/ns/233> <http://rs.tdwg.org/dwc/terms/genus> <http://opaquenamespace.org/ns/genus/itis_11002> .
<http://example.org/ns/233> <http://rs.tdwg.org/dwc/terms/vernacularName> <http://opaquenamespace.org/ns/commonNames/bottlebrushseaweed> .
<http://example.org/ns/233> <http://purl.org/dc/terms/description> "and Mazzaella cornucopiae" .
<http://example.org/ns/233> <http://purl.org/dc/terms/spatial> <http://sws.geonames.org/5718757/> .
<http://example.org/ns/233> <http://rs.tdwg.org/dwc/terms/identificationVerificationStatus> "Very Certain" .
<http://example.org/ns/233> <http://purl.org/dc/terms/date> "1981" .
<http://example.org/ns/233> <http://purl.org/dc/terms/type> <http://purl.org/dc/dcmitype/Image> .
<http://example.org/ns/233> <http://purl.org/dc/terms/format> <http://purl.org/NET/mediatypes/image/jpeg> .
<http://example.org/ns/233> <http://purl.org/dc/terms/rights> <http://creativecommons.org/licenses/by-nc-nd/4.0/> .
<http://example.org/ns/233> <http://purl.org/dc/terms/rightsHolder> "University of Oregon" .
<http://example.org/ns/233> <http://creativecommons.org/ns#license> <http://creativecommons.org/licenses/by-nc-nd/4.0/> .
<http://example.org/ns/233> <http://opaquenamespace.org/ns/set> <http://oregondigital.org/resource/oregondigital:oimb> .
<http://example.org/ns/233> <http://opaquenamespace.org/ns/contributingInstitution> <http://dbpedia.org/resource/University_of_Oregon> .
<http://example.org/ns/233> <http://purl.org/dc/terms/replaces> <http://oregondigital.org/u?/oimb,233> .

**Comment by kestlund** [comment]
If the labels can be returned, then let's definitely use.

For DC right holder use URI from dbpedia instead of string for "University
of Oregon."

**Comment by jsimic** [comment]
@lsat12357 Checked bag. Here are the issues:

image viewer appears to be broken
SOME subjects from op_ns not showing up in public view
class, genus, phylum, vernacularName not in public view
rightsHolder, label, license in raw
