### ISSUE TITLE
Tests for features taking too much memory on Travis

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#586]
Lately the test runs on Travis for the features group are taking too much memory and the process is getting killed before it completes. http://docs.travis-ci.com/user/common-build-problems/#My-build-script-is-killed-without-any-error

Currently I'm profiling the test runs and looking into adjusting garbage collection settings.

**Comment by terrellt** [comment]
Travis is playing nice lately. Can we close this @wickr?

**Comment by wickr** [comment]
Sure.
