### ISSUE TITLE
Ingest Herbarium

### ISSUE THREAD

**Issue by mickeroo** [OregonDigital/oregondigital#593]
Figure out predicates and controlled vocabs for (\<tag\> **label** [Sample data])
- [x] \<descri\> ["Pages Basionym: 39-40; Pages Full Article: 39-40", ...]
- [x] \<fullte\> ["", nil, "Pages Basionym: 1,2,3,4,6,11,29; Pages Full Article: 1-14; 29", ...]
- [x] \<identi\> **Filename** ["ORE28507", "ORE9181", "ORE26792", ...]
- [x] \<collec\> **Collection Number** ["2228", "2614", "19100",...]
- [x] \<accept\> ["ATRROS", "CALHOW", "ERIOCHCAL", ...]
- [x] \<langua\> **County** ["Sweetwater", ...]
- [x] \<covera\> **State** ["Wyoming", ...]
- [x] \<countr\> **Country** ["U.S.A.", ...]
- [x] \<source\> **Location Notes** ["Granger.", "cliffs of Columbia River near the Cascades.", ...]
- [x] \<rights\> ["Copyright Oregon State University Herbarium. Digital type specimens remain the property of the Oregon State University Herbarium. For questions regarding reproduction or use, please contact the OSU Herbarium Director at: http://oregonstate.edu/dept/botany/herbarium/.  Type descriptions remain the property of the individual copyright holders.  For information on site disclaimers, participating publishers and acknowledgements, please see: http://digitalcollections.library.oregonstate.edu/cdm4/client/herbarium/acknowledgements.php?CISOROOT=/herbarium"]
- [x] \<compou\> **Accession Number** ["ORE28507", "ORE9181", "ORE26792", ...]
- [x] \<dmaccess\> ["", "ORE11000", "ip:128.193.*; deny:file"]

*edited on 9/25 to remove some of the entries I missed from the hydra_metadata spreadsheet*

- [x] Figure out **compound objects**

- [x] Ingest Bags
- [x] Review Bags

**Comment by tvc15brian** [comment]
@mickeroo just pulled down 48 missing tiffs from JSTOR (OSC0000447-OSC0000494 from above list). I'll put them on lun08?

**Comment by mickeroo** [comment]
@tvc15brian that sounds good.  Thanks!

**Comment by mickeroo** [comment]
@tvc15brian okay, down to the last 28 missing items (woo hoo!):
```
Fl. N.W. Amer. 1 510. 1901.pdf -- http://oregondigital.org/u?/herbarium,1425
Proc_Calif_Acad_Sci_25_365_ 1944.pdf --  -- http://oregondigital.org/u?/herbarium,1694
Vas_Pl_Pac_N.W_5_129_1955.pdf -- http://oregondigital.org/u?/herbarium,1746
Pflanzenreich_IV_105_89_105_1927.pdf -- http://oregondigital.org/u?/herbarium,2906
Pflanzenreich_IV_Fam_250_128_1907.pdf -- http://oregondigital.org/u?/herbarium,2907
Pittonia_4_321_1901.pdf -- http://oregondigital.org/u?/herbarium,2908
Pittonia_4_322_1901.pdf -- http://oregondigital.org/u?/herbarium,2909
U.S.D.A_Dib_Bot_Circ_30_7_1901.pdf -- http://oregondigital.org/u?/herbarium,2910
U.S.D.A_Div_Bot_Bull_13(2)_t_78_1893.pdf -- http://oregondigital.org/u?/herbarium,2911
USDA_Div_Bot_13(2)_75_1893.pdf -- http://oregondigital.org/u?/herbarium,2912
ORE95495--ORE95496_batch_ocr.pdf -- http://oregondigital.org/u?/herbarium,2914
ORE96432--ORE96536--OSC146431--ORE96517--ORE96659--ORE96523_batch_ocr.pdf -- http://oregondigital.org/u?/herbarium,2915
ORE96534--ORE75976--OSC50518_batch_ocr.pdf -- http://oregondigital.org/u?/herbarium,2916
ORE96578--OSC86127--ORE96461--OSC28778_batch_ocr.pdf -- http://oregondigital.org/u?/herbarium,2917
ORE96584_batch_ocr.pdf -- http://oregondigital.org/u?/herbarium,2918
ORE96626--ORE96625_batch_ocr.pdf -- http://oregondigital.org/u?/herbarium,2919
ORE106335--ORE106492--ORE106505--ORE106290--ORE106508--ORE106409--ORE106371_batch_ocr.pdf -- http://oregondigital.org/u?/herbarium,2920
OSC17734_batch_ocr.pdf -- http://oregondigital.org/u?/herbarium,2921
OSC170400--ORE119621_batch_ocr.pdf -- http://oregondigital.org/u?/herbarium,2922
OSC180398--OSC164219_batch_ocr.pdf -- http://oregondigital.org/u?/herbarium,2923
WILLU13575--ORE24346_batch_ocr.pdf -- http://oregondigital.org/u?/herbarium,2924
WILLU21233_batch_ocr.pdf -- http://oregondigital.org/u?/herbarium,2925
Proc_Amer_Acad_Arts_20_355_1885.pdf -- http://oregondigital.org/u?/herbarium,2926
Proc_Amer_Acad_Arts_21_413_1886.pdf -- http://oregondigital.org/u?/herbarium,2927
Proc_Amer_Acad_Arts_22_480_1887.pdf -- http://oregondigital.org/u?/herbarium,2928
Bull_Soc_Bot_France_65_38_1918.pdf -- http://oregondigital.org/u?/herbarium,2929
Proc_Cal_Acad_Sci_Ser_2_5_624_1895.pdf -- http://oregondigital.org/u?/herbarium,2930
Proc_Amer_Acad_ Arts_45_394_1910.pdf -- http://oregondigital.org/u?/herbarium,2931

**Comment by tvc15brian** [comment]
@mickeroo these all appear to be PDFs. Just moved them into lun08/herbarium/pdfs/

**Comment by mickeroo** [comment]
@tvc15brian we are getting closer! There are still a few items that did not get exported from CDM and therefore when its parent is created the complex object errors out:

http://oregondigital.org/u?/herbarium,1330
http://oregondigital.org/u?/herbarium,1375
http://oregondigital.org/u?/herbarium,2904
http://oregondigital.org/u?/herbarium,2905
http://oregondigital.org/u?/herbarium,2913
http://oregondigital.org/u?/herbarium,4567 (this one is a complex object but only has an image)

**Comment by tvc15brian** [comment]
@mickeroo Just moved the metadata for each of the items above into the 2015-03-12 folder. I was only able to find 5 of the 6 TIFF files. I also included a filename-to-barcode list that might help you find some of the new scans.

**Comment by mickeroo** [comment]
@boockm I've ingested the missing items and fixed the Use Restrictions statement to show the new OD URL for acknowledgements (it had the CDM version previously).  It's ready for review!

**Comment by boockm** [comment]
@mickeroo Thanks Mike.

It doesn't appear that most of the metadata fields are indexed. Search for "Arnica," for example. No results in hydra. These results in CONTENTdm: http://bit.ly/1INcdNB. Is that because the content isn't fully indexed until it is made live?

We will need the content of the collection to be browsable (via facets) and searchable in a variety of ways, including by: specimen type, location, family, genus, current name usage, and collector. Is that possible? The last, collector, can probably wait until we have a chance to clean the names up.

**Comment by mickeroo** [comment]
@boockm since the collection has not been reviewed yet, you won't see any search results for Herbarium unless you are signed in and have clicked on the 'reviewer' link.  From there, you should get the results you're expecting.

To made facets for specimen type, family, etc. we need to turn those items into URIs.  You will need to find a vocabulary you want to use for each of the facets, then each of the items in the collection will have to be updated with the appropriate URIs for those terms.

**Comment by boockm** [comment]
@mickeroo OK, thanks for the explanation. We'll take of that after it goes live. I know you'll be happy to hear: Publish It!

**Comment by mickeroo** [comment]
The Herbarium items are marked as reviewed. (w00t!)
