### ISSUE TITLE
Wrong Rights Statements

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/oregondigital#606]
<http://oregondigital.org/resource/oregondigital:fj236216h> <http://purl.org/dc/terms/rights> <http://www.europeana.eu/rights/rr-r/> .

@terrellt @wickr @mickeroo @boockm Just a heads up: rr-r means access is restricted and no one can get to it without logging-in or a paywall or something. This should be rr-f, since it can be viewed freely online.  I've furthered refined our definition to something paid for by our institutions to make it clear to users to use the VPN. http://oregondigital.org/copyright  Please recommend any additional language needed, too.

**Comment by wickr** [comment]
Changed OSU Baseball set from RR-R to RR-F

**Comment by wickr** [comment]
Changed the remaining OSU sets from RR-R to RR-F: GWilliams, Oregon Explorer, Gifford, Corvallis Flood. 

I think this completes the ticket.
