### ISSUE TITLE
Ingest templates not in place when forwarding fields

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#611]
If check boxes are used to forward fields from the last ingest originating in a template, template required fields are no longer required.

**Comment by jechols** [comment]
Templates don't really have required fields - they're basically just pre-filled forms.  If we want templates to create required fields, that's a possibility (though it'll definitely take some time), but right now that feature doesn't exist.

**Comment by terrellt** [comment]
@jechols ...Really? I thought it failed validation if you had a template with pre-filled fields and you don't fill them in.

**Comment by jechols** [comment]
Nope.  Templates are about as dumb as you can image.  Dumber, actually.  Imagine the simplest way of implementing templates, then divide by two :P

They are literally just pre-filling a form's data.  That was the original requirement just so we could get templates off the ground fast, with an understanding that validations on metadata would be practically nonexistent - with or without templates.

Added a new ticket.  I think this one's safe to close and a bigger discussion is needed.
