### ISSUE TITLE
Bookreader search does not work in fullscreen mode in Safari

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#622]
Bookreader search works fine in regular viewing, but when switching to fullscreen mode it no longer works, the box won't accept text input.

This may be related to #474 

Reported by Brian Davis at OSU

**Comment by terrellt** [comment]
http://stackoverflow.com/questions/16150601/substitute-for-allow-keyboard-input-javascript-full-screen I don't think we can fix this. There's a flag to enable keyboard input, but even that doesn't work in Safari for "security reasons."

**Comment by terrellt** [comment]
Closing as "can't be fixed."
