### ISSUE TITLE
Add Oregon State University and Oregon Agricultural College as an opaquenamespace term

### ISSUE THREAD

**Issue by tvc15brian** [OregonDigital/oregondigital#627]

**Comment by wickr** [comment]
Karen was correct, these are all in LC and should be usable in the forms.

Oregon State Agricultural College
	http://id.loc.gov/authorities/names/n87850581
"Use this heading for items published by the college ca. 1886-1907, and ca. 1928-1936."

Oregon Agricultural College: 
	http://id.loc.gov/authorities/names/n95078079
"Use this heading for items published by the college ca. 1908-1927"
variant label: Oregon State College (1908-1927) 

Oregon State College:
	http://id.loc.gov/authorities/names/n82022628
"Use this heading for items published by the college ca. 1937-3/6/1961"

Oregon State University:	
	http://id.loc.gov/authorities/names/n80017721
"Name changed to Oregon State University on 3/6/1961"
