### ISSUE TITLE
Rights Permissions

### ISSUE THREAD

**Issue by tpendragon** [OregonDigital/oregondigital#657]
Automatically add appropriate groups when reviewed.

RR-R means "hide from everyone" except for those in AccessRestrictions; can add UseRestrictions (SCUA at UO)

RR-F means "show to everyone - make downloadable" UNLESS there's an AccessRestriction saying nobody can download it, in which case display but don't let them download.

**Comment by terrellt** [comment]
This is in Extended Featureset 1 mostly for a discussion on the mapping.

**Comment by jsimic** [comment]
7 defined groups:

UOopen
UOrestricted
OSUopen
OSUrestricted
OSUUOopen
OSUUOrestricted
Allrestricted

**Comment by kestlund** [comment]
Opting for eliminating OSUUOopen and OSUUOrestricted in favor of two statements, so only 5 defined groups.

**Comment by jsimic** [comment]
So, new CV?

**Comment by terrellt** [comment]
https://wiki.duraspace.org/display/hydra/Rights+Metadata+Subgroup has a metadata recommendation we should use.
