### ISSUE TITLE
Ingest Pacific Northwest Stream Survey

### ISSUE THREAD

**Issue by mickeroo** [OregonDigital/oregondigital#684]
Figure out predicates and controlled vocabs for (\<tag\> **label** [Sample data])
- [x] \<source\> **Original Collection** ["Pacific Northwest Stream Survey Collection", "", "Special Scientific Report: Fisheries"]
- [x] \<langua\> **Other Forms** ["Nitrate negatives", "Silver gelatin prints", "", "print"]
- [x] \<rights\> **Restrictrion** ["Permission to use must be obtained from OSU Archives.", ""]
- [x] \<relati\> **Related Materials** ["25D; Album1 pg.39 Image 1", "25D-(3)", "25D", ...]
- [x] \<contra\> **Contributing Institution** ["Oregon State University Libraries", ""]
- [x] \<contri\> **Project questions & comments -- Internal Note Field** ["Reviewed 12/11/02 -- added subject entry to Rivers and Streams; reviewed 4/15/2003 -- added Geog Subj. for Oregon City.",...]

- [x] Ingest Bags
- [ ] Review Bags

**Comment by mickeroo** [comment]
@boockm the existing rights statement for this collection is: "Permission to use must be obtained from OSU Archives."  Does it need it's own statement or can that be mapped to one we already have?

**Comment by boockm** [comment]
@mlv611 Can you let Mike know which Europeana rights statement applies for this collection and where we want the current statement ("Permission to use must be obtained from OSU Archives.") stored?

**Comment by mlv611** [comment]
@mickeroo, I would map to the Europeana rights statement  Paid Access - no re-use

**Comment by mlv611** [comment]
Done.

**Comment by mickeroo** [comment]
@mlv611 do we want to store the current rights statement anywhere?

**Comment by mlv611** [comment]
@mickeroo is there a logical place for it?

**Comment by terrellt** [comment]
Historically we haven't saved them - we've done a Rights Statement and a Rights Holder.

**Comment by mickeroo** [comment]
Good to know.  @boockm asked about storing the existing statement in his comment above so I just wanted to make sure it got answered.

**Comment by kestlund** [comment]
Just to clarify that the paid access is only if the entire item is restricted. If just the full res is restricted then use the Free Access - no reuse and make sure to restrict the download option.  We still need a set of URIs for AccessRestrictions, which we should work on at our January meeting.

We have put the existing statement in the UseRestrictions if wanted.

**Comment by wickr** [comment]
I agree the Rights should be "Free Access - No Re-use"

**Comment by mlv611** [comment]
@wickr @mickeroo .  That sounds fine.

**Comment by boockm** [comment]
Thanks everyone. 

@mickeroo So, Rights: Free Access - No Re-use.

Rights Holder probably not necessary and no need to retain current statement.

**Comment by mickeroo** [comment]
Okay great, thanks!

**Comment by mickeroo** [comment]
@boockm The items are ingested and derivatives are done, so this set should be ready to review.

**Comment by mlv611** [comment]
I reviewed approximately 230 items - then the system went down.  Will continue to approve the rest.

**Comment by boockm** [comment]
@mlv611 Looks like some clean up needs to be done on 'Work Type', 'Type', 'Format', 'Institution' fields. You'll notice strangeness when you check the facets.

**Comment by mlv611** [comment]
@boockm @mickeroo  I don't know where the work type for the pdfs came from.  It's not in the Cdm metadata.  The metadata for the tiffs looks fine, but the facets aren't picking it up.  They have a type and a format

**Comment by mlv611** [comment]
@boockm  @.I tried to update the records but I was not able to

**Comment by tvc15brian** [comment]
@boockm @mlv611 I looked at these as well and it seems like many of the AAT work type terms aren't being pulled in and just the URI is being displayed (at least administratively it is). I was able to get 'photographic prints' to work since 'gelatin silver prints' wasn't. It's a similar situation with Gifford and I'm putting together a list of work type predicates to make ticket for.

It seems that the Geographic fields also need a bit of work as they'll have to be dealt with at the same time you try to update the other fields.
![capturfiles_15](https://cloud.githubusercontent.com/assets/2175578/5839247/c22c27da-a141-11e4-8d41-d53a336b37dd.jpg)

**Comment by boockm** [comment]
@tvc15brian @mlv611 Sounds good, Brian. How about you and Maura get together to split these up? @jsimic @sseymore Would it make sense for us to make a ticket for each field that lists all the predicates we need for that field?

**Comment by terrellt** [comment]
Some of these work type predicates were cached before, and now they seem to have gone missing. I'm starting to wonder if our triple store is losing triples.

**Comment by tvc15brian** [comment]
@boockm @mlv611 That sounds good.

**Comment by jsimic** [comment]
@boockm Don't make separate tickets, just leave a single comment with all the fields and predicates

**Comment by mlv611** [comment]
@boockm @jsimic Sounds good

**Comment by mickeroo** [comment]
@boockm it looks like this collection is in better shape now as the facets seem to be displaying correctly.  What is there left to do?

**Comment by boockm** [comment]
@mickeroo Make it live!

**Comment by mickeroo** [comment]
Done. It lives!
