### ISSUE TITLE
Added UO additional SCUA collections

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/oregondigital#687]
Florence M. Hartshorn photographs, 1899-1900 (florence-hartshorn)
Mayo Methot Bogart (1904-1951) photographs (mayo-methot-bogart)
Opal S. Whiteley (1897-1992) photographs (opal-whiteley)
Frazier A. Boutelle photographs, c. 1865-1924 (frazier-boutelle)

**Comment by srabun** [comment]
oops - talked to Julia and this ticket is actually still open. Content is present but collection/set is not set up....? @kestlund

**Comment by kestlund** [comment]
@wickr , would you be able to set up these new collections?

**Comment by wickr** [comment]
@kestlund Done, added and reviewed.
