### ISSUE TITLE
Text string WITH A SPACE entered in to ingest form in Set field saves ok but breaks future editing

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#701]
If a text string for Set is entered into the Ingest form instead of a URI, the form can be saved, but future editing of the item causes an error ("We're sorry but something went wrong.") There's also an error trying to find the item via the console.

Depending on how autocomplete works for Set, if you just type in something like 'Oregon State University Athletics' you can end up with a URI like 'http://oregondigital.org/resource/Oregon State University Athletics' which gives an RDF::Reader error, and when you try to Edit the item Rails gives an error. The item has to be repaired by the console, copying the descMetadata datastream, fixing it, deleting broken one, and saving fixed one back to the item.

**Comment by jechols** [comment]
Has this been fixed?  I did a quick test locally and couldn't reproduce it.  I get a very odd URI in the "set" field (http://oregondigital.org/resource/foo), but it doesn't give any errors.

**Comment by srabun** [comment]
@jechols look into this

**Comment by jechols** [comment]
@wickr, let me know if you can reproduce this - my test with "foo" never caused a true error, and you could edit and fix it without any problems.  So... for right now I don't really have anything to look into.

**Comment by jechols** [comment]
(I double-checked locally just to be sure - I cannot get the object to error on edit)

**Comment by wickr** [comment]
Related to #281

**Comment by lsat12357** [comment]
If I type a string into the input and update, I immediately get an error and the asset is not affected; so still not sure how those Building Oregon assets got messed up.

**Comment by duncanbarth** [comment]
From the planning discussion the plan is to spend an hour trying to recreate the issue. If we can't recreate the issue, this gets closed.

**Comment by jechols** [comment]
This is probably unrelated, but ingesting live, putting in nothing but set, I was able to cause a crash: http://oregondigital.org/catalog/oregondigital:fx71c852g

**Comment by jechols** [comment]
Updated the title.  This "works" when entering something invalid, but actually causes the crash when the set string has a space in it.

**Comment by jechols** [comment]
I found that some controlled fields auto-strip spaces when injecting a fake namespace.  I wasn't able to figure out why sets wouldn't do that, and pivoted to redoing sets as a dropdown.  PR incoming.
