### ISSUE TITLE
Clicking facets link gives error when on oregondigital.org/sets

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#703]
When on the Sets list page, http://oregondigital.org/sets  clicking facets gives the error "We're sorry, but something went wrong."

The error in the logs is: 
ActionView::Template::Error (No route matches {:action=>"show", :controller=>"sets", :id=>"oregondigital:pg15bf25q", :set=>nil})

coming via link_to_document() in collections_helper.rb

**Comment by jechols** [comment]
/sets is not only the collections list, but also the list of collections themselves (/sets/braceros, for instance).  So the sets controller is a subclass of the catalog controller.

We could try to get the facet list off this one page, or we could have /sets be a different controller than /sets/*.  I'll see what I can figure out and maybe do a PR if I find an awesome solution.

**Comment by jechols** [comment]
Or I'll find a hacky solution and make a PR anyway.  Woo!
