### ISSUE TITLE
PDF not generated in viewer for ingest

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/oregondigital#706]
What is special about this particular PDF that it doesn't work in the viewer
![ode_notvisiable](https://cloud.githubusercontent.com/assets/2481327/5324512/323b5dec-7c90-11e4-8a36-2624c99a4461.png)
.

View: http://oregondigital.org/sets/daily-emerald/oregondigital:fx719t31p

**Comment by terrellt** [comment]
Closed by #767
