### ISSUE TITLE
Clear div before acknowlegements

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/oregondigital#707]
Can we get a clear div to put "acknowledgements" under the feature and intro?
![acknow_needs_clear](https://cloud.githubusercontent.com/assets/2481327/5325458/77289d92-7ca0-11e4-99b9-cb2121d15192.png)

**Comment by mccallum** [comment]
Just did a quick fix to get rid of this item before Bootstrap 3 re-write of many things
