### ISSUE TITLE
Image corruption on derivative generation

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/oregondigital#716]
Images are sometimes pixelated in derivative creation. No way to tell until you browse to the image.

http://oregondigital.org/sets/uo-athletics/oregondigital:df669g76j 

Example in Image Viewer: 
![screen shot 2014-12-22 at 4 22 39 pm](https://cloud.githubusercontent.com/assets/2481327/5533133/c6acfbe8-89f6-11e4-9e2c-fa5a14703260.png)

High res TIFF (downloaded from site):
![screen shot 2014-12-22 at 4 21 12 pm](https://cloud.githubusercontent.com/assets/2481327/5533127/b0acbe82-89f6-11e4-948e-d9cb14e3570d.png)

**Comment by jechols** [comment]
Could this be a situation where derivatives hadn't finished?  I just browsed and all is well.

**Comment by terrellt** [comment]
This got fixed with the 16-bit tiff issue.
