### ISSUE TITLE
Transfer Opaquenamespace.org to Marmotta

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/oregondigital#717]
@no-reply work with @terrellt to transfer opaquenamespace.org domain to our new marmotta install.

URIs must resolve!

**Comment by terrellt** [comment]
@no-reply Can has?

**Comment by mickeroo** [comment]
@kestlund has the transfer started?

**Comment by mickeroo** [comment]
OSU is managing the domain opaquenamespace.org and the site is running.
