### ISSUE TITLE
Missing rights statement for Lincoln Co. 

### ISSUE THREAD

**Issue by mickeroo** [OregonDigital/oregondigital#718]
@boockm what rights statement should we use for this collection?  @kestlund  pointed out in the meeting earlier today that it's lacking a rights statement so I'd like to add it.

**Comment by mickeroo** [comment]
@tvc15brian any word from Larry about this?

**Comment by tvc15brian** [comment]
@mickeroo I've asked a couple times and I'm not sure what's happening. I have to contact him later about another collection and will suggest that we just use Free Access - No Re-use until we hear from LCHS. I'll get you something to move forward with by the end of the day so we can put this one to bed. Sorry for delays 😰.

**Comment by mickeroo** [comment]
@tvc15brian I've just updated the collection to include the rights statement **Free Access - no reuse** and if we hear anything back from LCHS to the contrary we can change it.

**Comment by tvc15brian** [comment]
That works for us. Thanks @mickeroo
