### ISSUE TITLE
Turn off validation on creator field for ingest form

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/oregondigital#719]

**Comment by terrellt** [comment]
@kestlund @eatonm I just pushed up a branch that makes saving an asset with a string Creator actually build an OpaqueNamespace URI and set a label. Does that work?

**Comment by kestlund** [comment]
@terrellt : I find that quite slick but terrifying.  We would probably create a lot of garbage that way and basically lose all control in the vocab.

**Comment by terrellt** [comment]
@kestlund We were just about to turn OFF control of that vocab entirely, no? This way provides a road to translating our strings to Opaque Namespace.

**Comment by kestlund** [comment]
@terrellt : Perhaps, I misunderstood. We can turn off the control vocab temporarily. But I don't want strings to be automatically created in OPNS, because a review and cleanup process should happen first.  Especially, since students and other non-catalogers will be using the form for initial entries, I don't want URIs to be auto-built. Eventually, we want to control creators.

**Comment by terrellt** [comment]
I can build temporary fluff URIs for strings if you'd like, so that it's not in OpaqueNamespace, and we can move those statements over to properly controlled statements later.

I can't turn off validation of a CV field entirely without breaking faceting, linking out, and displaying of labels instead of URIs.

**Comment by kestlund** [comment]
@terrellt : that sounds much better

@jsimic : what do you think?

**Comment by jsimic** [comment]
I agree with @terrellt Let's try not to loose what control we have...

**Comment by terrellt** [comment]
https://github.com/OregonDigital/oregondigital/pull/722 This now turns strings in the form into URIs like "http://dummynamespace.org/creator/StringYouPutInHere"
