### ISSUE TITLE
Change PDF derivative image generation

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#720]
Current behavior is to go through each image size and extract all page images of that size, and then move to the next image size. This always uses the PDF as the source for each derivative image, and can take several hours with large PDFs.

Look at reworking the code to extract the largest JPG first, and then create the rest of the smaller JPGs from first JPG.

Another option may be to change the PDF to single-page PDFs using docsplit's extract_pages feature, which may ease up on memory used and processing time needed.

**Comment by kestlund** [comment]
@wickr : how are spaces issues factored between the JPG and PDF issue.  I like the idea of idea as each of its own page. Ideally, a real PDF viewer would be great someday.

**Comment by wickr** [comment]
@kestlund Space for disk storage? I'm not sure, but I was thinking this was just to help out image processing and so would only be temporary files. 

I'm going to try and test out processing times with a large file and can track filesizes as well.

**Comment by kestlund** [comment]
@wickr : Yes, I was thinking about disk storage. We inflate our PDFs quick a bit by our process and just wondering if the PDF individual files could help reduce that, too.

**Comment by wickr** [comment]
Here's results for the 2 test documents I've run so far. The times are just looking at file timestamps but should give a good enough picture of the changes.

-------------------------
Orange Owl, October 1921 (28 pages)
PDF: 49.9MB

OLD: 
x-large:	11:30-11:36  (6m)
large:		11:36-11:43  (7m)
normal:		11:44-11:51  (7m)
small:		11:51-11:59  (8m)
Total Time: 28m
Total Size: 22MB

NEW:
x-large:	4:59-5:00 (1m)
large:		5:00-5:01 (1m)
normal:		5:01-5:01 (<1m)
small:		5:01-5:01 (<1m)
Total Time: ~4m
Total Size: 20MB
----------------------

1957 Yearbook (464 pages)
PDF: 79.2MB

OLD:
x-large:	5:37-7:02  (1h25m)
large:		7:02-8:21  (1h19m)
normal:		8:22-9:52  (1h30m)
small:		9:52-11:23, 9:01-9:35  (2h5m)
Total Time: 6h 29m  (389m)
Total Size: 297MB

NEW:
x-large:	3:26-3:55  (29m)
large:		3:55-3:59  (4m)
normal:		3:59-4:02  (3m)
small:		4:02-4:05  (3m)
Total Time: 39m 
Total Size: 264MB

(Really not sure why the x-large run was way faster, it should have been roughly the same)

**Comment by terrellt** [comment]
Woah, I wonder why the x-large went quicker. Either way, awesome!
