### ISSUE TITLE
Interviewer and Interviewee fields not displaying

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/oregondigital#725]
Fields in model not showing on user view for interviewer and interviewee.

@terrellt : Do you know why these are not showing up?  I can create classes and make facetable, which we might want to do eventually, but I don't know why they are not showing up.

https://github.com/OregonDigital/oregondigital/blob/master/app/models/datastream/oregon_rdf.rb
![screen shot 2015-01-08 at 11 38 45 am](https://cloud.githubusercontent.com/assets/2481327/5669259/34869f84-972b-11e4-9685-68da97e487e6.png)
![screen shot 2015-01-08 at 11 33 30 am](https://cloud.githubusercontent.com/assets/2481327/5669261/36052da8-972b-11e4-9d8d-ee4f2d91a5ef.png)

**Comment by kestlund** [comment]
I think I know I was missed.

**Comment by terrellt** [comment]
@kestlund These should work - what do you think went wrong?

**Comment by kestlund** [comment]
They didn't have a class associated, so I think the opaquenamespace terms weren't rendering. I asked Jeremy to associate creator class (which has people) and to try that.

**Comment by terrellt** [comment]
@kestlund Do you have a link?

**Comment by terrellt** [comment]
@kestlund Found it. The problem's not that. Your n-triples look like this:

```
<http://oregondigital.org/resource/oregondigital:br86b4223> <http://id.loc.gov/vocabulary/relators/ive> "http://opaquenamespace.org/ns/creator/PrickettJakeb" .
<http://oregondigital.org/resource/oregondigital:br86b4223> <http://id.loc.gov/vocabulary/relators/ivr> "http://opaquenamespace.org/ns/creator/PelroyJacob" .
<http://oregondigital.org/resource/oregondigital:br86b4223> <http://id.loc.gov/vocabulary/relators/ivr> "http://opaquenamespace.org/ns/contributor/MockfordKevin" .
```

Strings that look like URIs, instead of URIs.

**Comment by kestlund** [comment]
@sseymore , since there aren't very many of these, do you think you can go through and replace the URIs as strings with the URIs?

**Comment by sseymore** [comment]
I'm updating all the assets now. The URIs were ingested as URIs but updating them made the URIs appear in the n-triples. 

The real issue is that they aren't appearing in the item display. 

Updating the record also got rid of the military service location raw statements, so they now appear in the item view and the n-triples.

**Comment by wickr** [comment]
@sseymore I think with the last couple Pull Requests in, Interviewee and Interviewer should be showing up now in the item display, and Interviewee is faceted. http://oregondigital.org/catalog/oregondigital:br86b4223

(UO Vets and any other sets will probably need reindexing before the Interviewee facets show up. I just edited and saved http://oregondigital.org/catalog/oregondigital:br86b4223  but it's the only one right now.)

Is this issue closable?

**Comment by sseymore** [comment]
Yes, looks like it's appearing on the other items and the Interviewee facet is appearing in the sidebar. I can go through the rest of the items and re-save them to update it. Would that reindex or is that  a system-wide thing? Thanks!

**Comment by wickr** [comment]
If you re-save them that will force the item to be reindexed.

We do have a system-level reindex, but it takes awhile to run. We can also effectively do a set-level reindex, which basically finds the right items and re-saves them via the Rails console. So let me know if you don't want to save them one-by-one.

**Comment by sseymore** [comment]
Only 30 or so. I'll do them. Thanks.
