### ISSUE TITLE
Deep RDF labels not being fetched

### ISSUE THREAD

**Issue by jechols** [OregonDigital/oregondigital#744]
http://oregondigital.org/catalog/oregondigital:df665602d

There is no "mammals" subject in the user-facing page, but the [ntriples](http://oregondigital.org/catalog/oregondigital:df665602d.nt) includes http://id.loc.gov/vocabulary/ethnographicTerms/afset011004, which clearly is mammals.  It appears the geographic metadata is also busted, as there's a geonames entry in the ntriples, but not on the page.

I think we have some cases where fetching is broken, or else our post-fetch store is broken.

**Comment by terrellt** [comment]
There are definitely a few terms that aren't being fetched. Not sure why - it may be that these jobs got killed in deploys and similar processes.

**Comment by terrellt** [comment]
If #749 gets merged we should reasonably be able to run a full fetch on every asset and see if that fixes this.

**Comment by terrellt** [comment]
@jechols @jsimic @kestlund Do we know of other objects that were having problems like this? The one in this example seems to be cleared up.

**Comment by jechols** [comment]
There were some MA objects, but I can't recall specifics - let me take a quick look

**Comment by jechols** [comment]
Yeah, we still have odd problems.  Not language per se, but a URI giving multiple differing labels.

These are both bronze age objects with the same getty URI:

- http://oregondigital.org/sets/maic?f%5Bdesc_metadata__stylePeriod_label_sim%5D%5B%5D=Age%2C+Bronze%24http%3A%2F%2Fvocab.getty.edu%2Faat%2F300019275
- http://oregondigital.org/sets/maic?f%5Bdesc_metadata__stylePeriod_label_sim%5D%5B%5D=Bronze+Age%24http%3A%2F%2Fvocab.getty.edu%2Faat%2F300019275

**Comment by terrellt** [comment]
Thanks @jechols, those are good ones to watch. That item hasn't been re-fetched yet (14,516 to go) - when it is, we'll see if it's all cleared up.

**Comment by jechols** [comment]
Ah, okay :)

**Comment by jechols** [comment]
Do we have any ETA on this?  I think we need an admin interface that shows some kind of "jobs left" or something :P

**Comment by terrellt** [comment]
@jechols http://oregondigital.org/resque Just be logged in. Someone ingested a thousand items and it pushed fetches to the end of the line.

**Comment by jechols** [comment]
Oh sweet, thanks!

**Comment by terrellt** [comment]
Fetch jobs are done - how's everything looking?

**Comment by jechols** [comment]
Bug in JSONLD now, working on it - this particular issue is probably fixed, though, as the bronze age stuff is definitely good now.

**Comment by terrellt** [comment]
@jechols @tvc15brian @wickr @jsimic How's this looking? Taken care of?

**Comment by tvc15brian** [comment]
@terrellt there still seem to be random Work Type terms coming through in Dutch and French this morning. 
http://oregondigital.org/catalog/oregondigital:df66ss463
http://oregondigital.org/catalog/oregondigital:xp68kg588

**Comment by jechols** [comment]
I wish I could add much, but I only notice things when I'm doing data sanity checks.  Right now, MA is looking better for sure, but the broken JSONLD we discovered Friday is still preventing me from saying for sure if the subset of problems I noticed is fixed.  (the work types that were in opaquenamespace)

**Comment by wickr** [comment]
Overall things look great. Found a few weird ones:

http://oregondigital.org/catalog/?_=1422904157665&f%5Bdesc_metadata__lcsubject_label_sim%5D%5B%5D=%D0%A3%D0%BD%D1%96%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%82%D0%B5%D1%82+%D0%9E%D1%80%D0%B5%D0%B3%D0%BE%D0%BD%D1%83%24http%3A%2F%2Fid.loc.gov%2Fauthorities%2Fnames%2Fn80126183

http://oregondigital.org/catalog/?_=1422904157680&f%5Bdesc_metadata__workType_label_sim%5D%5B%5D=images+num%C3%A9ris%C3%A9es%24http%3A%2F%2Fvocab.getty.edu%2Faat%2F300215302

http://oregondigital.org/catalog/?_=1422904157684&f%5Bdesc_metadata__workType_label_sim%5D%5B%5D=%E5%9C%93%E9%A0%82+%28%E5%BB%BA%E7%AF%89%E5%85%83%E7%B4%A0%29%24http%3A%2F%2Fvocab.getty.edu%2Faat%2F300001280

**Comment by terrellt** [comment]
@wickr Thanks. This is weird - it looks like not all the triples were captured before? Or some are getting lost? I don't know..

**Comment by duncanbarth** [comment]
Some of the stuff that looked weird above no longer looks weird... but we still have problems, in this case, the we have triples that are resolving, but still pulling the wrong language for the label

http://oregondigital.org/catalog/?f%5Bdesc_metadata__workType_label_sim%5D%5B%5D=zhao+pian%24http%3A%2F%2Fvocab.getty.edu%2Faat%2F300046300

**Comment by sseymore** [comment]
As of today, I'm only seeing issues in WorkType as was mentioned in the meeting:

http://oregondigital.org/catalog/?_=1424129339851&f%5Bdesc_metadata__workType_label_sim%5D%5B%5D=estampas+en+relieve%24http%3A%2F%2Fvocab.getty.edu%2Faat%2F300041391

http://oregondigital.org/catalog/?_=1424129339852&f%5Bdesc_metadata__workType_label_sim%5D%5B%5D=fonteinen%24http%3A%2F%2Fvocab.getty.edu%2Faat%2F300006179

http://oregondigital.org/catalog/?_=1424129339854&f%5Bdesc_metadata__workType_label_sim%5D%5B%5D=voedingsmiddelenfabrieken%24http%3A%2F%2Fvocab.getty.edu%2Faat%2F300006335

http://oregondigital.org/catalog/?_=1424129339854&f%5Bdesc_metadata__workType_label_sim%5D%5B%5D=paisajes+%28entorno%29%24http%3A%2F%2Fvocab.getty.edu%2Faat%2F300008626

and many more.

But I also see this lc subject from above that isn't resolved:

http://oregondigital.org/catalog/?_=1422904157665&f%5Bdesc_metadata__lcsubject_label_sim%5D%5B%5D=%D0%A3%D0%BD%D1%96%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%82%D0%B5%D1%82+%D0%9E%D1%80%D0%B5%D0%B3%D0%BE%D0%BD%D1%83%24http%3A%2F%2Fid.loc.gov%2Fauthorities%2Fnames%2Fn80126183

That's all I could find and I fixed the duplicate facets with UO Vets and some in African Political Ephemera.

**Comment by terrellt** [comment]
http://oregondigital.org/catalog/?_=1424454685531&f%5Bdesc_metadata__lcsubject_label_sim%5D%5B%5D=%D0%A3%D0%BD%D1%96%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%82%D0%B5%D1%82+%D0%9E%D1%80%D0%B5%D0%B3%D0%BE%D0%BD%D1%83%24http%3A%2F%2Fid.loc.gov%2Fauthorities%2Fnames%2Fn80126183&page=2 Some topics are also busted.

**Comment by mickeroo** [comment]
Trey is deleting the cache and triggering the fetch on everything to see if this takes care of it.

**Comment by duncanbarth** [comment]
Looks like the topic terrellt posted above works now, but the worktypes are still using the wrong language at times, so the fetch didn't seem to fix it.
