### ISSUE TITLE
Random 502 errors

### ISSUE THREAD

**Issue by jechols** [OregonDigital/oregondigital#746]
Duncan and I hit the site a bunch and randomly got 502 errors around 5:30pm to 6:00pm

Duncan was at IP 128.223.223.105
My IP was 128.223.85.89

**Comment by terrellt** [comment]
@jechols 502s come from the puma workers using an outrageous amount of memory. I significantly adjusted their ram ceilings - we'll have to watch it.

**Comment by jechols** [comment]
Should we look into something like http://timetobleed.com/memprof-a-ruby-level-memory-profiler/ to try and figure out why we are using so much RAM?

**Comment by terrellt** [comment]
I've done that and never found anything. I think this might be Puma's fault.
https://github.com/puma/puma/issues/342

I run htop and I see 9 threads, even though I tell it just to run 2.

**Comment by terrellt** [comment]
Alright, the extra threads are for "slow clients." Maybe everyone's a slow client. Adjusted some more settings and we'll see what happens.

**Comment by lsat12357** [comment]
I'm getting the 502 bad gateway today. first noticed it at 3-ish? and it's now 530.

**Comment by terrellt** [comment]
RAM issues, had to scale back some more. We're back up.

**Comment by terrellt** [comment]
Spun up Passenger instead of Puma. We'll see if it plays nicer.

**Comment by jechols** [comment]
So far so good it sounds like.  Close this or do we want further investigation?

**Comment by duncanbarth** [comment]
I hit this today at ~15:10ish, so its still happening at least sometime

**Comment by jechols** [comment]
Haven't seen this in a while, since @decimalator's fixes a month ago or so
