### ISSUE TITLE
Ingest Lee Moorhouse

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#759]
Creator in raw statments

**Comment by jsimic** [comment]
Exif missing #?
has_findingAid is acting as URI, not string

**Comment by kestlund** [comment]
dct:creator needs to be dce:creator (system not configured for dct:creator due to strings in creators for other collections).

@jsimic Can we get links to examples with the exif and has_findingAid problems?

**Comment by jsimic** [comment]
@kestlund http://oregondigital.library.oregonstate.edu/reviewer/oregondigital:df66x738s has both.
