### ISSUE TITLE
New Controlled Vocabulary – AAT Terms

### ISSUE THREAD

**Issue by tvc15brian** [OregonDigital/oregondigital#760]
We have a number of terms that we'd like to be able to use for some of our existing items and upcoming audiovisual collections (Work Type). Let me know if you need more than the URIs.

 still image:

photographic film (photographic materials)
http://vocab.getty.edu/aat/300014638

photogravures (prints)
http://vocab.getty.edu/aat/300154382

negatives (photographic)
http://vocab.getty.edu/aat/300127173

stereoscopic photographs
http://vocab.getty.edu/aat/300162872

cellulose nitrate film
http://vocab.getty.edu/aat/300311696

Autochromes (photographs)
http://vocab.getty.edu/aat/300138292

audiovisual:

3/4-inch
http://vocab.getty.edu/aat/300264685

Super-VHS (TM)
http://vocab.getty.edu/aat/300264684

VHS (TM)
http://vocab.getty.edu/aat/300264683

Betacam-SP
http://vocab.getty.edu/aat/300264687

Betacam (TM)
http://vocab.getty.edu/aat/300264686

Hi-8
http://vocab.getty.edu/aat/300264682

audiotapes
Source:http://vocab.getty.edu/aat/300028653

audiocassettes
http://vocab.getty.edu/aat/300028661

**Comment by sseymore** [comment]
They seem to be appearing in the reviewed records: http://oregondigital.library.oregonstate.edu/catalog/oregondigital:df66q788z

negatives (photographic) is there.

It could have fixed itself... ??? We also have appearing/disappearing fields at times.

**Comment by terrellt** [comment]
Fetches are running currently. It could be that it's finally getting to new ones - although I'm pretty sure those were around before. It's feeling like we're losing terms.

**Comment by tvc15brian** [comment]
Thanks - I've noticed that some of the terms were there at one point then disappeared.

**Comment by tvc15brian** [comment]
thanks @sseymore
