### ISSUE TITLE
Ingest uo-stock-photos

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/oregondigital#762]
Partial ingest of tifs from ArchivedProjects,
 a few errors with ethnographic terms as subjects.
e.g. http://id.loc.gov/vocabulary/ethnographicTerms/afset020378

**Comment by jsimic** [comment]
All errors in the uostockDPtif and uostockAPtif are the same term, which can be replaced by http://id.loc.gov/authorities/subjects/sh85007461

**Comment by lsat12357** [comment]
also http://id.loc.gov/vocabulary/ethnographicTerms/afset009065.html in uostockAPjpg
and I am deleting and reingesting bc of creators.

**Comment by jsimic** [comment]
http://vocab.getty.edu/aat/300218130 for http://id.loc.gov/vocabulary/ethnographicTerms/afset009065.html

**Comment by jsimic** [comment]
Raw statements: creator, note, colorContent, license
