### ISSUE TITLE
Lcsubject field isn't searchable

### ISSUE THREAD

**Issue by jechols** [OregonDigital/oregondigital#763]
Advanced search:

I'm pretty sure http://oregondigital.org/catalog/?utf8=%E2%9C%93&op=AND&all_fields=&title=&description=&creator=&lcsubject=baseball&date=&institution=&sort=score+desc&search_field=advanced&commit=Search ("baseball" in lcsubject) should yield some results given we have baseball-oriented lc subjects: http://oregondigital.org/catalog/?utf8=%E2%9C%93&f%5Bdesc_metadata__lcsubject_label_sim%5D%5B%5D=Baseball+players%24http%3A%2F%2Fid.loc.gov%2Fauthorities%2Fsubjects%2Fsh85012045&utf8=%E2%9C%93&op=AND&all_fields=&title=&description=&creator=&lcsubject=&date=&institution=&sort=score+desc&search_field=advanced&commit=Search

**Comment by terrellt** [comment]
Controlled vocabularies aren't searchable via advanced search because they're indexed to make the facets work. Do we WANT them to be, or should we just hide these? Should be noted, I'm not sure what it will take to make them work.

**Comment by jsimic** [comment]
@mickeroo @terrellt If this isn't working and we can't/don't want to make it work, we need to get the search box off the Advanced Search page. We're doing user testing soon...
