### ISSUE TITLE
Investigate Ghostscript upgrade/settings

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#767]
Ghostscript is hanging on creating JPGs from a few PDFs:

http://oregondigital.org/catalog/oregondigital:fx719w160
http://oregondigital.org/catalog/oregondigital:fx719t31p
http://oregondigital.org/catalog/oregondigital:fx719w37r

Ghostscript v9.15 is released. Currently v9.09 is on the worker server.

There could also be an issue with available fonts and substitution.

**Comment by wickr** [comment]
All 3 PDFs above work fine locally with an upgrade to Ghostscript v9.15

**Comment by terrellt** [comment]
Updated GS to 9.15, tested fx719t31p and it went through. Queued other two - we should be good.
