### ISSUE TITLE
Complex objects with more than 2 items don't work

### ISSUE THREAD

**Issue by mickeroo** [OregonDigital/oregondigital#768]
- RDF::List is not working
- There is a current need for this: Karen's project - items **do not** need to be in order
- Put statements in the holding objects like hasMember: ID and assume order
  - You lose contextual labels e.g. titles for TOC
  - Could do the RDF right but not lose it when we upgrade
  - Takes more work but does it better - and *should* work when we upgrade

Tasks:
  - [x] cdm2bag script would have to be updated
  - [x] Need to migrate existing list objects to flat
  - [x] Need to be able to index, so update indexing
  - [x] Views need to be able to use the new index appropriately

**Comment by mickeroo** [comment]
@terrellt do we just need to get the cdm2bag script updated to use the correct predicates and we're good to go?

**Comment by terrellt** [comment]
Yup
