### ISSUE TITLE
Change name for Ruth Mountaingrove Photographs

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#781]
A UO archivist wants the collection name changed for this collection http://oregondigital.org/sets/mountaingrove
to Lesbian Intentional Community: Ruth Mountaingrove (b. 1923) photographs

@wickr Can you update the set and facet name please? @mccallum Can you please update the collection page and the A-Z list?

Thanks! Let me know if anything is unclear.

**Comment by wickr** [comment]
@sseymore I updated the collection title, and it seems the collection page and A-Z list are fine, as they should pull from the same source and the title isn't hard-coded, I don't think.

The facet name should clear up soon I think, but if not we can keep an eye on it.

**Comment by sseymore** [comment]
Thank you!

**Comment by wickr** [comment]
@sseymore That's ok, I updated it again.

**Comment by sseymore** [comment]
Thanks @wickr !
