### ISSUE TITLE
download requiring login instead of IP

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/oregondigital#783]
Our users can't download the items in our collections that are IP restricted unless they are logged in. We need download regardless of log-in.

Example: http://oregondigital.org/catalog/oregondigital:df661w743

We had a similar problem with the audio download in UOVets, which is totally open (not IP restricted). I do not know why default downloads seem to require log-in. Is this an unintended feature that we got when the restricted for high res downloads was put on some archival photo collections?

**Comment by boockm** [comment]
My instincts are telling me that this could get messy, but I don't see a better way. I'm good with this.

**Comment by duncanbarth** [comment]
Since this apparently prevents people from actually accessing parts of our collections (the zip file thing has already bit a class), should we up the milestone from 'housekeeping' so we'll actually remember it in the next review?

**Comment by jechols** [comment]
(See issue #787 - we thought it was a different issue, but turns out it's the same problem but has a broader scope than this ticket's title suggested)
