### ISSUE TITLE
Ingest Archivision

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/oregondigital#786]
trial bag and ingest of 4 items. 
using ULAN for creators; needs to be added to system? and do we need to wait for ULAN to go live with rdf?

**Comment by lsat12357** [comment]
also sending jsmic a list of creators not found on the spreadsheet.

**Comment by lsat12357** [comment]
business, commerce and trade -> business; commerce;
Exhibitions--France--Paris -> Exhibitions; Paris;
contemporary (1960 to present) -> contemporary (1950 to present)

**Comment by lsat12357** [comment]
<http://example.org/ns/0> <http://purl.org/dc/terms/title> "CSEB (Computer Science and Engineering Building)" .
<http://example.org/ns/0> <http://purl.org/dc/terms/alternative> "York University Computer Science and Engineering Building" .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/cco/viewDescription> "General view, showing the southwest corner and looking along the south elevation" .
<http://example.org/ns/0> <http://purl.org/dc/elements/1.1/creator> <http://opaquenamespace.org/ns/creator/architectsAlliance> .
<http://example.org/ns/0> <http://purl.org/dc/elements/1.1/creator> <http://opaquenamespace.org/ns/creator/Busby+AssociatesArchitects> .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/cco/creatorDisplay> "architectsAlliance (architectural firm, established ca. 1993); Busby + Associates Architects (architectural firm, 1984-present)" .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/vra/earliestDate> "2000;" .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/vra/latestDate> "2001;" .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/vra/material> "glass, steel | construction" .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/vra/measurements> "9420 m2 (area, floor space)" .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/vra/culturalContext> <http://vocab.getty.edu/aat/300107962> .
<http://example.org/ns/0> <http://purl.org/dc/elements/1.1/coverage> "York University, Toronto, Ontario;" .
<http://example.org/ns/0> <http://purl.org/dc/elements/1.1/coverage> "Canada" .
<http://example.org/ns/0> <http://purl.org/dc/elements/1.1/coverage> "4700 Keele Street" .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/vra/workType> <http://vocab.getty.edu/aat/300263552> .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/vra/workType> <http://vocab.getty.edu/aat/300241583> .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/vra/workType> <http://vocab.getty.edu/aat/300004507> .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/vra/workType> <http://vocab.getty.edu/aat/300006495> .
<http://example.org/ns/0> <http://purl.org/dc/terms/subject> <http://opaquenamespace.org/ns/subject/architecturalexteriors> .
<http://example.org/ns/0> <http://purl.org/dc/terms/subject> <http://opaquenamespace.org/ns/subject/architecturalinteriors> .
<http://example.org/ns/0> <http://purl.org/dc/terms/subject> <http://opaquenamespace.org/ns/subject/contemporary1950topresent> .
<http://example.org/ns/0> <http://purl.org/dc/terms/subject> <http://opaquenamespace.org/ns/subject/engineeringindustry> .
<http://example.org/ns/0> <http://purl.org/dc/terms/subject> <http://vocab.getty.edu/aat/300077527> .
<http://example.org/ns/0> <http://purl.org/dc/terms/subject> <http://id.loc.gov/authorities/subjects/sh85006885> .
<http://example.org/ns/0> <http://purl.org/dc/terms/subject> <http://id.loc.gov/authorities/subjects/sh2003001382> .
<http://example.org/ns/0> <http://purl.org/dc/terms/description> "This was the test case for York University’s new 'green' design agenda. As the first green building in Ontario, it demonstrated for the first time that a sustainable approach could succeed in a cold climate. Undergraduate and graduate labs, classrooms, offices, and a 950-seat lecture hall complex are housed in a highly functional, flexible building that provides a transparent, animated and welcoming presence on Campus Walk, the University's main pedestrian thoroughfare. Every aspect of the building minimizes environmental impact: a highly efficient passive ventilation system, organized around 'thermal chimneys' and a bamboo-planted atrium; recyclable and low embodied energy materials; sun-shading devices on the south and west façades; and an extensive planted roof. CSEB has an energy consumption at 50% below conventionally built equivalents. The project was completed with Busby Perkins + Will." .
<http://example.org/ns/0> <http://purl.org/dc/terms/source> "Archivision, Inc." .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/localCollectionName> <http://opaquenamespace.org/ns/localCollectionName/ArchivisionAdditionalModuleFOUR> .
<http://example.org/ns/0> <http://purl.org/dc/terms/rights> <http://www.europeana.eu/rights/rr-r/> .
<http://example.org/ns/0> <http://opaquenamespace.org/rights/rightsHolder> "Scott Gilchrist, Archivision, Inc." .
<http://example.org/ns/0> <http://purl.org/dc/terms/type> <http://purl.org/dc/dcmitype/Image> .
<http://example.org/ns/0> <http://purl.org/dc/terms/identifier> "1A1-ALA-YEB-A1" .
<http://example.org/ns/0> <http://purl.org/dc/elements/1.1/subject> "green architecture; passive ventilation; Green buildings (Green technology); energy efficiency;" .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/set> <http://oregondigital.org/resource/oregondigital:aa-images> .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/contributingInstitution> <http://dbpedia.org/resource/University_of_Oregon> .
<http://example.org/ns/0> <http://purl.org/dc/terms/replaces> <http://oregondigital.org/u?/archivision,0> .

**Comment by lsat12357** [comment]
I will change vra/workType to rdf:type

**Comment by lsat12357** [comment]
1. will combine coverage strings into one string
2. in the test, coverage didn't get picked up, ended up in the raw statements

**Comment by lsat12357** [comment]
additionally add a triple with oregon:tgn and uri for city or country?

**Comment by jsimic** [comment]
Coverage is dce not dct

**Comment by jsimic** [comment]
@lsat12357 Checking bags. Here are the issues:
rightsHolder in the raw

**Comment by kestlund** [comment]
New vocab must be set up to render out of raw. Are URI's correct?  If so,
@lsat12357 can ingest and then add the vocab.
