### ISSUE TITLE
Can't download some files - 500 error

### ISSUE THREAD

**Issue by jechols** [OregonDigital/oregondigital#787]
We think this has to do with files for which we don't create derivatives.  For instance, zip files, excel files, etc.

NOTE: This stuff works fine if you're logged in!  Log out to reproduce the error.

Examples:
- http://oregondigital.org/catalog/oregondigital:df66wn02q - this is "application/octet-stream" (This is a jp2k that isn't encoded properly - but that's a whole different problem)
- http://oregondigital.org/catalog/oregondigital:df661w75c - this is "application/zip"

**Comment by jechols** [comment]
FYI, one of the files we needed access to was for a class - we're having to host the file ourselves for the time being.  Even though this affects only a handful of files, it's a pretty big problem.

**Comment by osulpweb** [comment]
Duplicate of #783?

**Comment by terrellt** [comment]
^ That was me.

**Comment by jechols** [comment]
Nope, we tested on some that weren't restricted (at least according to the rights statement).  And #783 doesn't indicate anything about a crash, so I didn't think it was related.

**Comment by jechols** [comment]
First problem: access errors somehow get translated into 500s through some magic I have yet to dig through.  This turns a relatively simple "access denied" into an "Internal Server Error" on production.

Second problem:

```ruby
  # In our downloads controller
  def can_download?
    return super if datastream_to_show == default_content_ds && default_content_ds.dsid != "content"
    return true if default_content_ds.dsid == "content" && current_ability.can?(:download, asset.class)
    return true if current_ability.can?(:create, asset.class)
    false
  end
```

The first line is what kills us - if the requested datastream is "content" and the default datastream is "content", we skip normal Hydra rules.  Meaning the user has to be given the ability to download the object type by its *class*.  In the case of a GenericAsset, "content" will be the **only** datastream, and therefore it has to be the default.  And as far as I can tell, we don't use the `:download` permission type at all.

Given this info, this is definitely the same problem as in #783 - the crash was what really made this ticket seem separate, but I'm guessing it just wasn't mentioned in the other ticket.

It sounds like discussion in #783 ended with being willing to give access to GenericAsset objects' content datastream.  I'm thinking the right approach is just to call super and then check other permissions if super returns false.  However, do we really want to handle permissions based on an object's class?  We don't seem to be using this feature, and it seems a little confusing to have rights based on Ruby classes rather than metadata.

My proposal is to fry most of the rules and allow anybody based on simple rights or admin overrides:

```ruby
  # In our downloads controller
  def can_download?
    return super || current_ability.can?(:create, asset.class)
  end
```

i.e., you either have rights as determined by the built-in rights management, or you have create access.

**Comment by jechols** [comment]
Given this is affecting classes, #783 was dropped into "housekeeping", and everybody's at code4lib, I'm going to just do the fix and submit a PR.

I'll also look at the error and try to figure out why it's turning into a 500 instead of giving a more useful "access denied" type of message.

**Comment by jechols** [comment]
Actual fix (without compromising all assets' content datastream): PR #789

We needed to retain the auto-denial of anonymous users when they weren't requesting the default datastream.

**Comment by jechols** [comment]
Still need to figure out why access denied errors are weird, so if that fix works, this bug still needs to stay open (or a new bug filed).

**Comment by jechols** [comment]
Figured out access control errors not propagating, but that PR (when I submit it) probably needs some discussion.  Turns out we aren't using the built-in Hydra controller behaviors, and I have no idea why... but I'm betting there's a good reason.

**Comment by jechols** [comment]
Fixed
