### ISSUE TITLE
Ingest bookarts

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/oregondigital#790]
sigh. technique should be hasTechnique.
rda probs might need to be fixed on app/models/datastream/oregon_rdf.rb, the #'s are missing
workType predicate in oregon_rdf.rb is listed as RDF.type, not as opns/vra/workType

**Comment by lsat12357** [comment]
contributor needs to be dce?

**Comment by lsat12357** [comment]
319 http://id.loc.gov/authorities/childrensSubjects/sj96005639 
typo in 583, 586

**Comment by lsat12357** [comment]
deleted bookarts in order to fix worktype and a few other errors; now erroring because nts use opns/contributor terms which no longer exist. will add terms to creators list before reingest.

**Comment by lsat12357** [comment]
@sseymore sorry more probs with bookarts, I think these vocabs are not currently ok with these preds; what should I replace with?
Term not in controlled vocabularies: http://id.loc.gov/authorities/names/n42023288.html 
Term not in controlled vocabularies: http://id.loc.gov/authorities/names/n86709774 
(with rdf type)
Term not in controlled vocabularies: http://id.loc.gov/authorities/classification/cf94049243
Term not in controlled vocabularies: http://id.loc.gov/authorities/classification/cf94050925  
Term not in controlled vocabularies: http://id.loc.gov/authorities/classification/cf05477436 
(with dce.contributor)
Term not in controlled vocabularies: http://www.rbms.info/committees/bibliographic_standards/controlled_vocabularies/binding/tr459.htm 
(with rdf type)

**Comment by sseymore** [comment]
Ok here are the replacements from the right vocabs:

Star Book: http://opaquenamespace.org/ns/workType/Starbook

Gatefold Book: http://opaquenamespace.org/ns/workType/Gatefoldbook

Flaubert: http://id.loc.gov/authorities/names/n79059896

Man Ray: http://id.loc.gov/authorities/names/n80019625 

Kent: http://id.loc.gov/authorities/names/n80026775

Clamshell boxes: http://opaquenamespace.org/ns/workType/Clamshellboxes

Thanks

**Comment by lsat12357** [comment]
some weirdness going on with bookarts http://oregondigital.org/bulk_tasks/4121, 
everything has errored upon reset/ingest
Unable to find 'oregondigital:df672b33v' in fedora. See logger for details.

**Comment by terrellt** [comment]
@lsat12357 Think I got that taken care of.
