### ISSUE TITLE
Ingest jsma

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/oregondigital#795]
for the items with any of the 5 ulan creators, add a creator display triple, first last

**Comment by lsat12357** [comment]
<http://example.org/ns/0> <http://purl.org/dc/terms/title> "Two Nude Men" .
<http://example.org/ns/0> <http://purl.org/dc/elements/1.1/creator> <http://vocab.getty.edu/ulan/500011051> .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/cco/creatorDisplay> "1606-1669" .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/vra/culturalContext> <http://vocab.getty.edu/aat/300111175> .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/vra/hasStylePeriod> <http://vocab.getty.edu/aat/300021444> .
<http://example.org/ns/0> <http://purl.org/dc/terms/date> "17th century" .
<http://example.org/ns/0> <http://www.loc.gov/standards/vracore/vocab/material> "Etching" .
<http://example.org/ns/0> <http://www.loc.gov/standards/vracore/vocab/measurements> "7-13/16 x 5-1/8 inches" .
<http://example.org/ns/0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vocab.getty.edu/aat/300264849> .
<http://example.org/ns/0> <http://purl.org/dc/terms/description> "print" .
<http://example.org/ns/0> <http://www.loc.gov/standards/mods/modsrdf/v1/#note> "Item information may be subject to verification." .
<http://example.org/ns/0> <http://purl.org/dc/terms/type> <http://purl.org/dc/dcmitype/Image> .
<http://example.org/ns/0> <http://purl.org/dc/terms/format> <http://purl.org/NET/mediatypes/image/jpeg> .
<http://example.org/ns/0> <http://opaquenamespace.org/rights/rightsHolder> "Jordan Schnitzer Museum of Art" .
<http://example.org/ns/0> <http://purl.org/dc/terms/rights> <http://www.europeana.eu/rights/rr-r/> .
<http://example.org/ns/0> <http://data.archiveshub.ac.uk/def/useRestrictions> "This item is restricted to University of Oregon authorized users for personal study, research, and teaching." .
<http://example.org/ns/0> <http://data.archiveshub.ac.uk/def/accessRestrictions> <http://opaquenamespace.org/ns/accessRestrictions/UOrestricted> .
<http://example.org/ns/0> <http://id.loc.gov/vocabulary/relators/rps> "University of Oregon, Jordan Schnitzer Museum of Art (Eugene, Oregon, United States)" .
<http://example.org/ns/0> <http://purl.org/dc/terms/identifier> "1965:11.3" .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/set> <http://oregondigital.org/resource/oregondigital:schnitzer-mofa> .
<http://example.org/ns/0> <http://purl.org/dc/terms/replaces> <http://oregondigital.org/u?/jsma,0> .

**Comment by lsat12357** [comment]
since ulan is live, did not add any creator display triples

**Comment by lsat12357** [comment]
changed rightsHolder to uri, changed vra predicates to opns/vra

**Comment by jsimic** [comment]
@lsat12357 Need to strip out all hasStylePeriod triples from all records. Not part of their original metadata.
