### ISSUE TITLE
Missing MA image

### ISSUE THREAD

**Issue by jechols** [OregonDigital/oregondigital#796]
I just happened to run across this while doing some more work on the MA site: http://oregondigital.org/catalog/oregondigital:df66p375w

Note that the thumbnail exists, but is really messed up: http://oregondigital.org/thumbnails/w/5/oregondigital-df66p375w.jpg

The medium image looks fairly close to what I'm seeing on the old site, oddly enough: http://oregondigital.org/media/medium-images/w/5/oregondigital-df66p375w.jpg

There could be others, I haven't done any kind of in-depth testing.

**Comment by terrellt** [comment]
Thumbnail looks busted to me, but the pyramidal looks right

**Comment by jechols** [comment]
Ah, you're right - I was making an assumption based on a PEBKAC error on my end.  So we just need to regenerate the thumbnail.

**Comment by mickeroo** [comment]
Trey re-ran derivatives and still got the same image.

**Comment by jechols** [comment]
Closing - nothing to be done without building a one-off thumbnail, which could easily be accidentally replaced
