### ISSUE TITLE
Give UO Rails Console Access

### ISSUE THREAD

**Issue by tpendragon** [OregonDigital/oregondigital#799]
Need SSH keys from UO developers (we could use your github ones if that's okay) and need to add appropriate IP ranges to firewall.

**Comment by duncanbarth** [comment]
Library Staff network in the Knight Library (which covers DSC and Jeremy) is 128.223.84.0/22

**Comment by kestlund** [comment]
I like the idea of using our Github keys is okay with Duncan.

**Comment by duncanbarth** [comment]
Whatever is fine with me. I'll leave it up to the devs as to how they want to do their key management.
