### ISSUE TITLE
Can't upload/review Emerald Media

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#805]
@terrellt : Paul (Harvey, the cataloger) hasn't been able to upload single issues of the Emerald this week, nor review one issue that is already uploaded. I tried and also get the "We're sorry, but something went wrong" message in both template ingest and review. The company is already inquiring where the issues are. Issue to review is Emerald Media, March 5, 2015: http://oregondigital.library.oregonstate.edu/catalog/oregondigital:fx719x06z

**Comment by terrellt** [comment]
Logs filled the disk again. =( Should be okay now.
