### ISSUE TITLE
derivatives PDFs still have issues for ODE

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/oregondigital#813]
Some old ODE PDFs are missing images.  Can we re-run derivates?

http://oregondigital.org/sets/daily-emerald/oregondigital:4t64gn84b#page/1/mode/1up

**Comment by terrellt** [comment]
@kestlund Is it possible to get a list of which ones are busted? I'd hate to rerun every one.

**Comment by kestlund** [comment]
This is the problem; we don't know which ones without clicking on each and
keep finding more. I could ask a student...

**Comment by terrellt** [comment]
@wickr Were you planning to do a big ingest, or can I queue up ~1500 PDFs for regeneration?

**Comment by wickr** [comment]
@terrellt Yes but probably not today. Go ahead and get the ODE ones going.

**Comment by terrellt** [comment]
Alright, queued derivatives for ODE.
