### ISSUE TITLE
PDF image generation taking too long

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/oregondigital#814]
PDF added to ODE yesterday still hasn't generated display.

http://oregondigital.org/sets/daily-emerald/oregondigital:fx719x700

![screen shot 2015-03-31 at 2 21 10 pm](https://cloud.githubusercontent.com/assets/2481327/6929635/372f8fb8-d7b1-11e4-9abe-1ae42afe53c5.png)

**Comment by mickeroo** [comment]
For what it's worth, there has been a lot of ingest work lately.  Between Building Oregon and Herbarium there are 15K derivatives jobs as well as 29K fetches queued at the moment so it may take a while to work through the backlog.

**Comment by terrellt** [comment]
14k derivatives to go. You all were busy.
