### ISSUE TITLE
Create ChinaVine collection

### ISSUE THREAD

**Issue by srabun** [OregonDigital/oregondigital#819]
We need to create a collection for ChinaVine. It will need to have complex objects and multiple file types/formats.

@wickr Do you need anything from us to get this going? We're working with a faculty member who has requested a May 18 deadline, so we want to get going asap...Thanks!

**Comment by wickr** [comment]
@srabun Use set title of 'ChinaVine' and ID of 'china-vine' ?

**Comment by sseymore** [comment]
@wickr It can be just chinavine for the collection ID.

**Comment by wickr** [comment]
@sseymore Ok thanks. 

The set is created and reviewed, so it's public. If you don't want it public yet I can un-review. 

The URI is http://oregondigital.org/resource/oregondigital:chinavine

**Comment by srabun** [comment]
@wickr @sseymore thank you! :)

**Comment by wickr** [comment]
I think this is completed. Feel free to reopen if needed.
