### ISSUE TITLE
What's the correct label for http://opaquenamespace.org/ns/rights/educational/ ?

### ISSUE THREAD

**Issue by jcoyne** [OregonDigital/oregondigital#824]
On this page https://oregondigital.org/copyright it says "Educational Use Only" but in the code (https://github.com/OregonDigital/oregondigital/blob/3a329dbb40af2fefe7a463257bc0563e10f73ffd/lib/oregon_digital/vocabularies/rights.rb#L7) it says "Educational Use Permitted". Which is correct?

**Comment by terrellt** [comment]
@kestlund ?

**Comment by kestlund** [comment]
"Educational Use Permitted"
