### ISSUE TITLE
Redirect for Collection Home pages and other supp pages on OD

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/oregondigital#831]
Now that we have mostly migrated, we need to put in redirects from the old A-Z page and links for the old collection home pages under the digcol directory.

**Comment by wickr** [comment]
@jsimic @lsat12357 Let me know if I missed anything. The old jsma 'page' may not need a redirect.

* http://oregondigital.org/digcol/ > http://oregondigital.org
* http://oregondigital.org/digcol/a2z.php > http://oregondigital.org/sets
* http://oregondigital.org/digcol/rights.php > http://oregondigital.org/copyright
* http://oregondigital.org/digcol/comments.php > http://oregondigital.org/contact

* http://oregondigital.org/cdm4/browse.php?CISOROOT=/rockshore93 > http://oregondigital.org/sets/rockyshore93
* http://oregondigital.org/digcol/afpep/ > http://oregondigital.org/sets/african-ephemera
* http://oregondigital.org/digcol/aaa/ > http://oregondigital.org/sets/aa-images
* http://oregondigital.org/digcol/bookarts/ > http://oregondigital.org/sets/artists-books
* http://oregondigital.org/digcol/bracero/ > http://oregondigital.org/sets/braceros
* http://oregondigital.org/digcol/archpnw/ > http://oregondigital.org/sets/building-or
* http://oregondigital.org/digcol/diss/ > http://oregondigital.org/sets/dissociation
* http://oregondigital.org/digcol/ulmann/ > http://oregondigital.org/sets/doris-ulmann
* http://oregondigital.org/digcol/fairbanks/ > http://oregondigital.org/sets/fairbanks
* http://oregondigital.org/digcol/gwilliams/ > http://oregondigital.org/sets/gwilliams
* http://oregondigital.org/digcol/gifford/ > http://oregondigital.org/sets/gifford
* http://oregondigital.org/digcol/sheetmusic/ > http://oregondigital.org/sets/sheetmusic
* http://oregondigital.org/digcol/gh/ > http://oregondigital.org/sets
* http://oregondigital.org/digcol/jasr/ > http://oregondigital.org/sets/jasr
* http://oregondigital.org/cdm4/results.php?&CISORESTMP=results.php&CISOVIEWTMP=item_viewer.php&CISOMODE=thumb&CISOGRID=thumbnail,A,1;title,A,1;creato,A,0;creata,200,0;none,A,0;20;title,none,none,none,none&CISOBIB=title,A,1,N;creato,A,0,N;creata,200,0,N;none,A,0,N;none,A,0,N;20;title,none,none,none,none&CISOTHUMB=20%20(5x4);title,none,none,none,none&CISOTITLE=20;title,none,none,none,none&CISOHIERA=20;creato,title,none,none,none&CISOSUPPRESS=1&CISOTYPE=browse&CISOROOT=%2Fjsma > http://oregondigital.org/sets/schnitzer-mofa
* http://oregondigital.org/digcol/comm/ > http://oregondigital.org/sets/mountaingrove
* http://oregondigital.org/digcol/lowenstam/ > http://oregondigital.org/sets/lowenstam
* http://oregondigital.org/digcol/maic/ > http://oregondigital.org/sets/maic
* http://oregondigital.org/digcol/folklore/ > http://oregondigital.org/sets/nw-folklife
* http://oregondigital.org/digcol/ode/ > http://oregondigital.org/sets/daily-emerald
* http://oregondigital.org/digcol/oimb > http://oregondigital.org/sets/oimb
* http://oregondigital.org/digcol/latinoherit/ > http://oregondigital.org/sets/or-latino-herit
* http://oregondigital.org/digcol/ormaps/ > http://oregondigital.org/sets/ormaps
* http://oregondigital.org/digcol/cultural/ > http://oregondigital.org/sets/oregon-multicultural-archives
* http://oregondigital.org/cdm4/browse.php?CISOROOT=/baseball > http://oregondigital.org/sets/osu-baseball
* http://oregondigital.org/digcol/archives/ > http://oregondigital.org/sets/osu-scarc
* http://oregondigital.org/digcol/herbarium/ > http://oregondigital.org/sets/herbarium
* http://oregondigital.org/cdm4/browse.php?CISOROOT=/streamsurve > http://oregondigital.org/sets/streamsurvey
* http://oregondigital.org/digcol/oac/ > http://oregondigital.org/sets/percent-for-art
* http://oregondigital.org/digcol/mh/ > http://oregondigital.org/sets/moorhouse
* http://oregondigital.org/digcol/corflood64/ > http://oregondigital.org/sets/corvallis-flood
* http://oregondigital.org/digcol/siuslaw/ > http://oregondigital.org/sets/siuslaw
* http://oregondigital.org/digcol/tlegacies/ > http://oregondigital.org/sets/tribal-legacies
* http://oregondigital.org/digcol/univ/ > http://oregondigital.org/sets/uo-arch-photos
* http://oregondigital.org/digcol/athletics/ > http://oregondigital.org/sets/uo-athletics
* http://oregondigital.org/digcol/uopres/ > http://oregondigital.org/sets/uo-president
* http://oregondigital.org/digcol/uostock/ > http://oregondigital.org/sets/uo-stock-photos
* http://oregondigital.org/digcol/wwdl/ > http://oregondigital.org/sets/western-waters

**Comment by jsimic** [comment]
@wickr All look good

**Comment by wickr** [comment]
These are in and live. Let me know if there's any issues.

**Comment by wickr** [comment]
I haven't heard about any issues, so I'm going to close this. If anything pops up let me know and/or file a new Issue.
