### ISSUE TITLE
Ingest chinavine

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/oregondigital#835]
@kestlund @jsimic @sseymore 
got a few cpds ingested, representing one trip/published materials
http://oregondigital.org/bulk_tasks/2481

they're kinda big

**Comment by terrellt** [comment]
wow

**Comment by lsat12357** [comment]
@srabun 
Term not in controlled vocabularies: http://opaquenamespace.org/ns/creator/ShandongUniversityofArtandDesign

**Comment by lsat12357** [comment]
and here's a link
http://oregondigital.org/bulk_task_children/1416521
@terrellt

**Comment by terrellt** [comment]
@lsat12357 The only supported vocabularies for contributingInstitution are https://github.com/OregonDigital/oregondigital/blob/master/lib/oregon_digital/vocabularies/institutions.rb#L4 and https://github.com/OregonDigital/oregondigital/blob/master/lib/oregon_digital/vocabularies/oregon_universities.rb#L4.

Do you want to add OpaqueNamespace creators too?

**Comment by lsat12357** [comment]
@jsimic @sseymore

**Comment by sseymore** [comment]
@terrellt What op_ns vocab is https://github.com/OregonDigital/oregondigital/blob/master/lib/oregon_digital/vocabularies/institutions.rb#L4 ? Here http://opaquenamespace.org/ns/oregondigitalorgs ? 

I can move that URI. The rest are dbpedia.

**Comment by lsat12357** [comment]
reminder: SS is rotating the images that need it and assembling them in separate directories for bagging.
