### ISSUE TITLE
Ingest artimages

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/oregondigital#842]
problem with term lookup for artcolls repositories: terms like "Archaeological Museum" map to multiple uris. jsimic reworking lookup terms to include city info.

**Comment by lsat12357** [comment]
<http://example.org/ns/0> <http://purl.org/dc/terms/title> "Demon with a lamp from Temple 9" .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/cco/creatorDisplay> "unknown (painter )" .
<http://example.org/ns/0> <http://purl.org/dc/terms/date> "9-10th century (created)" .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/vra/earliestDate> "0801" .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/vra/latestDate> "1000" .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/vra/material> "mural painting" .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/vra/measurements> "63.5 x 25.4 cm" .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/vra/culturalContext> <http://vocab.getty.edu/aat/300018279> .
<http://example.org/ns/0> <http://id.loc.gov/vocabulary/relators/rps> <http://opaquenamespace.org/ns/repository/MuseumfurIndischeKunst> .
<http://example.org/ns/0> <http://purl.org/dc/elements/1.1/coverage> "Temple 9, Bezeklik, Xinjiang Uygur Zizhiqu (formerSite), China" .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/tgn> <http://vocab.getty.edu/tgn/1000111> .
<http://example.org/ns/0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://opaquenamespace.org/ns/workType/painting> .
<http://example.org/ns/0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vocab.getty.edu/aat/300033618> .
<http://example.org/ns/0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vocab.getty.edu/aat/300033644> .
<http://example.org/ns/0> <http://purl.org/dc/terms/subject> <http://id.loc.gov/authorities/subjects/sh85089376> .
<http://example.org/ns/0> <http://purl.org/dc/terms/subject> <http://id.loc.gov/authorities/subjects/sh2008114280> .
<http://example.org/ns/0> <http://purl.org/dc/terms/subject> <http://id.loc.gov/authorities/subjects/sh85017454> .
<http://example.org/ns/0> <http://purl.org/dc/terms/subject> <http://opaquenamespace.org/ns/subject/Demons> .
<http://example.org/ns/0> <http://purl.org/dc/terms/subject> <http://id.loc.gov/authorities/subjects/sh85148563> .
<http://example.org/ns/0> <http://purl.org/dc/terms/isPartOf> "Bezeklik cave grottoes (formerlyPartOf)" .
<http://example.org/ns/0> <http://purl.org/dc/terms/source> "Bussagli, Mario; Central Asian Painting, Geneva: Editions d'Art Albert Skira S.A., 1979" .
<http://example.org/ns/0> <http://purl.org/ontology/holding#label> "2007_VRC_00043" .
<http://example.org/ns/0> <http://purl.org/dc/terms/rights> <http://creativecommons.org/publicdomain/mark/1.0/> .
<http://example.org/ns/0> <http://purl.org/dc/terms/type> <http://purl.org/dc/dcmitype/Image> .
<http://example.org/ns/0> <http://purl.org/dc/terms/identifier> "2007_VRC_00043" .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/set> <http://oregondigital.org/resource/oregondigital:aa-images> .
<http://example.org/ns/0> <http://opaquenamespace.org/ns/contributingInstitution> <http://dbpedia.org/resource/University_of_Oregon> .
<http://example.org/ns/0> <http://purl.org/dc/terms/replaces> <http://oregondigital.org/u?/artimages,0> .

**Comment by lsat12357** [comment]
<http://example.org/ns/36> <http://purl.org/dc/terms/title> "Douce Apocalypse, ca. 1270" .
<http://example.org/ns/36> <http://opaquenamespace.org/ns/cco/viewDescription> "He was with the saints. Revlations XIII: 7-10 (p. 50)" .
<http://example.org/ns/36> <http://opaquenamespace.org/ns/cco/creatorDisplay> "unknown (artist )" .
<http://example.org/ns/36> <http://purl.org/dc/terms/date> "ca. 1270" .
<http://example.org/ns/36> <http://opaquenamespace.org/ns/vra/earliestDate> "1265" .
<http://example.org/ns/36> <http://opaquenamespace.org/ns/vra/latestDate> "1275" .
<http://example.org/ns/36> <http://opaquenamespace.org/ns/vra/material> "illumination (image-making process)" .
<http://example.org/ns/36> <http://opaquenamespace.org/ns/vra/hasStylePeriod> <http://vocab.getty.edu/aat/300020775> .
<http://example.org/ns/36> <http://opaquenamespace.org/ns/vra/culturalContext> <http://vocab.getty.edu/aat/300111159> .
<http://example.org/ns/36> <http://id.loc.gov/vocabulary/relators/rps> <http://vocab.getty.edu/ulan/500309844> .
<http://example.org/ns/36> <http://opaquenamespace.org/ns/vra/idCurrentRepository> "Ms. Douce 180" .
<http://example.org/ns/36> <http://opaquenamespace.org/ns/tgn> <http://vocab.getty.edu/tgn/7011781> .
<http://example.org/ns/36> <http://opaquenamespace.org/ns/tgn> <http://vocab.getty.edu/tgn/7012044> .
<http://example.org/ns/36> <http://purl.org/dc/elements/1.1/coverage> "from Westminster or possibly Canterbury,London, England Canterbury, England, United Kingdom" .
<http://example.org/ns/36> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://opaquenamespace.org/ns/workType/manuscriptsandbooks> .
<http://example.org/ns/36> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vocab.getty.edu/aat/300028569> .
<http://example.org/ns/36> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vocab.getty.edu/aat/300265483> .
<http://example.org/ns/36> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vocab.getty.edu/aat/300264513> .
<http://example.org/ns/36> <http://purl.org/dc/terms/subject> <http://id.loc.gov/authorities/names/n79054379> .
<http://example.org/ns/36> <http://purl.org/dc/terms/subject> <http://id.loc.gov/authorities/names/n81065639> .
<http://example.org/ns/36> <http://purl.org/dc/terms/subject> <http://opaquenamespace.org/ns/subject/religiousSemitic> .
<http://example.org/ns/36> <http://purl.org/dc/terms/subject> <http://id.loc.gov/authorities/subjects/sh85116629> .
<http://example.org/ns/36> <http://purl.org/dc/terms/subject> <http://id.loc.gov/authorities/names/n78095796> .
<http://example.org/ns/36> <http://purl.org/dc/terms/subject> <http://id.loc.gov/authorities/names/n79060715> .
<http://example.org/ns/36> <http://purl.org/dc/terms/description> "This image detail was digitized to illustrate Costume of the period." .
<http://example.org/ns/36> <http://purl.org/ontology/holding#label> "89569" .
<http://example.org/ns/36> <http://purl.org/ontology/holding#label> "757 II Eng13 b-D74 17" .
<http://example.org/ns/36> <http://purl.org/dc/terms/rights> <http://creativecommons.org/publicdomain/mark/1.0/> .
<http://example.org/ns/36> <http://purl.org/dc/terms/type> <http://purl.org/dc/dcmitype/Image> .
<http://example.org/ns/36> <http://purl.org/dc/terms/identifier> "89569" .
<http://example.org/ns/36> <http://opaquenamespace.org/ns/set> <http://oregondigital.org/resource/oregondigital:aa-images> .
<http://example.org/ns/36> <http://opaquenamespace.org/ns/contributingInstitution> <http://dbpedia.org/resource/University_of_Oregon> .
<http://example.org/ns/36> <http://purl.org/dc/terms/replaces> <http://oregondigital.org/u?/artimages,36> .

**Comment by lsat12357** [comment]
second example is messy; one value for site, but two cities.

**Comment by lsat12357** [comment]
@jsimic: this errored
http://example.org/ns/102> <http://id.loc.gov/vocabulary/relators/rps> <http://vocab.getty.edu/ulan/500312780> .
that predicate not currently ok with ulan, but there are a lot of ulan uris in the lookup list

**Comment by lsat12357** [comment]
@jsimic: there are geonames uris in the city list; those won't work with the tgn predicate. So after consulting with SS, going to switch to dct.spatial whenever those show. hope that's ok.

**Comment by lsat12357** [comment]
@jsimic: there are 10 lcsubjects in the artcolls repos list. can these be replaced with terms from lcname?

**Comment by jsimic** [comment]
@lsat12357 Check all bags that ingested. Here are the issues, most of which we have discussed:

culturalContext in triples, not visible in public view
rps from op_ns not showing up in public view
title: Split into title and alternative. Is the script not through yet?
city/state, country, site detail -> coverage
ambiguous rps labels (no location info, i.e. Archaeological Museum)
