### ISSUE TITLE
Ingest Petrarch

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#844]
Please add Translator predicate to Creators.

http://id.loc.gov/vocabulary/relators/trl

**Comment by wickr** [comment]
@sseymore Do you want them faceted?

I was going to adjust Interviewee to be faceted, but probably leave Interviewer and Transcriber to not be.

**Comment by sseymore** [comment]
I'm going to defer to @jsimic on this.

**Comment by jsimic** [comment]
No, no facets.
