### ISSUE TITLE
Need a script for generating TIFF derivatives from a tiff

### ISSUE THREAD

**Issue by terrellt** [OregonDigital/oregondigital#853]

**Comment by terrellt** [comment]
@jechols Meant to be done ASAP.

**Comment by jechols** [comment]
I'm assuming this is more than a `find . -name "*.tiff" | xargs ...`, so what other info do I need here?

- The title implies just the pyramidal tiff.  No thumbnail/medium image?
- Is the input a bag or an individual file?
- Is the output a bag or just a pile of derivatives on disk?
- Is there any workflow needed?  i.e., pull all TIFFs from server/directory X, process, push derivatives up to server/directory Y

**Comment by terrellt** [comment]
Pyramidal, thumbnail, and medium. Input is a tiff. Output is three derivatives. No workflow yet, the output will be used to populate a bag.

**Comment by jechols** [comment]
If we're talking about strictly image in, images out, I'm thinking a simple bash script can do this in about ... I dunno, ten lines of code.  What am I missing here?

**Comment by terrellt** [comment]
Nothing. ASAP please

**Comment by jechols** [comment]
Oh we have some conditional stuff for 16-bit TIFFs - this'll be ruby after all I think

**Comment by jechols** [comment]
Super dumb, and I haven't yet actually tested it, but you keep saying "ASAP": https://github.com/jechols/derivatives

**Comment by jechols** [comment]
(that is, I haven't verified that the tiff is pyramidal, for instance - I did do a run and it produced files)

**Comment by jechols** [comment]
Verified output - seems good.  @terrellt, let me know if this is more or less what you were wanting.

**Comment by terrellt** [comment]
As long as @lsat12357 can use it I'm good.

**Comment by jechols** [comment]
Heh, as long as she has Ruby and libvips and image magick ...

I put it together with assumptions based on our old OD VMs

**Comment by terrellt** [comment]
Cool. @lsat12357 can you try it out?

**Comment by jechols** [comment]
Closing this - we didn't need it anyway
