### ISSUE TITLE
Data mismatch in lat/lng fields for Oregon Maps causing indexing problems

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#891]
Our Latitude and Longitude fields are in the Solr schema as tdoubles, for floating point numbers. 90 of the items in Oregon Maps have entries such as 'N46° 22' 30, N41° 52' 30'  These are causing index errors.

We either need to convert these latitude and longitude values to floating point, which would solve the index issues and give us numeric comparisons and easy plotting of points in the future. Or convert the Latitude and Longitude fields to strings, so they will accept any value, but we will lose numeric comparisons.

Further, there is more than 1 point in each field, I'm guessing to try and represent the bounding box. Although I also see the schema.org/box in the Unmapped Fields of the Ingest Form. I think we should keep Latitude and Longitude as single point values only, and expand the bounding box support if we want that.

@jsimic Any thoughts on this?

**Comment by jsimic** [comment]
@wickr I'm trying to think who would want to do a numeric comparison?

**Comment by jsimic** [comment]
@wickr Yes, let's use schema:box for boxes and keep lat/long at points.

**Comment by wickr** [comment]
@jsimic Not so much a person doing numeric comparisons, but if we add geosearching capabilities at some point, or 'search within 10 miles' type things, then the system will need floating point values for those.

**Comment by jsimic** [comment]
@wickr Let's convert!

**Comment by wickr** [comment]
Coordinates currently in Lat/Lng appear to match what's in the schema.org/box values. Need to confirm though. If so, can remove Lat/Lng values.

Need to get the Schema.org/Box showing up in system and Ingest Form.

**Comment by wickr** [comment]
@lsat12357 got these all cleaned up.
