### ISSUE TITLE
Change Publisher values to URIs, add Creator controlled vocabulary class to Publisher

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#898]
Publisher is not set to a controlled vocabulary class, so any time URIs are used they don't show up.

Check to make sure we don't have existing data in collections that includes both URIs and strings.

**Comment by wickr** [comment]
Items with Publisher:
* Total: 8425
* UO: 729
* OSU: 6682
  * Rocky Shore 93: 300
  * Middle East Waters: 5235
  * SCARC: 1108
  * Daily Barometer: 37

**Comment by lsat12357** [comment]
this seems to be it for UO:
oregondigital:fx71cj478	Free Men Speak, Inc.	
oregondigital:fx71cq835	N. J. Bocquet

**Comment by jsimic** [comment]
UO records updated.

**Comment by lsat12357** [comment]
in addition to loc names, opns creator and publisher, I found just a few using these:
http://id.loc.gov/vocabulary/organizations
and one of these
http://dbpedia.org/page

**Comment by jsimic** [comment]
@lsat12357  Can you scrape the loc orgs for me? I'll also put it the request on ticket #1274

**Comment by jsimic** [comment]
Changed LC orgs and wikidata entries to strings.

**Comment by jsimic** [comment]
Finished with the loc orgs and wikidata entries.

**Comment by wickr** [comment]
I ran another report and items in SCARC sets with Publisher text values now totaled 2605. I collapsed the list to unique values and Kevin is working on these, as well as the Middle East Waters values.

**Comment by sseymore** [comment]
@wickr going to double-check on this

**Comment by wickr** [comment]
Did a quick export today. Summary:
OSU: 8,624 values; 1156 are URIs, most text values are ready to be changed
UO: 5,953 values; all URIs

**Comment by wickr** [comment]
Now after known URI updates last week OSU is at 6,640 URI values out of 8,624 total.

**Comment by KevinJonesMeta** [comment]
URIs for OSU unique values ready. I'll replace 4 values through the workform because they are on multiple works with various publishers.

**Comment by wickr** [comment]
All replacements for OSU publisher values have been completed. Existing URIs as text have also been saved appropriately.
A full reindex of all OSU items with publisher values is currently running to ensure labels appear as expected.
