### ISSUE TITLE
Setting up regular OD backup 

### ISSUE THREAD

**Issue by mickeroo** [OregonDigital/oregondigital#900]
From OD meeting on 11/17/15:

Come up with cron job set of options, script and run tests, then report back to group on tests
Come up with schedule for running backups that is reasonable given time, network resources/impacts.

**Comment by jechols** [comment]
@decimalator: Did you test rsync with -c (checksumming) and --delete options?  We need to figure out timing for those to decide how often to run this.

**Comment by decimalator** [comment]
I'm running a new rsync now with -c and --delete, we'll see how it compares and whether it grinds parthenon and/or lib-hydra1 to a halt or not.

**Comment by jechols** [comment]
@decimalator / @duncanbarth: Has this been set up to run at a regular interval yet?
