### ISSUE TITLE
Store sessions in memcache

### ISSUE THREAD

**Issue by mickeroo** [OregonDigital/oregondigital#902]
From OD meeting on 11/17/15:

Store sessions in memcache
Verify that cookie error goes away
Check status of 502 error
Re-group

**Comment by jechols** [comment]
This is a dev thing, not an ops thing.  We need memcached's memory limit raised, but devs have to implement the memcached-based sessions.

**Comment by decimalator** [comment]
memory limit has already been increased from 256MB to 512MB

[root@lib-hydra1 ~]# ps ax | grep memcached | grep -v grep
 2983 ?        Ssl    0:02 memcached -d -p 11211 -u memcached -m 512 -c 1024 -P /var/run/memcached/memcached.pid

**Comment by jechols** [comment]
Assigning to myself so this doesn't get lost
