### ISSUE TITLE
N-triples validator?

### ISSUE THREAD

**Issue by mickeroo** [OregonDigital/oregondigital#912]
From OD meeting 11/16:

Check to make sure our triples are up to spec (Jeremy has noticed extra backslashes in some triples)
Let’s try to find a tool - Ruby RDF tools? Fix gem’s parser
Sheila ask RDF users or Hydra tech listserv: Does anyone know of a really good N-triples validator?

**Comment by srabun** [comment]
We found something! Does this work: http://librdf.org/ntriples/

**Comment by tpendragon** [comment]
RDF.rb's n-triples parser should be able to validate. If it doesn't, it's a bug, and I'm sure they'd be happy to fix it.

**Comment by jechols** [comment]
Closing - turns out the bad ntriples are bad data on our end, but they're *technically* valid.  i.e., "\\\bar" doesn't violate the spec even though it's certain we didn't mean for the object of the RDF statement to be a backslash followed by a backspace (ascii 8) followed by "ar".
