### ISSUE TITLE
PDF derivatives not working

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#962]
@wickr PDFs in UO Pres collection are blurry. Is this a deriv issue or a file issue? Do they just need to be forced to create derivs?

https://oregondigital.org/sets/uo-president/oregondigital:df66jr78z#page/1/mode/1up

This is also happening with new items that are being added:

https://oregondigital.org/catalog/oregondigital:fx71bj758#page/1/mode/1up

**Comment by wickr** [comment]
I think this is a file issue, before it gets to ingest. When I download the original ('High Resolution') files, the PDFs have very tiny pages.

Acrobat lists the page size as 1.71 x 2.5 inches

The Presidents one does have 9 tiny pages and 1 larger one. But even that last large one isn't too big.

**Comment by sseymore** [comment]
@wickr yeah, the jpegs that we made the pdfs from are 400 dpi with dimensions of around 800 x 1044. I tried recreating one with a higher dpi in the pdf of 300 and re-uploaded but the deriv is still blurry.

https://oregondigital.org/sets/uo-president/oregondigital:df66jr76d#page/1/mode/1up

Does this still have to do with size?

**Comment by sseymore** [comment]
nevermind.... I can fix it in Photoshop and re-upload. It is the sizing... got confused. Thanks!

**Comment by wickr** [comment]
Yeah. The new one is a little better, but the originals are still pretty small. They're not much bigger than some of our thumbnails.

Acrobat says 2.00 x 2.61 inches.

**Comment by wickr** [comment]
Ok great. Let me know if you still have issues with it, but a larger, better-quality PDF to start with should solve the issues. Once you get them fixed please close this ticket.
