### ISSUE TITLE
Look at scaling Hydra Rails across multiple VMs

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#969]
It's easier to add new VMs than it is to add more than 4 vCPUs. Since Rails is taking most of the CPU on lib-hydra1 right now, @decimalator suggested we look at making more than 1 VM for Rails.

Nginx can handle the load balancing.

It will need to use the same Mongo, and obviously the same Fedora. Same MySQL DB too.

We might have issues with sessions/cookies.
Also with statefiles or and other caches.

**Comment by srabun** [comment]
4 concurrent on priorities

**Comment by mellinma** [comment]
make sure OD 2 can handle this properly
